Repository channainfo/commissioner, pull requests merged in 2022-12, with the labels that each got.

#34 Authentication scope
  .gitignore
  Gemfile
  Gemfile.lock
  app/interactors/spree_cm_commissioner/firebase_id_token_provider.rb
  app/interactors/spree_cm_commissioner/user_id_token_authenticator.rb
  app/interactors/spree_cm_commissioner/user_id_token_checker.rb
  app/interactors/spree_cm_commissioner/user_identity_checker.rb
  app/interactors/spree_cm_commissioner/user_password_authenticator.rb
  app/interactors/spree_cm_commissioner/user_registration_with_id_token.rb
  app/models/spree/user_decorator.rb
  app/models/spree_cm_commissioner.rb
  app/models/spree_cm_commissioner/user_identity_provider.rb
  app/services/spree_cm_commissioner/user_authenticator.rb
  config/initializers/doorkeeper.rb
  config/locales/en.yml
  db/migrate/20221021043620_create_user_identity_providers.rb
  lib/spree_cm_commissioner/engine.rb
  lib/spree_cm_commissioner/factories.rb
  lib/spree_cm_commissioner/test_helper/factories/oauth_access_token_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/oauth_application_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/user_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/user_identity_provider_factory.rb
  spec/interactors/spree_cm_commissioner/firebase_id_token_provider_spec.rb
  spec/interactors/spree_cm_commissioner/user_id_token_authenticator_spec.rb
  spec/interactors/spree_cm_commissioner/user_id_token_checker_spec.rb
  spec/interactors/spree_cm_commissioner/user_identity_checker_spec.rb
  spec/interactors/spree_cm_commissioner/user_password_authenticator_spec.rb
  spec/interactors/spree_cm_commissioner/user_registration_with_id_token_spec.rb
  spec/models/spree_cm_commissioner/user_identity_provider_spec.rb
  spec/request/spree/spree_oauth_spec.rb
  spec/services/spree_cm_commissioner/user_authenticator_spec.rb
  spec/spec_helper.rb
  spec/support/doorkeeper_auth_helper.rb
  spec/support/json_helper.rb
Labels: enhancement, feature

#42 close #40 change include to has_key
  app/services/spree_cm_commissioner/user_authenticator.rb
Labels: bug

#44 close #43 add evm docs
  README.md
Labels: documentation

#57 close #56 add is_master to option type
  Gemfile
  Gemfile.lock
  app/models/spree/option_type_decorator.rb
  app/models/spree/product_decorator.rb
  app/models/spree/variant_decorator.rb
  app/overrides/spree/admin/option_types/_form/master.html.erb.deface
  app/overrides/spree/admin/products/_form/option_types.html.erb.deface
  app/views/shared/_option_type_field.erb
  db/migrate/20221214033306_add_is_master_to_spree_option_types.rb
  spec/models/spree/option_type_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/variant_spec.rb
Labels: core

#59 close #58 add page to set option values to master
  app/controllers/spree/admin/master_variant_controller.rb
  app/overrides/spree/admin/shared/_product_tabs/master_variant.html.erb.deface
  app/overrides/spree/admin/variants/_form/option_types_remover.html.erb.deface
  app/overrides/spree/admin/variants/_form/option_types_replacer.html.erb.deface
  app/views/spree/admin/master_variant/_form.html.erb
  app/views/spree/admin/master_variant/index.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: feature, core

#62 close #60 add master option value icon
  app/assets/images/cm-adjust.svg
  app/controllers/concerns/spree_cm_commissioner/icon_set_concern.rb
  app/controllers/spree/admin/vectors/icons_controller.rb
  app/controllers/spree/admin/vectors/option_values_controller.rb
  app/models/spree/option_value_decorator.rb
  app/models/spree_cm_commissioner/vector_icon.rb
  app/overrides/spree/admin/shared/sub_menu/_configuration/vectors.html.erb.deface
  app/views/spree/admin/master_variant/_form.html.erb
  app/views/spree/admin/shared/_icons_tabs.html.erb
  app/views/spree/admin/vectors/icons/index.html.erb
  app/views/spree/admin/vectors/option_values/index.html.erb
  config/routes.rb
  db/migrate/20221216065635_add_icon_to_spree_option_values.rb
Labels: feature

#64 close #63 finalize option type icons UI
  app/models/spree_cm_commissioner/vector_icon.rb
  app/overrides/spree/admin/option_types/index/actions.html.erb.deface
  app/overrides/spree/admin/products/_form/option_types.html.erb.deface
  app/views/spree/admin/master_variant/index.html.erb
  app/views/spree/admin/shared/_vectors_tabs.html.erb
  app/views/spree/admin/vectors/icons/index.html.erb
  app/views/spree/admin/vectors/option_values/index.html.erb
  config/locales/en.yml
  spec/models/spree_cm_commissioner/vector_icon_spec.rb
Labels: enhancement

#68 close #64 option value icon api
  app/assets/config/spree_cm_commissioner_manifest.js
  app/assets/images/cm-adjust.svg
  app/assets/images/cm-box.svg
  app/assets/images/cm-default-icon.svg
  app/models/spree/option_value_decorator.rb
  app/serializers/spree/v2/storefront/option_type_serializer_decorator.rb
  app/serializers/spree/v2/storefront/option_value_serializer_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  config/initializers/assets.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  spec/request/spree/api/v2/products_spec.rb
  spec/serializers/spree/v2/storefront/option_type_serializer_spec.rb
  spec/serializers/spree/v2/storefront/option_value_serializer_spec.rb
Labels: enhancement

#75 close #74 add attr_type and travel? to option type
  Gemfile
  Gemfile.lock
  app/models/concerns/spree_cm_commissioner/parameterize_name.rb
  app/models/spree/option_type_decorator.rb
  app/models/spree/option_value_decorator.rb
  app/models/spree/property_decorator.rb
  app/overrides/spree/admin/option_types/_form/attr_type.html.erb.deface
  app/overrides/spree/admin/option_types/_form/travel.html.erb.deface
  app/overrides/spree/admin/option_types/index/option_header.html.erb.deface
  app/overrides/spree/admin/option_types/index/option_row.html.erb.deface
  db/migrate/20221226032556_add_attr_type_to_spree_option_types.rb
  db/migrate/20221226035908_add_travel_bool_to_spree_option_types.rb
  spec/models/concerns/spree_cm_commissioner/parameterize_name_spec.rb
  spec/models/spree/option_type_spec.rb
  spec/serializers/spree/v2/storefront/option_value_serializer_spec.rb
  spec/spec_helper.rb
Labels: core

#82 close #76 add product type with enum
  app/models/concerns/spree_cm_commissioner/product_type.rb
  app/models/spree/product_decorator.rb
  app/models/spree/prototype_decorator.rb
  app/models/spree/variant_decorator.rb
  app/models/spree/vendor_decorator.rb
  app/overrides/spree/admin/products/_form/product_types.html.erb.deface
  app/overrides/spree/admin/products/new/product_from_prototype.html.erb.deface
  app/overrides/spree/admin/prototypes/_form/product_type.html.erb.deface
  app/overrides/spree/admin/prototypes/show/product_type.html.erb.deface
  app/overrides/spree/admin/vendors/_form/product_type.html.erb.deface
  app/views/shared/_product_type_field.erb
  db/migrate/20221229075014_add_product_type.rb
  spec/interactors/spree_cm_commissioner/vendor_updater_spec.rb
  spec/models/spree/prototype_spec.rb
  spec/models/spree/vendor_spec.rb
Labels: core, view
