Repository channainfo/commissioner, pull requests merged in 2023-09, with the labels that each got.

#531 Close #530 create request booking state updater interactor
  Gemfile.lock
  app/controllers/spree/telegram/orders_controller.rb
  app/interactors/spree_cm_commissioner/order_accepted_state_updater.rb
  app/interactors/spree_cm_commissioner/order_rejected_state_updater.rb
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  config/routes.rb
  db/migrate/20230829031739_add_need_confirmation_to_spree_product.rb
  db/migrate/20230829032126_add_accepted_at_to_spree_line_item.rb
  db/migrate/20230829032730_add_accepted_by_to_spree_line_item.rb
  db/migrate/20230829050132_add_rejected_by_to_spree_line_item.rb
  db/migrate/20230830093155_add_rejected_at_to_spree_line_item.rb
  db/migrate/20230901134307_add_request_state_to_spree_order.rb
  db/migrate/20230901135805_add_remark_to_spree_line_item.rb
  spec/interactors/spree_cm_commissioner/order_accepted_state_updater_spec.rb
  spec/interactors/spree_cm_commissioner/order_rejected_state_updater_spec.rb
Labels: backend

#538 close #537 user request booking notification
  app/interactors/spree_cm_commissioner/order_accepted_notification_sender.rb
  app/interactors/spree_cm_commissioner/order_rejected_notification_sender.rb
  app/notifications/spree_cm_commissioner/order_accepted_notification.rb
  app/notifications/spree_cm_commissioner/order_rejected_notification.rb
  config/locales/en.yml
  config/locales/km.yml
  spec/interactors/spree_cm_commissioner/order_accepted_notification_sender_spec.rb
  spec/interactors/spree_cm_commissioner/order_rejected_notification_sender_spec.rb
Labels: backend

#536 close #535 Validiate token before register user with pin code
  app/controllers/spree/api/v2/storefront/account_checker_controller.rb
  app/controllers/spree/api/v2/storefront/user_registration_with_pin_codes_controller.rb
  config/routes.rb
Labels: bug

#541 close #540 fix inconsistent pin_code_token and pin_code name
  app/controllers/spree/api/v2/storefront/pin_code_checkers_controller.rb
  app/interactors/spree_cm_commissioner/pin_code_checker.rb
  app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
  app/models/spree_cm_commissioner/pin_code.rb
  spec/interactors/spree_cm_commissioner/pin_code_checker_spec.rb
  spec/request/spree/api/v2/controller/pin_code_checkers_controller_spec.rb
Labels: enhancement

#539 Hotel Confirmation
  Gemfile.lock
  app/controllers/spree/telegram/orders_controller.rb
  app/interactors/spree_cm_commissioner/order_accepted_notification_sender.rb
  app/interactors/spree_cm_commissioner/order_accepted_state_updater.rb
  app/interactors/spree_cm_commissioner/order_rejected_notification_sender.rb
  app/interactors/spree_cm_commissioner/order_rejected_state_updater.rb
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/notifications/spree_cm_commissioner/order_accepted_notification.rb
  app/notifications/spree_cm_commissioner/order_rejected_notification.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20230829031739_add_need_confirmation_to_spree_product.rb
  db/migrate/20230829032126_add_accepted_at_to_spree_line_item.rb
  db/migrate/20230829032730_add_accepted_by_to_spree_line_item.rb
  db/migrate/20230829050132_add_rejected_by_to_spree_line_item.rb
  db/migrate/20230830093155_add_rejected_at_to_spree_line_item.rb
  db/migrate/20230901134307_add_request_state_to_spree_order.rb
  db/migrate/20230901135805_add_remark_to_spree_line_item.rb
  spec/interactors/spree_cm_commissioner/order_accepted_notification_sender_spec.rb
  spec/interactors/spree_cm_commissioner/order_accepted_state_updater_spec.rb
  spec/interactors/spree_cm_commissioner/order_rejected_notification_sender_spec.rb
  spec/interactors/spree_cm_commissioner/order_rejected_state_updater_spec.rb
Labels: feature

#544 close #532 transit route setup
  app/controllers/spree/transit/base_controller.rb
  app/controllers/spree/transit/reservations_controller.rb
  app/views/spree/layouts/transit.html.erb
  app/views/spree/transit/reservations/index.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: backend, transit

#543 close #542 rename vendor state to default state to avoid confusion, add to serializer
  app/models/spree_cm_commissioner/state_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/queries/spree_cm_commissioner/accommodation_query.rb
  app/serializers/spree/v2/storefront/accommodation_serializer.rb
  app/serializers/spree/v2/storefront/option_value_serializer_decorator.rb
  app/serializers/spree/v2/storefront/stock_location_serializer_decorator.rb
  db/migrate/20230905090812_rename_spree_vendors_state_id_column_to_default_state_id.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_factory.rb
  spec/interactors/spree_cm_commissioner/accommodation_search_detail_spec.rb
  spec/interactors/spree_cm_commissioner/state_updater_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/state_spec.rb
  spec/models/spree/stock_location_spec.rb
  spec/models/spree/vendor_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/fixed_date_spec.rb
  spec/queries/spree_cm_commissioner/accommodation_query_spec.rb
  spec/request/spree/api/v2/accommodations_spec.rb
  spec/request/spree/api/v2/nearby_places_spec.rb
  spec/serializers/spree/v2/storefront/accommodation_serializer_spec.rb
  spec/serializers/spree/v2/storefront/stock_location_serializer_spec.rb
Labels: enhancement, api

#548 close #546 transit location creation
  app/controllers/spree/transit/locations_controller.rb
  app/models/spree_cm_commissioner/state_decorator.rb
  app/views/spree/transit/locations/_form.html.erb
  app/views/spree/transit/locations/edit.html.erb
  app/views/spree/transit/locations/index.html.erb
  app/views/spree/transit/locations/new.html.erb
  app/views/spree/transit/shared/_header.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  app/views/spree/transit/shared/_vendor_switcher.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: backend, transit

#559 Close #558 request orders api
  app/controllers/spree/api/v2/storefront/account/orders_controller_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
Labels: api

#561 close #560 refactor order webhook request body
  app/models/spree_cm_commissioner/order_decorator.rb
  app/serializers/concerns/spree_cm_commissioner/api/v2/resource_serializer_concern_decorator.rb
Labels: chore

#521 close #520 added a qrcode payment field to vendor
  app/controllers/spree/admin/vendors_controller_decorator.rb
  app/controllers/spree/billing/base_controller.rb
  app/controllers/spree/billing/products_controller.rb
  app/controllers/spree/billing/vendors_controller.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/models/spree_cm_commissioner/vendor_payment_qrcode.rb
  app/overrides/spree/admin/variants/index/variants_header.html.erb.deface
  app/overrides/spree/admin/vendors/_form/image_logo.html.erb.deface
  app/views/spree/billing/products/_form.html.erb
  app/views/spree/billing/shared/_invoice.html.erb
  app/views/spree/billing/shared/_vendor_switcher.html.erb
  app/views/spree/billing/shared/sub_menu/_setting.html.erb
  app/views/spree/billing/vendors/_form.html.erb
  app/views/spree/billing/vendors/edit.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: backend, billing

#557 Close #547 transit branch setup
  app/controllers/spree/transit/base_controller.rb
  app/controllers/spree/transit/branches_controller.rb
  app/models/spree_cm_commissioner/branch.rb
  app/models/spree_cm_commissioner/place.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/transit/branches/_form.html.erb
  app/views/spree/transit/branches/edit.html.erb
  app/views/spree/transit/branches/index.html.erb
  app/views/spree/transit/branches/new.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230906072540_add_type_to_spree_cm_commissioner_place.rb
  db/migrate/20230907094354_add_state_id_to_spree_cm_commissioner_place.rb
  db/migrate/20230911080543_add_vendor_id_to_cm_place.rb
  vendor/assets/javascripts/map/map-picker.js
Labels: backend, transit

#565 close #562 add taxon assets fields to admin
  app/controllers/spree/admin/taxons_controller_decorator.rb
  app/models/spree_cm_commissioner/taxon_app_banner.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/taxon_web_banner.rb
  app/overrides/spree/admin/taxons/_form/assets_form.html.erb.deface
  app/overrides/spree/admin/taxons/_form/category_icon_field.html.erb.deface
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: view, backend

#568 close #567 add default state to product
  app/models/spree_cm_commissioner/product_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
Labels: enhancement

#572 Close #550 Transit Stop setup
  app/controllers/spree/transit/base_controller.rb
  app/controllers/spree/transit/stops_controller.rb
  app/models/spree_cm_commissioner/state_decorator.rb
  app/models/spree_cm_commissioner/stop.rb
  app/views/spree/transit/locations/index.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  app/views/spree/transit/stops/_filters.html.erb
  app/views/spree/transit/stops/_form.html.erb
  app/views/spree/transit/stops/edit.html.erb
  app/views/spree/transit/stops/index.html.erb
  app/views/spree/transit/stops/new.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230913050549_add_code_to_cm_place.rb
  db/migrate/20230913050637_add_branch_id_to_cm_place.rb
Labels: backend

#580 close #576 route setup
  app/controllers/spree/transit/routes_controller.rb
  app/controllers/spree/transit/stops_controller.rb
  app/models/concerns/spree_cm_commissioner/product_type.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/overrides/spree/admin/option_types/_option_value_fields/option_value_replacer.html.erb.deface
  app/views/spree/transit/branches/_form.html.erb
  app/views/spree/transit/routes/_form.html.erb
  app/views/spree/transit/routes/edit.html.erb
  app/views/spree/transit/routes/index.html.erb
  app/views/spree/transit/routes/new.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230914040528_add_short_name_and_url_to_spree_product.rb
Labels: backend, transit

#575 close #574 add account linkages api
  app/controllers/spree/api/v2/storefront/user_account_linkages_controller.rb
  app/interactors/spree_cm_commissioner/account_linkage.rb
  app/request_schemas/spree_cm_commissioner/user_account_linkage_request_schema.rb
  app/serializers/spree_cm_commissioner/v2/storefront/user_identity_provider_serializer.rb
  config/routes.rb
  spec/interactors/spree_cm_commissioner/account_linkage_spec.rb
Labels: api

#579 Close #578 add need confirmation checkbox
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/overrides/spree/admin/products/_form/need_confirmation_checkbox.html.erb.deface
  app/overrides/spree/admin/products/new/need_confirmation_checkbox.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: view, backend

#582 close #577 add exception handler with telegram
  README.md
  app/controllers/concerns/spree_cm_commissioner/exception_notificable.rb
  app/controllers/spree_cm_commissioner/application_controller_decorator.rb
  app/exception_notifier/spree_cm_commissioner/telegram_notifier.rb
  config/initializers/exception_notification.rb
  lib/spree_cm_commissioner.rb
  spree_cm_commissioner.gemspec
Labels: feature

#585 Close #584 cannot transition request state
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/order_decorator.rb
Labels: bug

#573 Close #566 add branch filtering
  app/controllers/spree/transit/branches_controller.rb
  app/views/spree/transit/branches/_filter_form.erb
  app/views/spree/transit/branches/index.html.erb
  app/views/spree/transit/stops/_form.html.erb
  config/locales/en.yml
Labels: backend, transit

#586 Close #549 Add Location Filtering
  app/controllers/spree/transit/locations_controller.rb
  app/models/spree_cm_commissioner/state_decorator.rb
  app/views/spree/transit/locations/_filter_form.erb
  app/views/spree/transit/locations/index.html.erb
  config/locales/en.yml
Labels: backend, transit

#589 close #587 auto add option value once new place is created
  app/models/spree_cm_commissioner/stop.rb
  lib/spree_cm_commissioner/test_helper/factories/branch_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/stop_factory.rb
  spec/models/spree_cm_commissioner/stop_spec.rb
Labels: backend, transit

#592 close #591 undefine try_spree_current_user on exception notifier
  app/controllers/concerns/spree_cm_commissioner/exception_notificable.rb
Labels: bug

#601 Close #600 multiple db support ( master and read replica)
  Gemfile.lock
  README.md
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/controllers/spree_cm_commissioner/admin/user_sessions_controller_decorator.rb
  app/controllers/spree_cm_commissioner/application_controller_decorator.rb
Labels: core

#603 Close #602 send pin code template
  app/views/spree_cm_commissioner/pin_code_mailer/send_pin_code.html.erb
Labels: view

#597 Close #594 Add Stop Filtering
  app/controllers/spree/transit/stops_controller.rb
  app/models/spree_cm_commissioner/stop.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/transit/stops/_filters.html.erb
Labels: backend, transit

#605 close #604 add admin user identity type controller
  app/controllers/spree/admin/user_identity_providers_controller.rb
  app/overrides/spree/admin/users/_tabs/tabs.html.erb.deface
  app/views/spree/admin/user_identity_providers/_form.html.erb
  app/views/spree/admin/user_identity_providers/edit.html.erb
  app/views/spree/admin/user_identity_providers/index.html.erb
  app/views/spree/admin/user_identity_providers/new.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: backend

#607 Close #606 order products taxons api
  Gemfile.lock
  app/controllers/spree/api/v2/storefront/order_products_taxons_controller.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/overrides/spree/admin/taxons/_form/custom_redirect_url.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  config/routes.rb
  db/migrate/20230921044620_add_custom_redirect_url_to_spree_taxon.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: api

#609 Close #608 fix dashboard show cause db connection to fail
  app/controllers/spree_cm_commissioner/admin/dashboard_controller_decorator.rb
Labels: enhancement

#611 close #610 set telegram channel to vendor & list authorized telegram users
  app/controllers/spree/admin/vendor_authorized_users_controller.rb
  app/exception_notifier/spree_cm_commissioner/telegram_notifier.rb
  app/interactors/spree_cm_commissioner/telegram_chats_finder.rb
  app/models/concerns/spree_cm_commissioner/vendor_preference.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/admin/shared/_vendor_tabs.html.erb
  app/views/spree/admin/vendor_authorized_users/index.html.erb
  config/initializers/telegram_bot.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20230920100147_add_preferences_to_spree_vendor.rb
  spec/interactors/spree_cm_commissioner/telegram_chats_finder_spec.rb
  spec/models/spree/vendor_spec.rb
Labels: feature, backend

#615 Enhance wrong role db connection #614
  app/controllers/spree_cm_commissioner/admin/products_controller_decorator.rb
  app/controllers/spree_cm_commissioner/admin/user_sessions_controller_decorator.rb
  app/controllers/spree_cm_commissioner/api/v2/storefront/checkout_controller_decorator.rb
Labels: enhancement

#613 Close #612 update find order by id to number
  app/controllers/spree/api/v2/storefront/notifications_controller.rb
  app/controllers/spree/api/v2/storefront/order_products_taxons_controller.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/order_decorator.rb
Labels: enhancement, api

#622 close #621 add gender to serializer
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
Labels: api

#624 close #623 send pin code to telegram for debugging purpose
  README.md
  app/interactors/spree_cm_commissioner/pin_code_sender.rb
  app/interactors/spree_cm_commissioner/telegram_debug_pin_code_sender.rb
  app/jobs/spree_cm_commissioner/telegram_debug_pin_code_sender_job.rb
  lib/spree_cm_commissioner/test_helper/factories/pin_code_factory.rb
  spec/interactors/spree_cm_commissioner/telegram_debug_pin_code_sender_spec.rb
  spec/jobs/spree_cm_commissioner/telegram_debug_pin_code_sender_job_spec.rb
Labels: chore

#625 Close #599 bookme+ email order confirmation
  Gemfile.lock
  app/assets/images/cm-bookme-plus-icon.svg
  app/assets/images/cm-striaght-line-icon.svg
  app/assets/images/event-mailer-bg.png
  app/assets/stylesheets/spree_cm_commissioner/mailer/order/style.scss
  app/helpers/spree/mail_helper_decorator.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/views/spree/order_mailer/confirm_email.html.erb
  app/views/spree_cm_commissioner/layouts/order_mailer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_customer_info.html.erb
  app/views/spree_cm_commissioner/order_mailer/_footer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  app/views/spree_cm_commissioner/order_mailer/_header.html.erb
  app/views/spree_cm_commissioner/order_mailer/_info_notice.html.erb
  app/views/spree_cm_commissioner/order_mailer/_purchased_items.html.erb
  app/views/spree_cm_commissioner/order_mailer/_purchased_summary.html.erb
  app/views/spree_cm_commissioner/order_mailer/_support_contact.html.erb
  app/views/spree_cm_commissioner/order_mailer/_your_booking.html.erb
  app/views/spree_cm_commissioner/order_mailer/event/_event_detail.html.erb
  app/views/spree_cm_commissioner/order_mailer/hotel/_booking_detail.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_items.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_line_item.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_summary.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_vendor_info.html.erb
  config/locales/en.yml
  config/locales/km.yml
  lib/spree_cm_commissioner.rb
  spree_cm_commissioner.gemspec
Labels: enhancement, view

#633 close #632 refactor user identities authentication
  app/controllers/spree/api/v2/storefront/account_checker_controller.rb
  app/interactors/spree_cm_commissioner/existing_account_checker.rb
  app/interactors/spree_cm_commissioner/user_password_authenticator.rb
  app/models/concerns/spree_cm_commissioner/phone_number_sanitizer.rb
  app/models/concerns/spree_cm_commissioner/user_identity.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/services/spree_cm_commissioner/user_authenticator.rb
  config/initializers/doorkeeper.rb
  lib/spree_cm_commissioner/test_helper/factories/user_factory.rb
  spec/interactors/spree_cm_commissioner/user_password_authenticator_spec.rb
  spec/models/spree_cm_commissioner/user_spec.rb
  spec/request/spree/spree_oauth_spec.rb
  spec/services/spree_cm_commissioner/user_authenticator_spec.rb
Labels: enhancement

#631 close #630 add application controller decorator to ActionController::API
  app/controllers/spree_cm_commissioner/action_controller/api_decorator.rb
Labels: core

#627 close #626 fix cannot sum vendor total inventory to state
  app/models/spree_cm_commissioner/state_decorator.rb
  spec/models/spree/state_spec.rb
Labels: bug

#635 close #634 add forget password controller
  app/controllers/spree/api/v2/storefront/reset_passwords_controller.rb
  app/interactors/spree_cm_commissioner/user_forgotten_password_updater.rb
  app/serializers/spree_cm_commissioner/v2/storefront/reset_password_serializer.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  spec/interactors/spree_cm_commissioner/user_forgotten_password_updater_spec.rb
Labels: api

#629 Close #628 line-items api
  app/controllers/spree/api/v2/storefront/account/orders_controller_decorator.rb
  app/controllers/spree/api/v2/storefront/line_items_controller.rb
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree/v2/storefront/line_item_order_serializer.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  config/routes.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: api, backend
