Repository channainfo/commissioner, pull requests merged in 2023-03, with the labels that each got.

#215 Close #214 add vendor kind option values to vendor serializer
  app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/vendor_serializer_spec.rb
Labels: api

#204 close #202 validate merchant users
  app/controllers/spree/admin/merchant/base_controller.rb
  app/controllers/spree/admin/merchant/errors_controller.rb
  app/controllers/spree/admin/merchant/users_controller.rb
  app/controllers/spree/admin/merchants/base_controller.rb
  app/errors/spree_cm_commissioner/unauthorized_vendor_error.rb
  app/views/spree/admin/merchant/errors/forbidden.html.erb
  app/views/spree/admin/merchant/shared/_header.html.erb
  app/views/spree/admin/merchant/shared/_main_menu.html.erb
  app/views/spree/admin/merchant/shared/_vendor_switcher.html.erb
  app/views/spree/admin/merchant/users/index.html.erb
  app/views/spree/layouts/error_template.html.erb
  app/views/spree/layouts/merchant.html.erb
  config/routes.rb
Labels: backend

#208 close #205 add phone number to order
  Gemfile
  Gemfile.lock
  app/interactors/spree_cm_commissioner/phone_number_parser.rb
  app/models/concerns/spree_cm_commissioner/phone_number_sanitizer.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree/v2/storefront/cart_serializer_decorator.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  config/initializers/phonelib.rb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20230228032325_add_phone_number_to_spree_order.rb
  db/migrate/20230228083928_add_phone_number_to_spree_user.rb
  spec/interactors/spree_cm_commissioner/phone_number_parser_spec.rb
  spec/models/spree/order_spec.rb
  spec/serializers/spree/v2/storefront/cart_serializer_spec.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
Labels: enhancement, api, core

#218 close #216 improve require dependencies
  Gemfile
  Gemfile.lock
  db/migrate/20221017132636_add_lat_lon_to_spree_stock_locations.rb
  db/migrate/20221021043620_create_user_identity_providers.rb
  db/migrate/20221111013544_add_min_max_price_to_spree_vendors.rb
  db/migrate/20221227084456_add_permanent_stock_to_spree_variants.rb
  db/migrate/20230102035446_add_kind_to_spree_option_types.rb
  db/migrate/20230105074914_add_fields_to_spree_line_items.rb
  db/migrate/20230109062713_add_total_inventory_and_state_id_to_spree_vendors.rb
  db/migrate/20230111022259_create_spree_cm_commissioner_vendor_option_types.rb
  db/migrate/20230117021850_create_spree_cm_commissioner_option_value_vendors.rb
  db/migrate/20230119100844_add_star_rating_to_spree_vendor.rb
  db/migrate/20230120091001_add_short_description_to_spree_vendor.rb
  db/migrate/20230120115157_add_total_inventory_to_spree_states.rb
  db/migrate/20230125131429_add_promoted_to_spree_option_type.rb
  lib/generators/spree_cm_commissioner/install/install_generator.rb
  lib/spree_cm_commissioner.rb
  spree_cm_commissioner.gemspec
Labels: chore

#207 Close #206 get nearby places from google api
  app/controllers/spree/admin/nearby_places_controller.rb
  app/controllers/spree/admin/vendors_controller_decorator.rb
  app/interactors/spree_cm_commissioner/nearby_place_distance_finder.rb
  app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/models/spree_cm_commissioner/vendor_place.rb
  app/views/spree/admin/nearby_places/_form.html.erb
  app/views/spree/admin/nearby_places/index.html.erb
  app/views/spree/admin/nearby_places/new.html.erb
  config/initializers/google_map.rb
  spec/cassettes/SpreeCmCommissioner_NearbyPlaceFinder/_call/should_get_20_nearby_places_for_vendor.yml
  spec/cassettes/SpreeCmCommissioner_VendorNearbyPlaceBuilder/_call/should_get_20_nearby_places_for_vendor.yml
  spec/interactors/spree_cm_commissioner/builder_nearby_place_builder_spec.rb
  spec/models/spree_cm_commissioner/vendor_place_spec.rb
Labels: api

#220 close #219 added crud and search operation to merchant users
  app/controllers/spree/admin/merchant/base_controller.rb
  app/controllers/spree/admin/merchant/users_controller.rb
  app/views/spree/admin/merchant/errors/forbidden.html.erb
  app/views/spree/admin/merchant/shared/_vendor_switcher.html.erb
  app/views/spree/admin/merchant/users/_form.html.erb
  app/views/spree/admin/merchant/users/_tabs.html.erb
  app/views/spree/admin/merchant/users/edit.html.erb
  app/views/spree/admin/merchant/users/index.html.erb
  app/views/spree/admin/merchant/users/new.html.erb
  app/views/spree/admin/vectors/icons/index.html.erb
  config/routes.rb
  spec/models/spree_cm_commissioner/vector_icon_spec.rb
Labels: backend

#226 close #225 add pricing model by extend with promotion
  app/interactors/spree_cm_commissioner/vendor_price_rules_activator.rb
  app/models/spree_cm_commissioner/adjustment_decorator.rb
  app/models/spree_cm_commissioner/listing_price.rb
  app/models/spree_cm_commissioner/pricing_model.rb
  app/models/spree_cm_commissioner/pricing_model/actions/create_listing_price_adjustment.rb
  app/models/spree_cm_commissioner/pricing_model/rules/fixed_date.rb
  app/models/spree_cm_commissioner/pricing_model_action.rb
  app/models/spree_cm_commissioner/pricing_model_rule.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  db/migrate/20230310032336_add_vendor_reference_to_spree_promotion_rule.rb
  db/migrate/20230310100611_create_spree_cm_commissioner_listing_prices.rb
  db/migrate/20230313080741_change_column_order_null_to_spree_adjustments.rb
  lib/spree_cm_commissioner/test_helper/factories/listing_price_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_model_action_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_model_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_model_rule_factory.rb
  spec/interactors/spree_cm_commissioner/vendor_price_rules_activator_spec.rb
  spec/models/spree/adjustment_spec.rb
  spec/models/spree/vendor_spec.rb
  spec/models/spree_cm_commissioner/listing_price_spec.rb
Labels: feature

#229 close #228 setup spree backend js & stylesheet decorator
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/stylesheets/spree_cm_commissioner/backend.css
  app/assets/stylesheets/spree_cm_commissioner/backend/commissioner_admin.css.scss
  lib/generators/spree_cm_commissioner/install/install_generator.rb
Labels: chore

#227 close #105 add sort search option type list page
  app/controllers/spree/admin/option_types_controller_decorator.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/overrides/spree/admin/option_types/index/option_header.html.erb.deface
  app/overrides/spree/admin/option_types/index/sort_search.html.erb.deface
Labels: enhancement, view

#234 close #233 account checker api
  app/controllers/spree/api/v2/storefront/account_checker_controller.rb
  app/interactors/spree_cm_commissioner/existing_account_checker.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  config/locales/en.yml
  config/routes.rb
  spec/interactors/spree_cm_commissioner/existing_account_checker_spec.rb
  spec/request/spree/api/v2/account_checker_spec.rb
Labels: feature, api

#236 Close #235 find by state
  app/controllers/spree/api/v2/storefront/account/orders_controller_decorator.rb
  app/finders/spree_cm_commissioner/orders/find_by_state.rb
  spec/finders/spree_cm_commissioner/orders/find_by_state_spec.rb
Labels: api, backend

#239 close #238 setup calendar ui + orders calendar sample
  Gemfile.lock
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/calendar.js
  app/assets/javascripts/spree_cm_commissioner/popover.js
  app/assets/stylesheets/spree_cm_commissioner/backend.css
  app/assets/stylesheets/spree_cm_commissioner/backend/calendar.scss
  app/assets/stylesheets/spree_cm_commissioner/backend/commissioner_admin.css.scss
  app/controllers/spree/admin/calendars/base_controller.rb
  app/controllers/spree/admin/calendars/orders_controller.rb
  app/helpers/spree/admin/base_helper_decorator.rb
  app/overrides/spree/admin/shared/_main_menu/sidebar_calendars.html.erb.deface
  app/views/shared/_calendar.html.erb
  app/views/shared/calendar/_order_popover.html.erb
  app/views/shared/calendar/_orders_sidebar.html.erb
  app/views/spree/admin/calendars/orders/index.html.erb
  app/views/spree/admin/shared/sub_menu/_calendar.html.erb
  app/views/spree/admin/vectors/icons/index.html.erb
  config/locales/en.yml
  config/routes.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/calendar_event.rb
  spree_cm_commissioner.gemspec
Labels: view

#243 close #242 decorate promotion view to support pricing model
  app/controllers/spree/admin/promotions_controller_decorator.rb
  app/helpers/spree_cm_commissioner/admin/promotion_rules_helper_decorator.rb
  app/models/spree_cm_commissioner/pricing_model.rb
  app/models/spree_cm_commissioner/pricing_model/actions/create_listing_price_adjustment.rb
  app/models/spree_cm_commissioner/promotion_decorator.rb
  app/overrides/spree/admin/promotions/_form/type.html.erb.deface
  app/overrides/spree/admin/promotions/index/page_tabs.html.erb.deface
  app/views/spree/admin/promotions/actions/_create_listing_price_adjustment.html.erb
  app/views/spree/admin/promotions/rules/_fixed_date.html.erb
  config/locales/en.yml
  lib/spree_cm_commissioner/engine.rb
Labels: view

#261 Close #260 generate sequence number of invoice
  app/interactors/spree_cm_commissioner/invoice_number_creator.rb
  app/models/spree_cm_commissioner/invoice.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  db/migrate/20230322091608_create_cm_invoices.rb
  spec/interactors/spree_cm_commissioner/invoice_number_creator_spec.rb
Labels: feature

#259 close #258 fix undefined promotion.rules
  app/models/spree_cm_commissioner/pricing_model.rb
  app/models/spree_cm_commissioner/promotion_decorator.rb
  lib/spree_cm_commissioner/engine.rb
  spec/models/spree/promotion_spec.rb
  spec/models/spree_cm_commissioner/pricing_model_spec.rb
Labels: bug

#255 Close #254 create sms
  Gemfile.lock
  app/errors/spree_cm_commissioner/connection_error.rb
  app/interactors/sms_adapter/plasgate.rb
  app/interactors/sms_adapter/twillio.rb
  app/interactors/spree_cm_commissioner/international_mobile_formatter.rb
  app/interactors/spree_cm_commissioner/sms.rb
  app/models/spree_cm_commissioner/sms_log.rb
  config/locales/en.yml
  db/migrate/20230322160952_create_spree_cm_commissioner_sms_logs.rb
  spec/factories/spree_cm_commissioner/sms_logs.rb
  spec/interactors/spree_cm_commissioner/sms_spec.rb
  spree_cm_commissioner.gemspec
Labels: api, backend

#270 close #269 only a variant of each product can be subscribed
  app/controllers/spree/admin/merchant/customers_controller.rb
  app/models/spree_cm_commissioner/customer.rb
  app/models/spree_cm_commissioner/subscription.rb
  app/views/spree/admin/merchant/customers/index.html.erb
  app/views/spree/admin/merchant/subscriptions/_form.html.erb
  app/views/spree/admin/merchant/subscriptions/edit.html.erb
  app/views/spree/admin/merchant/subscriptions/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
Labels: backend

#280 close #264 create pin code sender
  app/interactors/spree_cm_commissioner/pin_code_sender.rb
  app/jobs/spree_cm_commissioner/sms_job.rb
  app/jobs/spree_cm_commissioner/sms_pin_code_job.rb
  app/mailers/spree_cm_commissioner/pin_code_mailer.rb
  app/models/spree_cm_commissioner/pin_code.rb
  db/migrate/20230328235551_create_spree_cm_commissioner_pin_codes.rb
  spec/factories/spree_cm_commissioner/pin_codes.rb
  spec/interactors/spree_cm_commissioner/pin_code_sender_spec.rb
Labels: api, backend

#276 close #274 setup order view
  app/controllers/concerns/spree/admin/merchant/order_parents_concern.rb
  app/controllers/spree/admin/merchant/invoice_controller.rb
  app/controllers/spree/admin/merchant/orders_controller.rb
  app/controllers/spree/admin/merchant/payments_controller.rb
  app/models/spree_cm_commissioner/customer.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/admin/merchant/invoice/show.html.erb
  app/views/spree/admin/merchant/orders/edit.html.erb
  app/views/spree/admin/merchant/orders/index.html.erb
  app/views/spree/admin/merchant/payments/index.html.erb
  app/views/spree/admin/merchant/shared/_order_tabs.html.erb
  app/views/spree/admin/merchant/shared/_subscription_tabs.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: subscription, backend

#282 Close #281 test pin code spec
  app/mailers/spree_cm_commissioner/application_mailer.rb
  app/models/spree_cm_commissioner/pin_code.rb
  app/models/spree_cm_commissioner/pin_code_contact_update.rb
  app/models/spree_cm_commissioner/pin_code_email_confirm.rb
  app/models/spree_cm_commissioner/pin_code_forget_password.rb
  app/models/spree_cm_commissioner/pin_code_login.rb
  app/models/spree_cm_commissioner/pin_code_mobile_confirm.rb
  app/models/spree_cm_commissioner/pin_code_registration.rb
  app/models/spree_cm_commissioner/pin_code_update_user_login.rb
  spec/models/spree_cm_commissioner/pin_code_spec.rb
Labels: spec

#237 close #195 setup ACL
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/role_form.js
  app/controllers/spree/admin/merchant/roles_controller.rb
  app/models/spree_cm_commissioner/permission.rb
  app/models/spree_cm_commissioner/role_decorator.rb
  app/models/spree_cm_commissioner/role_permission.rb
  app/views/spree/admin/merchant/roles/_form.html.erb
  app/views/spree/admin/merchant/roles/edit.html.erb
  app/views/spree/admin/merchant/roles/index.html.erb
  app/views/spree/admin/merchant/roles/new.html.erb
  app/views/spree/admin/merchant/shared/_main_menu.html.erb
  app/views/spree/admin/merchant/shared/_role_tabs.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230317072219_create_spree_cm_commissioner_permissions.rb
  db/migrate/20230317073224_create_spree_cm_commissioner_role_permissions.rb
Labels: feature, view

#283 close #278 add merchant payment view
  app/controllers/concerns/spree/admin/merchant/payment_creatable.rb
  app/controllers/concerns/spree/admin/merchant/payment_fireable.rb
  app/controllers/spree/admin/merchant/payments_controller.rb
  app/controllers/spree/admin/merchant/refunds_controller.rb
  app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/views/spree/admin/merchant/payments/_list.html.erb
  app/views/spree/admin/merchant/payments/index.html.erb
  app/views/spree/admin/merchant/payments/new.html.erb
  config/locales/en.yml
  config/routes.rb
  lib/spree_cm_commissioner/test_helper/factories/customer_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/subscription_factory.rb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
Labels: subscription, payment

#294 Close #287-create-pin-code-creator
  .vscode/settings.json
  app/interactors/spree_cm_commissioner/pin_code_creator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/pin_code_serializer.rb
  config/locales/en.yml
  db/migrate/20230328235551_create_spree_cm_commissioner_pin_codes.rb
  spec/interactors/spree_cm_commissioner/pin_code_creator_spec.rb
  spec/interactors/spree_cm_commissioner/pin_code_sender_spec.rb
Labels: api, spec, backend
