Repository channainfo/commissioner, pull requests merged in 2023-12, with the labels that each got.

#873 close #872 fix image size to fit aspect radio
  app/models/spree_cm_commissioner/image_methods_decorator.rb
Labels: bug, M

#882 close #880 add exception dates to weekend promotion rule
  app/assets/javascripts/spree_cm_commissioner/annual_calendar_form.js
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/stylesheets/spree_cm_commissioner/backend/calendar.scss
  app/controllers/spree/admin/promotion_events_rules_controller.rb
  app/controllers/spree/admin/promotion_weekend_rules_controller.rb
  app/models/spree_cm_commissioner/promotion/rules/weekend.rb
  app/views/shared/_calendar.html.erb
  app/views/spree/admin/promotion_weekend_rules/_exception_dates.html.erb
  app/views/spree/admin/promotion_weekend_rules/_form.html.erb
  app/views/spree/admin/promotion_weekend_rules/_new_exception_date_form.html.erb
  app/views/spree/admin/promotion_weekend_rules/edit.html.erb
  app/views/spree/admin/promotions/rules/_weekend.html.erb
  config/routes.rb
  spec/models/spree_cm_commissioner/promotion/rules/weekend_spec.rb
Labels: enhancement, backend, L

#869 close #868 fix redirect and load data
  app/controllers/spree/admin/line_items_controller.rb
  app/views/spree/admin/line_items/_form.html.erb
Labels: bug

#878 close #874 update notification body to rich text
  app/views/spree/admin/customer_notifications/_form.html.erb
  app/views/spree/admin/customer_notifications/index.html.erb
Labels: enhancement, S

#879 close #875 update notification type field to enum integer
  app/models/spree_cm_commissioner/customer_notification.rb
  app/notifications/spree_cm_commissioner/customer_content_notification.rb
  app/notifications/spree_cm_commissioner/order_complete_notification.rb
  app/views/spree/admin/customer_notifications/_form.html.erb
  db/migrate/20231207022826_change_notification_type_to_integer_in_spree_cm_commissioner_customer_notifications.rb
  lib/spree_cm_commissioner/test_helper/factories/customer_notification_factory.rb
  spec/notifications/spree_cm_commissioner/customer_content_notifications_spec.rb
Labels: enhancement, S

#877 Close #856 Transit add location to be taxon
  app/controllers/spree/transit/base_controller.rb
  app/controllers/spree/transit/taxonomies_controller.rb
  app/controllers/spree/transit/taxons_controller.rb
  app/helpers/spree/transit/sortable_tree_helper.rb
  app/models/concerns/spree_cm_commissioner/taxonomy_kind.rb
  app/models/spree_cm_commissioner/taxonomy_decorator.rb
  app/views/spree/transit/service_calendars/_filters.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  app/views/spree/transit/shared/sortable_tree/_taxonomy.html.erb
  app/views/spree/transit/taxonomies/_filters.html.erb
  app/views/spree/transit/taxonomies/_form.html.erb
  app/views/spree/transit/taxonomies/_list.html.erb
  app/views/spree/transit/taxonomies/edit.html.erb
  app/views/spree/transit/taxonomies/index.html.erb
  app/views/spree/transit/taxonomies/new.html.erb
  app/views/spree/transit/taxons/_assets_form.html.erb
  app/views/spree/transit/taxons/_form.html.erb
  app/views/spree/transit/taxons/edit.html.erb
  app/views/spree/transit/taxons/index.html.erb
  app/views/spree/transit/taxons/new.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: feature

#890 Close #826 ui event logo broken in section event detail
  app/views/spree_cm_commissioner/order_mailer/_mailer_stylesheets.html.erb
  app/views/spree_cm_commissioner/order_mailer/event/_event_detail.html.erb
Labels: bug

#892 Close #891 add amount and display_amount to line item serializer
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: enhancement, XS

#893 Close #827 the email confirmation ui is broken in responsive mode
  app/views/spree_cm_commissioner/order_mailer/_mailer_stylesheets.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: bug

#889 close #888 read all notification api
  app/controllers/spree/api/v2/storefront/notifications_controller.rb
  app/interactors/spree_cm_commissioner/notification_reader.rb
  app/models/spree_cm_commissioner/notification.rb
  config/routes.rb
  spec/interactors/spree_cm_commissioner/notification_reader_spec.rb
Labels: api, M

#886 close #865 update user confirm_at to check unconfirmed user
  app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
  spec/interactors/spree_cm_commissioner/user_pin_code_authenticator_spec.rb
Labels: enhancement, L

#895 close #894 add cm_guest model for kyc
  app/models/spree_cm_commissioner/back_image.rb
  app/models/spree_cm_commissioner/front_image.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/id_card.rb
  db/migrate/20231214074523_create_spree_cm_commissioner_guests.rb
  db/migrate/20231214075200_create_spree_cm_commissioner_id_cards.rb
Labels: feature, M

#903 close #902 add default state to vendor serializer
  app/serializers/spree/v2/storefront/accommodation_serializer.rb
  app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/vendor_serializer_spec.rb
Labels: api, S

#905 close #904 add include kyc to spree product
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/overrides/spree/admin/products/_form/include_kyc_checkbox.html.erb.deface
  app/overrides/spree/admin/products/new/include_kyc_checkbox.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  db/migrate/20231215083209_add_kyc_to_spree_product.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: feature, M

#920 close #919 add home banner to taxon
  app/controllers/spree/admin/taxons_controller_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/taxon_home_banner.rb
  app/overrides/spree/admin/taxons/_form/assets_form.html.erb.deface
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  app/views/spree/admin/homepage_section/edit.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: backend, S

#915 close #914 add taxon to cm guest
  app/models/concerns/spree_cm_commissioner/taxon_kind.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/taxonomy_decorator.rb
  app/overrides/spree/admin/taxons/_form/kind_html.erb.deface
  db/migrate/20231219094449_add_taxon_reference_to_spree_cm_commissioner_guests.rb
  db/migrate/20231219094925_add_line_item_reference_to_spree_cm_commissioner_guests.rb
  db/migrate/20231219144136_remove_occupation_from_spree_cm_commissioner_guests.rb
Labels: backend, S

#901 Close #887 add vehicle table
  app/controllers/spree/transit/vehicle_photos_controller.rb
  app/controllers/spree/transit/vehicles_controller.rb
  app/models/spree_cm_commissioner/vehicle.rb
  app/models/spree_cm_commissioner/vehicle_photo.rb
  app/models/spree_cm_commissioner/vehicle_type.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/transit/shared/_main_menu.html.erb
  app/views/spree/transit/shared/_vehicle_tabs.html.erb
  app/views/spree/transit/vehicle_photos/_form.html.erb
  app/views/spree/transit/vehicle_photos/edit.html.erb
  app/views/spree/transit/vehicle_photos/index.html.erb
  app/views/spree/transit/vehicle_photos/new.html.erb
  app/views/spree/transit/vehicles/_filter_form.html.erb
  app/views/spree/transit/vehicles/_form.html.erb
  app/views/spree/transit/vehicles/edit.html.erb
  app/views/spree/transit/vehicles/index.html.erb
  app/views/spree/transit/vehicles/new.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20231211034859_create_cm_vehicles.rb
Labels: backend

#900 close #898 add guest api
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  config/routes.rb
Labels: feature, api, M

#918 Close #916 Add Search and Sort to Vehicle Type
  app/controllers/spree/transit/vehicle_types_controller.rb
  app/models/spree_cm_commissioner/vehicle_type.rb
  app/views/spree/transit/vehicle_types/_filter_form.html.erb
  app/views/spree/transit/vehicle_types/index.html.erb
  config/locales/en.yml
Labels: backend

#923 close #922 add kyc field to spree product
  app/controllers/spree/admin/kyc_controller.rb
  app/helpers/spree_cm_commissioner/admin/kycable_helper.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/overrides/spree/admin/shared/_product_tabs/kyc.html.erb.deface
  app/views/spree/admin/kyc/_form.html.erb
  app/views/spree/admin/kyc/edit.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20231221085859_remove_kyc_from_spree_products.rb
  db/migrate/20231221112718_add_kyc_to_spree_products.rb
  spec/interactors/spree_cm_commissioner/admin/kycable_helper_spec.rb
Labels: backend, M

#941 close #940 fix bug in stock location dashboard
  app/overrides/spree/admin/stock_locations/_form/stock_location_vendor.html.erb.deface
Labels: bug, S

#936 Close #932 Create a taxon_vendor and then connect the vendor and taxon
  app/models/spree_cm_commissioner/taxon_vendor.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  db/migrate/20231228105731_create_spree_cm_commissioner_taxon_vendors.rb
Labels: feature, L

#939 close #938 allow promo_total to be positive
  app/models/spree_cm_commissioner/order_decorator.rb
  spec/models/spree/order_spec.rb
Labels: S

#943 close #942 using spree_current_order instead of manually set order_number
  app/controllers/spree/api/v2/storefront/guest_line_items_controller.rb
Labels: enhancement, XS
