Repository channainfo/commissioner, pull requests merged in 2023-07, with the labels that each got.

#445 Close #444 notification api
  Gemfile.lock
  app/controllers/spree/admin/customer_notifications_controller.rb
  app/controllers/spree/api/v2/storefront/customer_notifications_controller.rb
  app/controllers/spree/api/v2/storefront/notifications_controller.rb
  app/controllers/spree/api/v2/storefront/user_device_token_registrations_controller.rb
  app/interactors/spree_cm_commissioner/user_device_token_deregister.rb
  app/notifications/noticed_fcm_base.rb
  app/notifications/spree_cm_commissioner/customer_content_notification.rb
  app/serializers/spree/v2/storefront/customer_notification_serializer.rb
  app/serializers/spree/v2/storefront/notification_serializer.rb
  config/routes.rb
  db/migrate/20230615082127_add_read_at_to_spree_cm_notifications.rb
  db/migrate/20230622043118_remove_type_from_spree_cm_commissioner_notifications.rb
  lib/spree_cm_commissioner/test_helper/factories/notification_factory.rb
  spec/interactors/spree_cm_commissioner/order_complete_notification_sender_spec.rb
Labels: api

#391 Close Notification
  Gemfile.lock
  README.md
  app/controllers/spree/admin/customer_notifications_controller.rb
  app/controllers/spree/api/v2/resource_controller_decorator.rb
  app/controllers/spree/api/v2/storefront/customer_notifications_controller.rb
  app/controllers/spree/api/v2/storefront/notifications_controller.rb
  app/controllers/spree/api/v2/storefront/user_device_token_registrations_controller.rb
  app/interactors/spree_cm_commissioner/customer_content_notification_creator.rb
  app/interactors/spree_cm_commissioner/customer_notification_cron_executor.rb
  app/interactors/spree_cm_commissioner/customer_notification_sender.rb
  app/interactors/spree_cm_commissioner/notification_reader.rb
  app/interactors/spree_cm_commissioner/user_device_token_deregister.rb
  app/interactors/spree_cm_commissioner/user_device_token_register.rb
  app/jobs/spree_cm_commissioner/customer_content_notification_creator_job.rb
  app/jobs/spree_cm_commissioner/customer_notification_cron.rb
  app/jobs/spree_cm_commissioner/customer_notification_sender_job.rb
  app/models/spree_cm_commissioner/customer_notification.rb
  app/models/spree_cm_commissioner/device_token.rb
  app/models/spree_cm_commissioner/feature_image.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/notifications/noticed_fcm_base.rb
  app/notifications/spree_cm_commissioner/customer_content_notification.rb
  app/notifications/spree_cm_commissioner/order_complete_notification.rb
  app/serializers/spree/v2/storefront/customer_notification_serializer.rb
  app/serializers/spree/v2/storefront/notification_serializer.rb
  app/serializers/spree/v2/storefront/user_device_token_serializer.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  app/views/spree/admin/customer_notifications/_form.html.erb
  app/views/spree/admin/customer_notifications/index.html.erb
  app/views/spree/admin/device_tokens/_form.html.erb
  app/views/spree/admin/device_tokens/index.html.erb
  app/views/spree/admin/shared/_send_test_form.html.erb
  config/routes.rb
  db/migrate/20230601030525_add_device_tokens_count_to_spree_users.rb
  db/migrate/20230614072904_add_device_type_to_spree_cm_device_token.rb
  db/migrate/20230615082127_add_read_at_to_spree_cm_notifications.rb
  db/migrate/20230622043118_remove_type_from_spree_cm_commissioner_notifications.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/test_helper/factories/customer_notification_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/device_token_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/notification_factory.rb
  spec/interactors/spree_cm_commissioner/customer_content_notification_creator_spec.rb
  spec/interactors/spree_cm_commissioner/customer_notification_sender_job_spec.rb
  spec/interactors/spree_cm_commissioner/customer_notification_sender_spec.rb
  spec/interactors/spree_cm_commissioner/notification_reader_spec.rb
  spec/interactors/spree_cm_commissioner/order_complete_notification_sender_spec.rb
  spec/interactors/spree_cm_commissioner/user_device_token_deregister_spec.rb
  spec/jobs/spree_cm_commissioner/customer_content_notification_creator_job_spec.rb
  spec/jobs/spree_cm_commissioner/customer_notification_cron_spec.rb
  spec/notifications/spree_cm_commissioner/customer_content_notifications_spec.rb
  spec/request/spree/api/v2/controller/user_device_token_registrations_spec.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
  spree_cm_commissioner.gemspec
Labels: feature

#456 close #454 fix order detail always return 404
  app/controllers/spree/api/v2/storefront/account/orders_controller_decorator.rb
Labels: bug

#459 Close #457 remove unused redirect url from homepage background
  app/views/spree/admin/homepage_background/_form.html.erb
  lib/spree_cm_commissioner/test_helper/factories/homepage_background_factory.rb
Labels: bug

#461 close #371 validate room quantity base on perminent stock & date
  app/models/spree_cm_commissioner/stock/availability_validator_decorator.rb
  app/queries/spree_cm_commissioner/variant_quantity_availability_query.rb
  config/locales/en.yml
  spec/models/spree/stock/availability_validator_spec.rb
  spec/queries/spree_cm_commissioner/variant_quantity_availability_query_spec.rb
Labels: enhancement, core

#469 Close #449 add home screen dynamic background image
  app/controllers/spree/admin/homepage_background_controller.rb
  app/controllers/spree/api/v2/storefront/homepage_data_controller.rb
  app/models/spree_cm_commissioner/homepage_background_app_image.rb
  app/models/spree_cm_commissioner/homepage_background_web_image.rb
  app/models/spree_cm_commissioner/subscription.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_background_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_data_serializer.rb
  app/services/spree_cm_commissioner/homepage_data_loader.rb
  app/views/spree/admin/homepage_background/index.html.erb
  spec/models/spree_cm_commissioner/homepage_background_spec.rb
  spec/services/spree_cm_commissioner/homepage_data_loader_spec.rb
Labels: bug

#468 close #467 enhance home data api
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_data_serializer.rb
  app/services/spree_cm_commissioner/homepage_data_loader.rb
  spec/models/spree/stock/availability_validator_spec.rb
  spec/queries/spree_cm_commissioner/variant_quantity_availability_query_spec.rb
  spec/serializers/spree_cm_commissioner/v2/storefront/homepage_data_serializer_spec.rb
  spec/services/spree_cm_commissioner/homepage_data_loader_spec.rb
Labels: bug, enhancement

#474 Close #472 pin code generator api
  app/controllers/spree/api/v2/storefront/pin_code_generators_controller.rb
  app/interactors/spree_cm_commissioner/pin_code_generator.rb
  config/routes.rb
  db/migrate/20230714063829_change_type_column_in_spree_cm_commissioner_pincodes.rb
  spec/request/spree/api/v2/controller/pin_code_generaters_controller_spec.rb
Labels: api

#476 close #475 fix vendor logo null raised error on UI
  app/overrides/spree/admin/vendors/_form/image_logo.html.erb.deface
  app/overrides/spree/admin/vendors/_form/logo.html.erb.deface
  app/overrides/spree/admin/vendors/index/index.html.erb.deface
  app/views/shared/_asset_field.html.erb
Labels: bug, enhancement, view, backend

#478 close #477 fix inconsistent checkin checkout date usage
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/promotion/actions/create_date_specific_item_adjustments.rb
  app/models/spree_cm_commissioner/stock/availability_validator_decorator.rb
  app/queries/spree_cm_commissioner/reservation_variant_quantity_availability_query.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_factory.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/stock/availability_validator_spec.rb
  spec/queries/spree_cm_commissioner/reservation_variant_quantity_availability_query_spec.rb
Labels: enhancement

#479 1.0.0-pre5
  app/controllers/spree/admin/homepage_background_controller.rb
  app/controllers/spree/api/v2/storefront/homepage_data_controller.rb
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/spree_cm_commissioner/homepage_background_app_image.rb
  app/models/spree_cm_commissioner/homepage_background_web_image.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/promotion/actions/create_date_specific_item_adjustments.rb
  app/models/spree_cm_commissioner/stock/availability_validator_decorator.rb
  app/models/spree_cm_commissioner/subscription.rb
  app/overrides/spree/admin/vendors/_form/image_logo.html.erb.deface
  app/overrides/spree/admin/vendors/_form/logo.html.erb.deface
  app/overrides/spree/admin/vendors/index/index.html.erb.deface
  app/queries/spree_cm_commissioner/reservation_variant_quantity_availability_query.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_background_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_data_serializer.rb
  app/services/spree_cm_commissioner/homepage_data_loader.rb
  app/views/shared/_asset_field.html.erb
  app/views/spree/admin/homepage_background/index.html.erb
  lib/spree_cm_commissioner/test_helper/factories/vendor_factory.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/stock/availability_validator_spec.rb
  spec/models/spree_cm_commissioner/homepage_background_spec.rb
  spec/queries/spree_cm_commissioner/reservation_variant_quantity_availability_query_spec.rb
  spec/serializers/spree_cm_commissioner/v2/storefront/homepage_data_serializer_spec.rb
  spec/services/spree_cm_commissioner/homepage_data_loader_spec.rb
Labels: release

#473 Close #464 User Registration with pin code
  Gemfile.lock
  app/controllers/spree/api/v2/storefront/pin_code_checkers_controller.rb
  app/controllers/spree/api/v2/storefront/pin_code_generators_controller.rb
  app/controllers/spree/api/v2/storefront/user_registration_with_pin_codes_controller.rb
  app/interactors/spree_cm_commissioner/oauth_token_generator.rb
  app/interactors/spree_cm_commissioner/pin_code_checker.rb
  app/interactors/spree_cm_commissioner/pin_code_generator.rb
  app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
  app/models/concerns/spree_cm_commissioner/user_notification.rb
  app/models/spree_cm_commissioner/pin_code.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230714063829_change_type_column_in_spree_cm_commissioner_pincodes.rb
  lib/spree_cm_commissioner/test_helper/factories/pin_code_factory.rb
  spec/interactors/spree_cm_commissioner/pin_code_checker_spec.rb
  spec/interactors/spree_cm_commissioner/user_pin_code_authenticator_spec.rb
  spec/request/spree/api/v2/controller/pin_code_checkers_controller_spec.rb
  spec/request/spree/api/v2/controller/pin_code_generaters_controller_spec.rb
  spec/request/spree/api/v2/controller/user_registration_with_pin_codes_controller_spec.rb
Labels: feature, api

#487 Close #486 enhance user sign up with pin code
  Gemfile.lock
  app/controllers/spree/api/v2/storefront/user_registration_with_pin_codes_controller.rb
  app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
  app/models/spree_cm_commissioner/subscription.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: api

#489 Close #488 change password api
  app/controllers/spree/api/v2/storefront/change_passwords_controller.rb
  app/interactors/spree_cm_commissioner/password_changer.rb
  config/routes.rb
  spec/interactors/spree_cm_commissioner/password_changer_spec.rb
  spec/request/spree/api/v2/controller/change_passwords_controller_spec.rb
Labels: api

#492 Close #491 fixing bug in stock location
  app/overrides/spree/admin/stock_locations/index/index.html.erb.deface
Labels: bug

#494 1.0.0-pre7
  Gemfile.lock
  app/controllers/spree/api/v2/storefront/change_passwords_controller.rb
  app/controllers/spree/api/v2/storefront/pin_code_checkers_controller.rb
  app/controllers/spree/api/v2/storefront/pin_code_generators_controller.rb
  app/controllers/spree/api/v2/storefront/user_registration_with_pin_codes_controller.rb
  app/interactors/spree_cm_commissioner/oauth_token_generator.rb
  app/interactors/spree_cm_commissioner/password_changer.rb
  app/interactors/spree_cm_commissioner/pin_code_checker.rb
  app/interactors/spree_cm_commissioner/pin_code_generator.rb
  app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
  app/models/concerns/spree_cm_commissioner/user_notification.rb
  app/models/spree_cm_commissioner/pin_code.rb
  app/models/spree_cm_commissioner/subscription.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/overrides/spree/admin/stock_locations/index/index.html.erb.deface
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20230714063829_change_type_column_in_spree_cm_commissioner_pincodes.rb
  lib/spree_cm_commissioner/test_helper/factories/pin_code_factory.rb
  spec/interactors/spree_cm_commissioner/password_changer_spec.rb
  spec/interactors/spree_cm_commissioner/pin_code_checker_spec.rb
  spec/interactors/spree_cm_commissioner/user_pin_code_authenticator_spec.rb
  spec/request/spree/api/v2/controller/change_passwords_controller_spec.rb
  spec/request/spree/api/v2/controller/pin_code_checkers_controller_spec.rb
  spec/request/spree/api/v2/controller/pin_code_generaters_controller_spec.rb
  spec/request/spree/api/v2/controller/user_registration_with_pin_codes_controller_spec.rb
Labels: release
