Repository channainfo/commissioner, pull requests merged in 2023-06, with the labels that each got.

#394 close #384 simple variant creation
  app/controllers/spree/billing/base_controller.rb
  app/controllers/spree/billing/products_controller.rb
  app/controllers/spree/billing/variants_controller.rb
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/billing/customers/index.html.erb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/products/_add_stock_form.html.erb
  app/views/spree/billing/products/_form.html.erb
  app/views/spree/billing/products/index.html.erb
  app/views/spree/billing/products/new.html.erb
  app/views/spree/billing/products/stock.html.erb
  app/views/spree/billing/variants/_form.html.erb
  app/views/spree/billing/variants/edit.html.erb
  app/views/spree/billing/variants/index.html.erb
  app/views/spree/billing/variants/new.html.erb
  config/locales/en.yml
Labels: backend

#398 Close #388 filter data for report
  app/controllers/spree/billing/report_controller.rb
  app/views/spree/billing/report/_date_range_picker.html.erb
Labels: feature, view

#400 Close #399 notification cron job
  app/interactors/spree_cm_commissioner/customer_notification_cron_executor.rb
  app/jobs/spree_cm_commissioner/customer_notification_sender_job.rb
  app/models/spree_cm_commissioner/customer_notification.rb
  spec/interactors/spree_cm_commissioner/customer_notification_sender_job_spec.rb
Labels: core

#402 Close #401 report page overdue orders bug
  app/controllers/spree/billing/report_controller.rb
Labels: invalid

#410 close #409 fix inconsistent asset serializer
  app/models/spree_cm_commissioner/asset.rb
  app/serializers/spree/v2/storefront/feature_image_serializer.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  app/serializers/spree/v2/storefront/user_profile_serializer.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  app/serializers/spree/v2/storefront/vendor_logo_serializer.rb
  app/serializers/spree/v2/storefront/vendor_photo_serializer.rb
  app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/asset_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/base_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/brand_taxon_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/category_icon_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/category_taxon_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_banner_app_image_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_banner_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_banner_web_image_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_data_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/taxon_brand_logo_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/taxon_category_icon_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/taxon_include_product_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/taxon_web_banner_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/vendor_app_promotion_banner_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/vendor_include_product_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/vendor_promotion_banner_serializer.rb
  lib/spree_cm_commissioner/test_helper/factories/asset_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  spec/serializers/spree/v2/storefront/accommodation_serializer_spec.rb
  spec/serializers/spree/v2/storefront/cart_serializer_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/nearby_place_serializer_spec.rb
  spec/serializers/spree/v2/storefront/option_type_serializer_spec.rb
  spec/serializers/spree/v2/storefront/option_value_serializer_spec.rb
  spec/serializers/spree/v2/storefront/place_serializer_spec.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/stock_location_serializer_spec.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
  spec/serializers/spree/v2/storefront/vendor_photo_serializer_spec.rb
  spec/serializers/spree/v2/storefront/vendor_serializer_spec.rb
  spec/serializers/spree_cm_commissioner/v2/storefront/asset_serializer_spec.rb
  spec/serializers/spree_cm_commissioner/v2/storefront/homepage_data_serializer_spec.rb
  spec/serializers/spree_cm_commissioner/v2/storefront/promotion_action_serializer_spec.rb
  spec/serializers/spree_cm_commissioner/v2/storefront/promotion_serializer_spec.rb
  spree_cm_commissioner.gemspec
Labels: chore, spec

#413 close #412 move factories to lib test helper instead
  lib/spree_cm_commissioner/test_helper/factories/homepage_banner_app_image_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/homepage_banner_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/homepage_banner_web_image_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/permission.rb
  lib/spree_cm_commissioner/test_helper/factories/pin_code_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/place_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/service_calendar_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/sms_logs.rb
  lib/spree_cm_commissioner/test_helper/factories/stock_location_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/taxon_brand_logo_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/taxon_category_icon.rb
  lib/spree_cm_commissioner/test_helper/factories/taxon_web_banner_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_logo_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_photo_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_place_factory.rb
Labels: chore

#404 Close #403 send notification to specific user
  app/controllers/spree/admin/customer_notifications_controller.rb
  app/interactors/spree_cm_commissioner/customer_notification_sender.rb
  app/interactors/spree_cm_commissioner/user_device_token_register.rb
  app/notifications/spree_cm_commissioner/customer_content_notification.rb
  app/notifications/spree_cm_commissioner/order_complete_notification.rb
  app/views/spree/admin/customer_notifications/index.html.erb
  app/views/spree/admin/device_tokens/index.html.erb
  app/views/spree/admin/shared/_send_test_form.html.erb
  spec/interactors/spree_cm_commissioner/customer_notification_sender_spec.rb
Labels: feature, backend

#411 Close #407 add start date and end date to line item
  app/overrides/spree/admin/orders/_line_items/_line_items.html.erb.deface
Labels: enhancement, backend

#417 close #416 revert back spree_cm_commissioner.gemspec
  spree_cm_commissioner.gemspec
Labels: chore

#420 Close #408 Filter Data for Report by Cashier
  app/controllers/spree/billing/report_controller.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/payment_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/payments/_list.html.erb
  app/views/spree/billing/report/_date_range_picker.html.erb
  app/views/spree/billing/users/edit.html.erb
  config/locales/en.yml
Labels: feature, view

#406 close #405 add penalty to payment
  app/controllers/spree/billing/adjustments_controller.rb
  app/controllers/spree/billing/payments_controller.rb
  app/controllers/spree/billing/products_controller.rb
  app/overrides/spree/admin/shared/_order_summary/penalty.html.erb.deface
  app/services/spree_cm_commissioner/penalty_calculator.rb
  app/views/spree/billing/adjustments/_adjustment.html.erb
  app/views/spree/billing/adjustments/_adjustments_table.html.erb
  app/views/spree/billing/adjustments/_form.html.erb
  app/views/spree/billing/adjustments/index.html.erb
  app/views/spree/billing/adjustments/new.html.erb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/payments/index.html.erb
  app/views/spree/billing/shared/_invoice.html.erb
  app/views/spree/billing/shared/_order_tabs.html.erb
  config/locales/en.yml
  config/locales/km.yml
  spec/services/spree_cm_commissioner/penalty_calculator_spec.rb
Labels: view, backend, billing

#415 Close #414 add fcm credentails
  README.md
  app/controllers/spree/api/v2/resource_controller_decorator.rb
  app/controllers/spree/api/v2/storefront/user_device_token_registrations_controller.rb
  app/jobs/spree_cm_commissioner/customer_notification_cron.rb
  app/models/spree_cm_commissioner/customer_notification.rb
  app/notifications/noticed_fcm_base.rb
  app/views/spree/admin/device_tokens/index.html.erb
  lib/spree_cm_commissioner.rb
  spec/jobs/spree_cm_commissioner/customer_notification_cron_spec.rb
  spec/notifications/spree_cm_commissioner/customer_content_notifications_spec.rb
  spec/request/spree/api/v2/controller/user_device_token_registrations_spec.rb
  spree_cm_commissioner.gemspec
Labels: core

#427 Close #426 add the start promotion date to the main promotion screen
  app/overrides/spree/admin/promotions/index/index.html.erb.deface
Labels: enhancement, backend

#432 1.0.0-2.0.pre
  app/controllers/spree/billing/adjustments_controller.rb
  app/controllers/spree/billing/payments_controller.rb
  app/controllers/spree/billing/products_controller.rb
  app/overrides/spree/admin/promotions/index/index.html.erb.deface
  app/overrides/spree/admin/shared/_order_summary/penalty.html.erb.deface
  app/services/spree_cm_commissioner/penalty_calculator.rb
  app/views/spree/billing/adjustments/_adjustment.html.erb
  app/views/spree/billing/adjustments/_adjustments_table.html.erb
  app/views/spree/billing/adjustments/_form.html.erb
  app/views/spree/billing/adjustments/index.html.erb
  app/views/spree/billing/adjustments/new.html.erb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/payments/index.html.erb
  app/views/spree/billing/shared/_invoice.html.erb
  app/views/spree/billing/shared/_order_tabs.html.erb
  config/locales/en.yml
  config/locales/km.yml
  spec/services/spree_cm_commissioner/penalty_calculator_spec.rb
Labels: release

#431 close #430 enhanced post-paid and pre-paid
  app/models/spree_cm_commissioner/line_item_decorator.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/subscription_factory.rb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
Labels: feature, backend, billing

#434 Close #397 Billman Login Issues
  app/controllers/concerns/spree_cm_commissioner/billing/role_authorization.rb
Labels: bug, enhancement

#437 Close #435 Report Tab Bug
  app/views/spree/billing/shared/sub_menu/_report.html.erb
Labels: bug, view

#438 Close #433-enhancement of the image in vendor screen upload from locally
  app/overrides/spree/admin/vendors/index/index.html.erb.deface
Labels: enhancement

#440 Close #439 Payment State Translation
  app/views/spree/billing/report/_overview.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: feature

#442 Close #441 configure the image url and fix the vendor logo in vendor
  app/overrides/spree/admin/users/_form/profile_pic.html.erb.deface
  app/overrides/spree/admin/vendors/_form/logo.html.erb.deface
  app/overrides/spree/admin/vendors/index/index.html.erb.deface
Labels: bug
