Repository channainfo/commissioner, pull requests merged in 2023-10, with the labels that each got.

#638 close #637 required twillo-ruby
  app/interactors/sms_adapter/twillio.rb
  lib/spree_cm_commissioner.rb
Labels: chore

#640 Close #639 make notice-info section in confirmation mailer dynamic
  app/assets/stylesheets/spree_cm_commissioner/mailer/order/style.scss
  app/helpers/spree/mail_helper_decorator.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/views/spree_cm_commissioner/order_mailer/_footer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_info_notice.html.erb
  app/views/spree_cm_commissioner/order_mailer/_support_contact.html.erb
  app/views/spree_cm_commissioner/order_mailer/_your_booking.html.erb
  app/views/spree_cm_commissioner/order_mailer/event/_event_detail.html.erb
  app/views/spree_cm_commissioner/order_mailer/hotel/_booking_detail.html.erb
Labels: chore

#646 close #645 fix active record read only mode on api controller
  app/models/spree_cm_commissioner/oauth_access_token_decorator.rb
Labels: bug

#649 close #648 fix :platform not defined when cleanup_device_token
  app/mailers/spree/order_mailer_decorator.rb
  app/notifications/noticed_fcm_base.rb
  spec/notifications/spree_cm_commissioner/customer_content_notifications_spec.rb
Labels: bug

#658 close #657 add event date to taxon
  Gemfile.lock
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/overrides/spree/admin/taxons/_form/to_date_form_date.html.erb.deface
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20230929092732_add_from_date_to_spree_taxon.rb
  db/migrate/20230929092843_add_to_date_to_spree_taxon.rb
  spec/models/spree/line_item_spec.rb
Labels: backend

#663 close #652 allow to filter product by vendor
  app/models/spree_cm_commissioner/product_decorator.rb
  app/overrides/spree/admin/products/_filters/vendor_filter.html.erb.deface
Labels: enhancement, backend

#662 close #661 add column kind to spree taxon and spree taxonomy
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/taxonomy_decorator.rb
  app/overrides/spree/admin/taxonomies/_form/kind.html.erb.deface
  app/overrides/spree/admin/taxons/_form/kind_html.erb.deface
  app/views/shared/_kind_field.html.erb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20231005021029_add_kind_to_spree_taxon.rb
  db/migrate/20231005021329_add_kind_to_spree_taxonomy.rb
  spec/models/spree/line_item_spec.rb
Labels: backend

#665 close #664 filter only complete line items for event
  app/controllers/spree/api/v2/storefront/line_items_controller.rb
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  spec/models/spree/line_item_spec.rb
Labels: api

#667 close #666 add generate qr api
  app/controllers/spree/api/v2/storefront/order_qrs_controller.rb
  app/helpers/spree/mail_helper_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  config/routes.rb
Labels: api

#673 close #672 enhance markas read api
  app/controllers/spree/api/v2/storefront/customer_notifications_controller.rb
  app/controllers/spree/api/v2/storefront/notifications_controller.rb
  app/controllers/spree/api/v2/storefront/order_request_notifications_controller.rb
  app/interactors/spree_cm_commissioner/notification_reader.rb
  app/models/spree_cm_commissioner/notification.rb
  config/routes.rb
  spec/interactors/spree_cm_commissioner/notification_reader_spec.rb
Labels: bug, enhancement

#676 close #675 integrate google recaptcha enterprise
  Gemfile.lock
  README.md
  app/controllers/spree/api/v2/storefront/pin_code_generators_controller.rb
  app/interactors/spree_cm_commissioner/recaptcha_token_validator.rb
  config/initializers/recaptcha_enterprise.rb
  config/locales/en.yml
  config/locales/km.yml
  lib/spree_cm_commissioner.rb
  spec/interactors/spree_cm_commissioner/recaptcha_token_validator_spec.rb
  spec/request/spree/api/v2/controller/pin_code_generaters_controller_spec.rb
  spree_cm_commissioner.gemspec
Labels: enhancement

#678 close #677 consider line item a reservation if it's either accommodation or service
  app/models/spree_cm_commissioner/line_item_decorator.rb
  spec/models/spree/line_item_spec.rb
Labels: enhancement

#680 close #679 standalone service account for recaptcha
  app/interactors/spree_cm_commissioner/recaptcha_token_validator.rb
  config/initializers/recaptcha_enterprise.rb
Labels: chore

#683 close #682 undefine handle when telegram bot error
  app/exception_notifier/spree_cm_commissioner/telegram_notifier.rb
Labels: hotfix

#684 close #681 fix undefined local variable or method 'base' for product
  app/models/spree_cm_commissioner/product_decorator.rb
Labels: hotfix

#686 close #687 fix missing args in telegram notifier
  app/exception_notifier/spree_cm_commissioner/telegram_notifier.rb
Labels: bug

#693 close #692 clear cache when update home feed
  app/controllers/spree/admin/homepage_feed_controller.rb
  app/models/spree_cm_commissioner/configuration.rb
  app/views/spree/admin/homepage_feed/edit.html.erb
Labels: enhancement, feature

#690 Close #671 no style for order mailer
  app/assets/config/spree_cm_commissioner_manifest.js
  app/assets/images/cm-striaght-line-icon.svg
  app/assets/images/mailer/bed.png
  app/assets/images/mailer/bookme-plus.png
  app/assets/images/mailer/calendar.png
  app/assets/images/mailer/envelope.png
  app/assets/images/mailer/event-mailer-bg.png
  app/assets/images/mailer/facebook.png
  app/assets/images/mailer/instagram.png
  app/assets/images/mailer/map-marker.png
  app/assets/images/mailer/phone.png
  app/assets/images/mailer/twitter.png
  app/assets/images/mailer/user.png
  app/assets/stylesheets/spree_cm_commissioner/mailer/base.css.scss
  app/assets/stylesheets/spree_cm_commissioner/mailer/order/style.scss
  app/helpers/spree/mail_helper_decorator.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/views/spree_cm_commissioner/layouts/order_mailer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_customer_info.html.erb
  app/views/spree_cm_commissioner/order_mailer/_footer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  app/views/spree_cm_commissioner/order_mailer/_mailer_stylesheets.html.erb
  app/views/spree_cm_commissioner/order_mailer/_support_contact.html.erb
  app/views/spree_cm_commissioner/order_mailer/event/_event_detail.html.erb
  app/views/spree_cm_commissioner/order_mailer/hotel/_booking_detail.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_summary.html.erb
Labels: bug

#695 close #694 update app name in mailer
  app/mailers/spree_cm_commissioner/pin_code_mailer.rb
  app/views/spree_cm_commissioner/pin_code_mailer/send_pin_code.html.erb
Labels: bug, hotfix

#697 close #696 enhance room need confirmation flow - validation, transitions
  app/interactors/spree_cm_commissioner/order_accepted_state_updater.rb
  app/interactors/spree_cm_commissioner/order_rejected_state_updater.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/stock/availability_validator_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  db/migrate/20231010161219_rename_spree_line_item_accepted_by_rejected_by_column_to_accepter_rejecter_id.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_factory.rb
  spec/interactors/spree_cm_commissioner/order_accepted_state_updater_spec.rb
  spec/interactors/spree_cm_commissioner/order_rejected_state_updater_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/stock/availability_validator_spec.rb
Labels: enhancement

#698 Close #699 render qr in mailer and using inline style
  app/controllers/spree_cm_commissioner/qr_images_controller.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/views/spree/order_mailer/confirm_email.html.erb
  app/views/spree_cm_commissioner/layouts/order_mailer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  app/views/spree_cm_commissioner/order_mailer/_mailer_stylesheets.html.erb
  app/views/spree_cm_commissioner/order_mailer/hotel/_booking_detail.html.erb
  config/initializers/premailer_rails.rb
  config/routes.rb
  lib/spree_cm_commissioner.rb
  spree_cm_commissioner.gemspec
Labels: enhancement

#703 close #702 ensure cart before adding line item
  app/controllers/spree_cm_commissioner/api/v2/storefront/cart_controller_decorator.rb
Labels: enhancement

#705 close #704 add request booking admin ui flow
  Gemfile.lock
  app/assets/images/backend-accept_all.svg
  app/assets/images/backend-alert_request_to_vendor.svg
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/overrides/spree/admin/orders/_line_items/_header.html.erb.deface
  app/overrides/spree/admin/orders/_line_items/_line_items.html.erb.deface
  app/overrides/spree/admin/shared/_order_summary/request_state.html.erb.deface
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  spec/models/spree/order_spec.rb
Labels: enhancement

#701 close #700 get s3 object with url
  app/controllers/spree/api/v2/storefront/profile_images_controller.rb
  app/interactors/spree_cm_commissioner/profile_image_updater.rb
  app/models/spree_cm_commissioner/s3_signed_url.rb
  app/serializers/spree/v2/storefront/user_profile_serializer.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/profile_image_serializer.rb
  spec/interactors/spree_cm_commissioner/profile_image_updater_spec.rb
Labels: enhancement

#708 close #707 allow payment transition to void from failed
  app/models/spree_cm_commissioner/payment_decorator.rb
  app/services/spree_cm_commissioner/cart/destroy_decorator.rb
  spec/services/spree/cart/destroy_spec.rb
Labels: enhancement

#706 close #670 added name field to vendor_place
  app/controllers/spree/admin/nearby_places_controller.rb
  app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb
  app/views/spree/admin/nearby_places/new.html.erb
  spec/cassettes/SpreeCmCommissioner_VendorNearbyPlaceBuilder/_call/should_get_20_nearby_places_for_vendor.yml
Labels: enhancement, backend

#710 Close #709 search query should return only vendor with product type accomodation
  Gemfile.lock
  app/queries/spree_cm_commissioner/accommodation_query.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_factory.rb
  spec/interactors/spree_cm_commissioner/accommodation_search_detail_spec.rb
  spec/queries/spree_cm_commissioner/accommodation_query_spec.rb
  spec/request/spree/api/v2/accommodations_spec.rb
Labels: bug

#712 close #711 required user for cart & checkout api
  app/controllers/spree_cm_commissioner/api/v2/storefront/cart_controller_decorator.rb
  app/controllers/spree_cm_commissioner/api/v2/storefront/checkout_controller_decorator.rb
Labels: enhancement

#717 close #716 alert order complete telegram store vendor
  app/factory/spree_cm_commissioner/order_telegram_message_factory.rb
  app/factory/spree_cm_commissioner/telegram_message_factory.rb
  app/interactors/spree_cm_commissioner/telegram_notification_sender.rb
  app/jobs/spree_cm_commissioner/telegram_notification_sender_job.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/concerns/spree_cm_commissioner/store_preference.rb
  app/models/spree_cm_commissioner/store_decorator.rb
  app/overrides/spree/admin/stores/_form/store_preferences.html.erb.deface
  db/migrate/20231009163252_add_preferences_to_spree_store.rb
  spec/factory/spree_cm_commissioner/order_telegram_message_factory_spec.rb
  spec/jobs/spree_cm_commissioner/telegram_notification_sender_job_spec.rb
Labels: feature

#722 close #721 add order notification to mock send notification
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/overrides/spree/admin/shared/_order_tabs/notifications.html.erb.deface
  app/views/spree/admin/orders/notifications.html.erb
  config/initializers/spree_permitted_attributes.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: feature

#720 Close #715 use from_date instead for event type in mailer template
  app/views/spree/order_mailer/confirm_email.html.erb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  app/views/spree_cm_commissioner/order_mailer/event/_event_detail.html.erb
Labels: enhancement

#719 Close #718 improve public qr generator
  app/controllers/spree_cm_commissioner/qr_images_controller.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  spec/models/spree/order_spec.rb
Labels: enhancement

#724 close #723 improve telegram order complete push message
  app/factory/spree_cm_commissioner/order_telegram_message_factory.rb
  app/factory/spree_cm_commissioner/telegram_message_factory.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  spec/factory/spree_cm_commissioner/order_telegram_message_factory_spec.rb
Labels: enhancement

#732 close #731 after transition to complete not trigger when order complete
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  spec/models/spree/order_spec.rb
Labels: bug

#735 Close #734 not return unpublished vendor when doing search
  app/queries/spree_cm_commissioner/accommodation_query.rb
  spec/queries/spree_cm_commissioner/accommodation_query_spec.rb
Labels: bug

#737 close #736 add full backtrace to telegram exception notifier
  app/exception_notifier/spree_cm_commissioner/telegram_notifier.rb
  config/initializers/exception_notification.rb
Labels: enhancement

#727 close #726 show only accepted completed line-item in upcoming
  app/controllers/spree/api/v2/storefront/line_items_controller.rb
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
Labels: bug

#745 close #744 fix line item controller not return order that doesn't need confirmation
  app/controllers/spree/api/v2/storefront/line_items_controller.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  spec/models/spree/order_spec.rb
Labels: bug, hotfix

#750 close #749 alert request telegram to store
  app/assets/images/backend-reject_all.svg
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/concerns/spree_cm_commissioner/store_preference.rb
  app/overrides/spree/admin/orders/_line_items/_header.html.erb.deface
  config/initializers/spree_permitted_attributes.rb
  config/locales/en.yml
  config/routes.rb
Labels: feature

#743 Close #742 add sort for min_price and max_price to accommodations
  app/controllers/spree/api/v2/storefront/accommodations_controller.rb
Labels: enhancement

#748 Close #746 Add a field phone number to the admin/user and edit screens
  app/overrides/spree/admin/users/_form/fields.html.erb.deface
  app/overrides/spree/admin/users/index/body.html.erb.deface
  app/overrides/spree/admin/users/index/headers.html.erb.deface
  app/overrides/spree/admin/users/index/ransack.html.erb.deface
Labels: enhancement

#752 close #751 undefine method paid for line items
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  spec/models/spree/line_item_spec.rb
Labels: bug, hotfix

#754 Close #753 make phone number values to store in the input field and get their value to display on the user screen
  app/overrides/spree/admin/users/_form/fields.html.erb.deface
  app/overrides/spree/admin/users/index/body.html.erb.deface
  app/overrides/spree/admin/users/index/headers.html.erb.deface
  app/overrides/spree/admin/users/index/ransack.html.erb.deface
  config/initializers/spree_permitted_attributes.rb
Labels: enhancement

#756 close #755 implement show action in order line item
  app/controllers/spree/api/v2/storefront/line_items_controller.rb
  app/serializers/spree/v2/storefront/line_item_order_serializer.rb
  config/routes.rb
Labels: api

#758 Close #757 view ticket details from the backend
  app/controllers/spree_cm_commissioner/orders_controller.rb
  app/overrides/spree/admin/orders/_order_actions/actions.html.erb.deface
  app/views/spree/order_mailer/confirm_email.html.erb
  app/views/spree_cm_commissioner/order_mailer/_info_notice.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: enhancement, backend

#768 close #765 auto set name to user on social connect
  app/interactors/spree_cm_commissioner/account_linkage.rb
  app/interactors/spree_cm_commissioner/firebase_id_token_provider.rb
  app/interactors/spree_cm_commissioner/user_registration_with_id_token.rb
  app/serializers/spree_cm_commissioner/v2/storefront/user_identity_provider_serializer.rb
  db/migrate/20231030183224_add_name_to_user_identity_provider.rb
  spec/interactors/spree_cm_commissioner/account_linkage_spec.rb
  spec/interactors/spree_cm_commissioner/firebase_id_token_provider_spec.rb
  spec/interactors/spree_cm_commissioner/user_registration_with_id_token_spec.rb
Labels: enhancement

#761 close #760 show request booking order when payment_state is not paid
  app/controllers/spree/api/v2/storefront/order_request_notifications_controller.rb
  app/models/spree_cm_commissioner/notification.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  spec/models/spree_cm_commissioner/notification_spec.rb
Labels: bug, enhancement
