Repository channainfo/commissioner, pull requests merged in 2023-02, with the labels that each got.

#169 Close #167 add username attributes
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
Labels: api

#170 Close #155 nearby facilities
  app/controllers/spree/admin/nearby_places_controller.rb
  app/controllers/spree/api/v2/storefront/nearby_places_controller.rb
  app/interactors/spree_cm_commissioner/nearby_place_creator.rb
  app/models/spree/vendor_decorator.rb
  app/models/spree_cm_commissioner/place.rb
  app/models/spree_cm_commissioner/vendor_place.rb
  app/serializers/spree/v2/storefront/nearby_place_serializer.rb
  app/serializers/spree/v2/storefront/place_serializer.rb
  app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
  app/views/spree/admin/nearby_places/_form.html.erb
  app/views/spree/admin/nearby_places/index.html.erb
  app/views/spree/admin/nearby_places/new.html.erb
  app/views/spree/admin/shared/_vendor_tabs.html.erb
  config/routes.rb
  db/migrate/20230208032303_create_cm_places.rb
  db/migrate/20230208032317_create_cm_vendor_places.rb
  spec/factories/spree_cm_commissioner/place_factory.rb
  spec/factories/spree_cm_commissioner/vendor_place_factory.rb
  spec/interactors/spree_cm_commissioner/nearby_place_creator_spec.rb
  spec/models/spree/vendor_spec.rb
  spec/models/spree_cm_commissioner/place_spec.rb
  spec/models/spree_cm_commissioner/vendor_place_spec.rb
  spec/request/spree/api/v2/nearby_places_spec.rb
  spec/serializers/spree/v2/storefront/nearby_place_serializer_spec.rb
  spec/serializers/spree/v2/storefront/place_serializer_spec.rb
  spec/serializers/spree/v2/storefront/vendor_serializer_spec.rb
  spec/spec_helper.rb
Labels: feature

#164 close #152 add promoted option values to vendor
  app/models/spree/vendor_decorator.rb
  app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
  lib/spree_cm_commissioner/test_helper/factories/option_value_vendor_factory.rb
  spec/models/spree/vendor_spec.rb
  spec/serializers/spree/v2/storefront/vendor_serializer_spec.rb
Labels: api

#175 close #172 migrate commissioner to fit spree 4.5 ui
  app/overrides/spree/admin/shared/_main_menu/sidebar_organizations.html.erb.deface
  app/overrides/spree/admin/shared/_product_tabs/master_variant.html.erb.deface
  app/overrides/spree/admin/vendors/edit/vendor_tabs.html.erb.deface
  app/views/spree/admin/nearby_places/index.html.erb
  app/views/spree/admin/nearby_places/new.html.erb
  app/views/spree/admin/shared/_vendor_tabs.html.erb
  app/views/spree/admin/vectors/icons/index.html.erb
  app/views/spree/admin/vendor_kind_option_types/index.html.erb
  app/views/spree/admin/vendor_photos/edit.html.erb
  app/views/spree/admin/vendor_photos/index.html.erb
  app/views/spree/admin/vendor_photos/new.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: enhancement, view

#176 close #177 move model decorator to commissioner module
  app/models/spree/property_decorator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/models/spree_cm_commissioner/option_value_decorator.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/property_decorator.rb
  app/models/spree_cm_commissioner/prototype_decorator.rb
  app/models/spree_cm_commissioner/state_decorator.rb
  app/models/spree_cm_commissioner/stock_location_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
Labels: enhancement

#179 close #178 require delivery only on product type ecommerce digital
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  spec/models/spree/order_spec.rb
Labels: core

#181 Close #180 add build status badge to README
  README.md
Labels: enhancement, badge

#188 close #187 add taxon icon
  app/controllers/spree/admin/taxons_controller_decorator.rb
  app/models/spree_cm_commissioner/asset.rb
  app/models/spree_cm_commissioner/taxon_category_icon.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/overrides/spree/admin/taxons/_form/category_icon_field.html.erb.deface
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/asset_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/base_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/category_icon_serializer.rb
  app/views/shared/_asset_field.html.erb
  config/initializers/spree_permitted_attributes.rb
  config/locales/en.yml
  config/routes.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_photo_factory.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: api, view, backend

#198 close #197 setup merchant route and layout
  app/controllers/spree/admin/merchants/base_controller.rb
  app/controllers/spree/admin/merchants/users_controller.rb
  app/views/spree/admin/merchants/shared/_main_menu.html.erb
  app/views/spree/admin/merchants/users/index.html.erb
  app/views/spree/layouts/merchant.html.erb
  config/routes.rb
Labels: core, view, backend

#201 close #200 add merchant's users view
  app/controllers/spree/admin/merchants/base_controller.rb
  app/controllers/spree/admin/merchants/users_controller.rb
  app/views/spree/admin/merchants/shared/_header.html.erb
  app/views/spree/admin/merchants/shared/_main_menu.html.erb
  app/views/spree/admin/merchants/shared/_vendor_switcher.html.erb
  app/views/spree/admin/merchants/users/index.html.erb
  app/views/spree/layouts/merchant.html.erb
  config/routes.rb
Labels: core, view, backend

#194 Close #193 add vcr gem
  Gemfile
  Gemfile.lock
  spec/cassettes/SpreeCmCommissioner_FirebaseIdTokenProvider/_cert_generation/return_fails_when_kid_not_match.yml
  spec/cassettes/Test_VCR_/Get_responses_from_an_api.yml
  spec/interactors/spree_cm_commissioner/firebase_id_token_provider_spec.rb
  spec/request/spree/api/vcr_spec.rb
  spec/support/vcr.rb
Labels: enhancement
