Repository channainfo/commissioner, pull requests merged in 2023-11, with the labels that each got.

#772 close #764 fixed nearby-place error
  app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb
Labels: bug, backend

#774 close #773 add a checkbox to reveal description
  .bundle/config
  app/overrides/spree/admin/products/_form/reveal_description_to_user.html.erb.deface
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  db/migrate/20231030024437_add_reveal_description_to_spree_products.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
Labels: enhancement, api

#779 close #788 manual send webhook in order view
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/views/spree/admin/orders/notifications.html.erb
  config/routes.rb
Labels: feature, backend

#781 close #780 add webhook events view
  app/controllers/spree/admin/webhooks_events_controller.rb
  app/views/spree/admin/webhooks_events/index.html.erb
  config/routes.rb
Labels: feature

#776 close # 775 remove password section when confirm to delete account
  app/controllers/spree/api/v2/storefront/account_deletions_controller.rb
  app/interactors/spree_cm_commissioner/account_deletion.rb
  spec/interactors/spree_cm_commissioner/account_deletion_spec.rb
  spec/request/spree/api/v2/controller/account_deletions_controller_spec.rb
Labels: enhancement

#783 close #782 disable rules fields on new action webhook subscriber view
  app/overrides/spree/admin/webhooks_subscribers/_form/rules.html.erb.deface
Labels: bug

#786 close #785 add show webhook order api
  app/controllers/spree/api/webhook/base_controller.rb
  app/controllers/spree/api/webhook/orders_controller.rb
  app/models/spree_cm_commissioner/webhooks/subscriber_decorator.rb
  config/routes.rb
  spec/models/spree/webhooks/subscriber_spec.rb
Labels: api

#788 close #787 add restart checkout flow api
  app/controllers/spree_cm_commissioner/api/v2/storefront/cart_controller_decorator.rb
  config/routes.rb
Labels: api

#790 Close #789 update ticket template link base on product type
  app/helpers/spree/base_helper_decorator.rb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_items.html.erb
Labels: enhancement

#792 close #791 account recover api
  app/controllers/spree/api/v2/storefront/account_recovers_controller.rb
  app/interactors/spree_cm_commissioner/account_recover.rb
  app/interactors/spree_cm_commissioner/user_id_token_authenticator.rb
  app/interactors/spree_cm_commissioner/user_password_authenticator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  config/routes.rb
  db/migrate/20231101110711_add_account_restored_at_to_spree_users.rb
  spec/interactors/spree_cm_commissioner/account_recover_spec.rb
Labels: api

#794 close #793 fix undefine method user.full_name empty? for nil:nilClass
  app/models/spree_cm_commissioner/user_decorator.rb
  spec/models/spree_cm_commissioner/user_spec.rb
Labels: hotfix

#798 close #797 authorized subscriber to access only resource that authorized by rules
  app/controllers/spree/api/webhook/base_controller.rb
  app/controllers/spree/api/webhook/orders_controller.rb
  app/controllers/spree_cm_commissioner/orders_controller.rb
  app/controllers/spree_cm_commissioner/qr_images_controller.rb
  app/models/concerns/spree_cm_commissioner/webhooks/subscriber_rulable.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/webhooks/rules/order_states.rb
  app/models/spree_cm_commissioner/webhooks/rules/order_vendors.rb
  app/models/spree_cm_commissioner/webhooks/subscriber_rule.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/webhooks/subscriber_spec.rb
  spec/models/spree_cm_commissioner/webhooks/rules/order_states_spec.rb
  spec/models/spree_cm_commissioner/webhooks/rules/order_vendors_spec.rb
Labels: feature

#801 close #800 bulk send request to subscriber
  app/controllers/spree/admin/webhooks_subscriber_orders_controller.rb
  app/interactors/spree_cm_commissioner/webhook_subscriber_orders_sender.rb
  app/jobs/spree_cm_commissioner/webhook_subscriber_orders_sender_job.rb
  app/models/spree_cm_commissioner/webhooks/rules/order_states.rb
  app/models/spree_cm_commissioner/webhooks/rules/order_vendors.rb
  app/overrides/spree/admin/webhooks_subscribers/index/table.html.erb.deface
  app/views/spree/admin/webhooks_subscriber_orders/index.html.erb
  config/routes.rb
Labels: feature

#804 close #803 add weekend promotion rule
  app/models/spree_cm_commissioner/promotion/rules/date.rb
  app/models/spree_cm_commissioner/promotion/rules/fixed_date.rb
  app/models/spree_cm_commissioner/promotion/rules/weekend.rb
  app/views/spree/admin/promotions/rules/_fixed_date.html.erb
  app/views/spree/admin/promotions/rules/_weekend.html.erb
  config/locales/en.yml
  config/locales/km.yml
  lib/spree_cm_commissioner/engine.rb
  spec/models/spree_cm_commissioner/promotion/rules/date_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/fixed_date_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/weekend_spec.rb
Labels: enhancement, feature

#806 close #805 add multiple vendors promotion rule
  app/models/spree_cm_commissioner/promotion/rules/vendor.rb
  app/models/spree_cm_commissioner/promotion/rules/vendors.rb
  app/models/spree_cm_commissioner/vendor_promotion_rule.rb
  app/views/spree/admin/promotions/rules/_vendor.html.erb
  app/views/spree/admin/promotions/rules/_vendors.html.erb
  config/locales/en.yml
  config/locales/km.yml
  db/migrate/20231114034655_create_spree_cm_commissioner_vendor_promotion_rules.rb
  db/migrate/20231114085705_remove_spree_cm_commissioner_promotion_rules_vendor.rb
  lib/spree_cm_commissioner/engine.rb
  spec/models/spree_cm_commissioner/promotion/rules/vendor_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/vendors_spec.rb
  spec/models/spree_cm_commissioner/vendor_promotion_rule_spec.rb
Labels: feature

#808 close #807 fix write query attempted while in readonly-mode spree_users
  app/controllers/spree/admin/base_controller_decorator.rb
Labels: bug

#810 close #809 add stock location serializer
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: api

#812 close #811 undefine vendor rule in migration
  db/migrate/20231114085705_remove_spree_cm_commissioner_promotion_rules_vendor.rb
Labels: bug

#814 close #813 add queue when call queue_webhooks_requests
  app/interactors/spree_cm_commissioner/webhook_subscriber_orders_sender.rb
  app/jobs/spree_cm_commissioner/queue_order_webhooks_requests_job.rb
  spec/jobs/spree_cm_commissioner/queue_order_webhooks_requests_job_spec.rb
  spec/jobs/spree_cm_commissioner/webhook_subscriber_orders_sender_job_spec.rb
Labels: enhancement

#816 close #815 update sms adaptor to plasgate
  app/interactors/spree_cm_commissioner/sms.rb
Labels: chore

#818 close #817 allow to set weekend days on promotion rule
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/spree_cm_commissioner/promotion/actions/create_date_specific_item_adjustments.rb
  app/models/spree_cm_commissioner/promotion/rules/weekend.rb
  app/models/spree_cm_commissioner/promotion_decorator.rb
  app/views/spree/admin/promotions/rules/_weekend.html.erb
  config/locales/en.yml
  config/locales/km.yml
  spec/models/spree/line_item_spec.rb
  spec/models/spree/stock/availability_validator_spec.rb
  spec/models/spree_cm_commissioner/promotion/actions/create_date_specific_item_adjustments_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/weekend_spec.rb
Labels: enhancement, spec

#820 close #819 fix relation between vendor to promotions
  app/models/concerns/spree_cm_commissioner/vendor_promotable.rb
  spec/models/spree/vendor_spec.rb
Labels: bug

#822 close #821 fix weekend always not eligible
  app/models/spree_cm_commissioner/promotion/rules/weekend.rb
  spec/models/spree_cm_commissioner/promotion/rules/weekend_spec.rb
Labels: bug

#829 close #828 implement dynamic section
  app/controllers/spree/admin/homepage_section_controller.rb
  app/controllers/spree/admin/homepage_section_relatable_controller.rb
  app/controllers/spree/api/v2/storefront/homepage_sections_controller.rb
  app/models/spree_cm_commissioner/homepage_section.rb
  app/models/spree_cm_commissioner/homepage_section_relatable.rb
  app/serializers/spree/v2/storefront/homepage_section_relatable_serializer.rb
  app/serializers/spree/v2/storefront/homepage_section_serializer.rb
  app/views/spree/admin/homepage_feed/_form.html.erb
  app/views/spree/admin/homepage_feed/shared/_feed_tabs.html.erb
  app/views/spree/admin/homepage_section/_form.html.erb
  app/views/spree/admin/homepage_section/edit.html.erb
  app/views/spree/admin/homepage_section/index.html.erb
  app/views/spree/admin/homepage_section/new.html.erb
  app/views/spree/admin/homepage_section_relatable/_form.html.erb
  app/views/spree/admin/homepage_section_relatable/edit.html.erb
  app/views/spree/admin/homepage_section_relatable/new.html.erb
  config/routes.rb
  db/migrate/20231114081649_create_spree_cm_commissioner_homepage_sections.rb
  db/migrate/20231114082243_create_spree_cm_commissioner_homepage_section_relatables.rb
  spec/models/spree_cm_commissioner/homepage_section_relatable_spec.rb
  spec/models/spree_cm_commissioner/homepage_section_spec.rb
Labels: feature

#833 close #832 save queue id to sms log
  app/interactors/spree_cm_commissioner/sms.rb
  app/services/sms_adapter/base.rb
  app/services/sms_adapter/plasgate.rb
  app/services/sms_adapter/twillio.rb
  db/migrate/20231120105233_add_external_ref_to_sms_log.rb
  spec/interactors/spree_cm_commissioner/sms_spec.rb
Labels: enhancement

#835 close #834 bring back organization tab
  Gemfile.lock
  app/overrides/spree/admin/shared/_main_menu/sidebar_organizations.html.erb.deface
  app/overrides/spree/admin/vendors/index/index.html.erb.deface
  spree_cm_commissioner.gemspec
Labels: enhancement

#837 close #836 add active field to homepage banner
  app/views/spree/admin/homepage_banner/_form.html.erb
Labels: enhancement, backend

#839 close #838 not force update order.request_state when complete
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  spec/models/spree/order_spec.rb
Labels: bug

#841 close #840 add create date specific adjustment platform serializer
  app/serializers/spree/api/v2/platform/create_date_specific_item_adjustment_serializer.rb
Labels: enhancement

#843 close #842 fix undefine promotion_id for source when promotion action is deleted
  app/models/spree_cm_commissioner/order_decorator.rb
  spec/models/spree/order_spec.rb
Labels: bug

#824 close #823 notify order complete notification to user only when payme…
  app/controllers/spree/admin/customer_notifications_controller.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/notifications/noticed_fcm_base.rb
  spec/models/spree/order_spec.rb
Labels: bug, enhancement

#851 close #850 fix plasgate not send sms
  app/services/sms_adapter/plasgate.rb
  spec/interactors/spree_cm_commissioner/sms_spec.rb
Labels: bug, hotfix

#849 close #848 remove penalty from order summary
  app/overrides/spree/admin/shared/_order_summary/adjustment_total.html.erb.deface
  app/overrides/spree/admin/shared/_order_summary/penalty.html.erb.deface
Labels: backend

#853 close #852 send image in notification payload
  app/models/spree_cm_commissioner/customer_notification.rb
  app/models/spree_cm_commissioner/store_decorator.rb
  app/notifications/noticed_fcm_base.rb
  app/notifications/spree_cm_commissioner/customer_content_notification.rb
  app/overrides/spree/admin/stores/form/_layout/default_notification_image.html.erb.deface
  config/initializers/spree_permitted_attributes.rb
Labels: enhancement

#860 close #830 edit line item fields backend
  app/controllers/spree/admin/line_items_controller.rb
  app/overrides/spree/admin/orders/_line_items/_line_items.html.erb.deface
  app/views/spree/admin/line_items/_form.html.erb
  app/views/spree/admin/line_items/edit.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: backend

#862 close #861 add vendor nearby_places to stock_location_serializer
  app/models/spree_cm_commissioner/stock_location_decorator.rb
  app/serializers/spree/v2/storefront/stock_location_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/stock_location_serializer_spec.rb
Labels: api
