Repository channainfo/commissioner, pull requests merged in 2023-04, with the labels that each got.

#291 close #290 save current user to payment state machine
  app/controllers/spree/admin/merchant/payments_controller.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/payment_decorator.rb
  app/models/spree_cm_commissioner/state_change_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/views/spree/admin/merchant/payments/_list.html.erb
  app/views/spree/admin/merchant/report/show.html.erb
  db/migrate/20230330120250_add_payable_to_spree_payment.rb
  spec/models/spree/payment_spec.rb
Labels: subscription, payment

#302 Close #286 Booking Email template
  Gemfile.lock
  app/assets/config/spree_cm_commissioner_manifest.js
  app/assets/stylesheets/spree_cm_commissioner/mailer/base.css.scss
  app/assets/stylesheets/spree_cm_commissioner/mailer/order/style.scss
  app/helpers/spree/mail_helper_decorator.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/views/spree/order_mailer/confirm_email.html.erb
  app/views/spree_cm_commissioner/layouts/order_mailer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_header.html.erb
  app/views/spree_cm_commissioner/order_mailer/_purchased_items.html.erb
  app/views/spree_cm_commissioner/order_mailer/_purchased_summary.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_line_item.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_vendor_info.html.erb
  config/locales/en.yml
  lib/spree_cm_commissioner.rb
  spree_cm_commissioner.gemspec
Labels: feature

#301 Close #300 add tacteng font
  app/assets/fonts/tacteng.ttf
  app/assets/stylesheets/spree_cm_commissioner/backend/invoice.scss
  app/views/spree/admin/merchant/shared/_invoice.html.erb
Labels: backend

#289 close #288 added cron job for subscriptions
  app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
  app/jobs/spree_cm_commissioner/subscription_order_executor_job.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/subscription.rb
  app/views/spree/admin/merchant/customers/index.html.erb
  app/views/spree/admin/merchant/shared/_vendor_switcher.html.erb
  db/migrate/20230330085530_add_last_occurence_to_cm_commissioner_subscription.rb
  db/migrate/20230403071100_add_version_to_cm_commissioner_subscription.rb
  docs/sql/subscriptions/remaining_subscriptions.sql
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
Labels: backend

#316 close #315 fix spec pass when run individually & but fails on all
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/queries/spree_cm_commissioner/subscription_orders_query_spec.rb
  spec/spec_helper.rb
Labels: bug, documentation

#306 Close #305 enhance design
  Gemfile.lock
  app/assets/config/spree_cm_commissioner_manifest.js
  app/assets/fonts/Moul-Regular.ttf
  app/assets/stylesheets/spree_cm_commissioner/backend/commissioner_admin.css.scss
  app/assets/stylesheets/spree_cm_commissioner/backend/invoice.scss
  app/interactors/spree_cm_commissioner/nearby_place_creator.rb
  app/interactors/spree_cm_commissioner/nearby_place_distance_finder.rb
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/admin/merchant/invoice/show.html.erb
  app/views/spree/admin/merchant/shared/_invoice.html.erb
  app/views/spree/admin/merchant/shared/_order_tabs.html.erb
  app/views/spree/admin/merchant/shared/_vendor_logo.html.erb
  app/views/spree/admin/merchant/shared/_vendor_switcher.html.erb
  app/views/spree/layouts/merchant.html.erb
Labels: enhancement

#322 close #312 add states changes to payment view
  app/controllers/spree/admin/merchant/payments_controller.rb
  app/views/spree/admin/merchant/payments/_state_changes.html.erb
  app/views/spree/admin/merchant/payments/show.html.erb
Labels: feature, view
