Repository channainfo/commissioner, pull requests merged in 2024-02, with the labels that each got.

#1068 close #1067 check whether guest is allowed checkout
  app/controllers/spree/api/v2/storefront/guest_line_items_controller.rb
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/id_card.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_line_item_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  config/routes.rb
  db/migrate/20240201074345_remove_gender_default_value_from_guest.rb
  lib/spree_cm_commissioner/test_helper/factories/back_image_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/front_image_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/id_card_factory.rb
  spec/interactors/spree_cm_commissioner/check_in_bulk_creator_spec.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
  spec/models/spree_cm_commissioner/id_card_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: enhancement

#1053 Close #1050 create a product tab and then connect the product to the taxon
  app/controllers/spree/admin/classifications_controller.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/views/spree/admin/classifications/edit.html.erb
  app/views/spree/admin/classifications/index.html.erb
  app/views/spree/admin/classifications/new.html.erb
  app/views/spree/admin/shared/_products.html.erb
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  config/routes.rb
Labels: enhancement, M

#1071 close #1070 undefined method update customer notification send at
  app/interactors/spree_cm_commissioner/customer_notification_cron_executor.rb
Labels: bug

#1083 close #1082 fixed vehicle_type not loading the correct amenities
  app/controllers/spree/transit/amenities_controller.rb
  app/controllers/spree/transit/vehicle_types_controller.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/views/spree/transit/shared/_main_menu.html.erb
Labels: backend, transit

#1080 close #1078 add notification type to request order payload
  app/notifications/spree_cm_commissioner/order_accepted_notification.rb
  app/notifications/spree_cm_commissioner/order_rejected_notification.rb
  app/notifications/spree_cm_commissioner/order_requested_notification.rb
Labels: enhancement

#1076 close #1075 remove cache from guest serializer
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
Labels: bug, S

#1081 Close #1079 add subTitle column and add subTitle in taxon page
  app/overrides/spree/admin/taxons/_form/sub_title.html.erb.deface
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20240202101246_add_sub_title_to_spree_taxon.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: enhancement, api, backend

#1090 close #1089 add group payment by bank api
  app/controllers/spree/api/v2/storefront/account/preferred_payment_method_controller.rb
  app/controllers/spree/api/v2/storefront/cart_payment_method_groups_controller.rb
  app/finders/spree_cm_commissioner/payment_methods/group_by_bank.rb
  app/models/concerns/spree_cm_commissioner/user_preference.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/payment_method_group_serializer.rb
  config/routes.rb
  db/migrate/20240205075923_add_preferences_to_spree_user.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/payment_method_group.rb
  spec/finders/spree_cm_commissioner/payment_methods/group_by_bank_spec.rb
Labels: feature, api

#1100 close #1099 display new payment for only early adopter user
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/payment_method_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/overrides/spree/admin/payment_methods/_form/display_on_field.html.erb.deface
  app/services/spree_cm_commissioner/seeds/roles_decorator.rb
  config/locales/en.yml
  config/locales/km.yml
  lib/spree_cm_commissioner/test_helper/factories/user_factory.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/payment_method_spec.rb
Labels: feature, S

#1015 Close #1011 change transit taxonomies url
  Gemfile
  Gemfile.lock
  app/controllers/spree/transit/places_controller.rb
  app/controllers/spree/transit/taxonomies_controller.rb
  app/helpers/spree/transit/sortable_tree_helper.rb
  app/models/concerns/spree_cm_commissioner/taxonomy_kind.rb
  app/models/spree_cm_commissioner/taxonomy_decorator.rb
  app/views/spree/transit/places/_assets_form.html.erb
  app/views/spree/transit/places/_form.html.erb
  app/views/spree/transit/places/edit.html.erb
  app/views/spree/transit/places/index.html.erb
  app/views/spree/transit/places/new.html.erb
  app/views/spree/transit/routes/index.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  app/views/spree/transit/shared/sortable_tree/_taxonomy.html.erb
  app/views/spree/transit/taxonomies/_filters.html.erb
  app/views/spree/transit/taxonomies/_form.html.erb
  app/views/spree/transit/taxonomies/_list.html.erb
  app/views/spree/transit/taxonomies/edit.html.erb
  app/views/spree/transit/taxonomies/index.html.erb
  app/views/spree/transit/taxons/index.html.erb
  app/views/spree/transit/taxons/new.html.erb
  app/views/spree/transit/vehicles/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/models/spree/taxonomy_spec.rb
Labels: backend, transit

#1077 close #1064 api for dashboard_crew_events
  app/controllers/spree/api/v2/operator/dashboard_crew_events_controller.rb
  app/controllers/spree/api/v2/operator/event_ticket_aggregators_controller.rb
  app/controllers/spree_cm_commissioner/admin/payments_controller_decorator.rb
  app/queries/spree_cm_commissioner/dashboard_crew_event_query.rb
  app/queries/spree_cm_commissioner/event_ticket_aggregator_query.rb
  app/serializables/spree_cm_commissioner/event_ticket_aggregator.rb
  app/serializers/spree_cm_commissioner/v2/operator/dashboard_crew_event_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/event_ticket_aggregator_serializer.rb
  config/routes.rb
Labels: api, L

#1104 close #1101 spec test for dashboard crew events query
  app/controllers/spree/api/v2/operator/dashboard_crew_events_controller.rb
  app/queries/spree_cm_commissioner/dashboard_crew_event_query.rb
  app/serializers/spree_cm_commissioner/v2/operator/check_in_serializer.rb
  lib/spree_cm_commissioner/test_helper/factories/user_factory.rb
  spec/queries/spree_cm_commissioner/dashboard_crew_event_query_spec.rb
Labels: api, spec, S

#1041 close #1031 api for pie_chart crew event dashboard
  app/controllers/spree/api/v2/operator/pie_chart_event_aggregators_controller.rb
  app/queries/spree_cm_commissioner/pie_chart_event_aggregator_queries.rb
  app/serializables/spree_cm_commissioner/pie_chart_event_aggregator.rb
  app/serializers/spree_cm_commissioner/v2/operator/guest_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/pie_chart_event_aggregator_serializer.rb
  config/routes.rb
Labels: api, L

#1020 Close #930 Guest Promotion
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/guest_occupation_promotion_rule.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/promotion/actions/create_guest_item_adjustments.rb
  app/models/spree_cm_commissioner/promotion/rules/guest.rb
  app/models/spree_cm_commissioner/promotion/rules/guest_age_group.rb
  app/models/spree_cm_commissioner/promotion/rules/guest_occupations.rb
  app/models/spree_cm_commissioner/promotion_decorator.rb
  app/views/spree/admin/promotions/actions/_create_guest_item_adjustments.html.erb
  app/views/spree/admin/promotions/rules/_guest_age_group.html.erb
  app/views/spree/admin/promotions/rules/_guest_occupations.html.erb
  config/locales/en.yml
  config/locales/km.yml
  db/migrate/20240109081006_create_spree_cm_commissioner_guest_occupation_promotion_rules.rb
  docs/spree_core/add_new_promotion.md
  lib/spree_cm_commissioner/engine.rb
  spec/models/spree_cm_commissioner/promotion/actions/create_guest_item_adjustments_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/guest_age_group_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/guest_occupations_spec.rb
Labels: feature

#1106 close #1105 rspec test for event_ticket_aggregator_query
  app/queries/spree_cm_commissioner/event_ticket_aggregator_query.rb
  spec/queries/spree_cm_commissioner/event_ticket_aggregator_query_spec.rb
Labels: api, spec, S

#1116 close #1114 move homepage to main menu tab
  app/overrides/spree/admin/shared/_main_menu/sidebar_homepage.html.erb.deface
  app/overrides/spree/admin/shared/sub_menu/_configuration/menu_items.html.erb.deface
  app/views/spree/admin/homepage_background/index.html.erb
  app/views/spree/admin/homepage_banner/index.html.erb
  app/views/spree/admin/homepage_feed/edit.html.erb
  app/views/spree/admin/homepage_feed/shared/_feed_tabs.html.erb
  app/views/spree/admin/homepage_section/index.html.erb
  app/views/spree/admin/shared/sub_menu/_homepage.html.erb
Labels: enhancement, feature, S

#1111 close #1109 rspec api for pie_chart dashboard_crew_event
  app/queries/spree_cm_commissioner/pie_chart_event_aggregator_queries.rb
  spec/queries/spree_cm_commissioner/pie_chart_event_aggregator_queries_spec.rb
Labels: api, spec, S

#1113 close #1112 refactor precaculate event ticket total
  app/interactors/spree_cm_commissioner/products_taxons_total_count_pre_calculator.rb
  app/jobs/spree_cm_commissioner/products_taxons_total_count_pre_calculator_job.rb
  app/models/spree_cm_commissioner/classification_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/queries/spree_cm_commissioner/event_ticket_aggregator_query.rb
  db/migrate/20240212102718_add_total_count_to_spree_products_taxons.rb
  lib/spree_cm_commissioner/test_helper/factories/products_taxons_factory.rb
  spec/jobs/spree_cm_commissioner/products_taxons_total_count_pre_calculator_job_spec.rb
  spec/queries/spree_cm_commissioner/event_ticket_aggregator_query_spec.rb
Labels: api, M

#1120 close #1119 add badge to menu item
  app/overrides/spree/admin/menu_items/_form/badge_field.html.erb.deface
  app/serializers/spree_cm_commissioner/v2/storefront/menu_item_serializer_decorator.rb
  db/migrate/20240215090018_add_badge_to_spree_menu_items.rb
Labels: enhancement, S

#1110 close #1097 add segment bitwise to homepage_sections table
  app/controllers/spree/admin/homepage_section_controller.rb
  app/helpers/spree_cm_commissioner/admin/homepage_segment_helper.rb
  app/models/concerns/spree_cm_commissioner/homepage_section_bitwise.rb
  app/models/spree_cm_commissioner/homepage_section.rb
  app/models/spree_cm_commissioner/homepage_section_relatable.rb
  app/overrides/spree/admin/shared/_main_menu/sidebar_homepage.html.erb.deface
  app/serializers/spree/v2/storefront/homepage_section_serializer.rb
  app/views/spree/admin/homepage_background/index.html.erb
  app/views/spree/admin/homepage_banner/index.html.erb
  app/views/spree/admin/homepage_feed/edit.html.erb
  app/views/spree/admin/homepage_section/_form.html.erb
  app/views/spree/admin/homepage_section/index.html.erb
  db/migrate/20240207065651_add_segment_to_homepage_sections.rb
  db/migrate/20240215072543_add_homepage_section_relatables_count_to_homepage_sections.rb
  spec/interactors/spree_cm_commissioner/admin/homepage_segment_helper_spec.rb
  spec/models/spree_cm_commissioner/homepage_section_relatable_spec.rb
  spec/models/spree_cm_commissioner/homepage_section_spec.rb
Labels: feature, spec, L

#1117 close #1102 allow api filter homepage sections by segment
  app/controllers/spree/api/v2/storefront/homepage_sections_controller.rb
  app/models/concerns/spree_cm_commissioner/homepage_section_bitwise.rb
  app/models/spree_cm_commissioner/homepage_section.rb
  config/routes.rb
  spec/models/spree_cm_commissioner/homepage_section_spec.rb
Labels: enhancement, api, M

#1124 close #1123 fixed changing seat-type leads to multiple redundant post requests
  app/assets/javascripts/spree_cm_commissioner/vehicle_seat.js
Labels: bug, backend, transit

#1128 close #1125 return line_items to check_ins for dashboard history
  app/models/spree_cm_commissioner/check_in.rb
  app/serializers/spree_cm_commissioner/v2/operator/check_in_serializer.rb
Labels: api, XS

#1126 close #1118 segment homepage image background for specific page
  app/controllers/spree/admin/homepage_background_controller.rb
  app/controllers/spree/admin/homepage_section_controller.rb
  app/controllers/spree/api/v2/storefront/homepage_background_controller.rb
  app/helpers/spree_cm_commissioner/admin/homepage_segment_helper.rb
  app/models/concerns/spree_cm_commissioner/homepage_section_bitwise.rb
  app/models/spree_cm_commissioner/homepage_background.rb
  app/serializers/spree_cm_commissioner/v2/storefront/homepage_background_serializer.rb
  app/views/spree/admin/homepage_background/_form.html.erb
  app/views/spree/admin/homepage_background/index.html.erb
  app/views/spree/admin/homepage_section/index.html.erb
  config/routes.rb
  db/migrate/20240216024911_add_segment_to_homepage_background.rb
  spec/models/spree_cm_commissioner/homepage_background_spec.rb
Labels: enhancement, api, S

#1138 close #1137 remove kyc checkbox from product form, it is not neccessary
  app/overrides/spree/admin/products/_form/include_kyc_checkbox.html.erb.deface
Labels: bug, XS

#1144 close #1143 reload order before recaculate
  app/services/spree_cm_commissioner/cart/recalculate_decorator.rb
  spec/services/spree/cart/remove_line_item_spec.rb
Labels: bug, enhancement

#1147 close #1146 notification title and message does not show the lated up…
  app/models/spree_cm_commissioner/user_decorator.rb
Labels: bug

#1145 close #1142 change key api in pie_chart_event
  app/queries/spree_cm_commissioner/pie_chart_event_aggregator_queries.rb
Labels: api, XS

#1140 close #1139 add missing things_to_do badge background color
  app/helpers/spree_cm_commissioner/admin/homepage_segment_helper.rb
Labels: enhancement, XS

#1122 close #1121 fixed ActiveRecord::ReadOnlyError on /transit/route
  app/controllers/spree/transit/places_controller.rb
  app/controllers/spree/transit/routes_controller.rb
  app/models/spree_cm_commissioner/taxonomy_decorator.rb
Labels: backend, transit

#1152 close #1136 filter check_in by polymophic checkinable
  app/controllers/spree/api/v2/operator/check_in_bulks_controller.rb
  app/controllers/spree/api/v2/operator/check_ins_controller.rb
  app/interactors/spree_cm_commissioner/check_in_bulk_creator.rb
  app/models/spree_cm_commissioner/check_in.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/serializers/spree_cm_commissioner/v2/operator/check_in_serializer.rb
  db/migrate/20240221103954_add_check_in_able_to_check_ins.rb
  spec/interactors/spree_cm_commissioner/check_in_bulk_creator_spec.rb
Labels: api, S

#1158 close #1157 add started_at attribute type to spree_option_type
  app/models/concerns/spree_cm_commissioner/attr_type_validation.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/overrides/spree/admin/option_types/_option_value_fields/option_value_replacer.html.erb.deface
  spec/models/concerns/spree_cm_commissioner/attr_type_validation_spec.rb
Labels: backend

#1161 close #1155 return event and total_count with single api request and rspec
  app/controllers/spree/api/v2/operator/dashboard_crew_events_controller.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/queries/spree_cm_commissioner/dashboard_crew_event_query.rb
  app/serializers/spree_cm_commissioner/v2/operator/classification_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/dashboard_crew_event_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/product_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/taxon_serializer.rb
  lib/spree_cm_commissioner/test_helper/factories/taxon_factory.rb
  spec/queries/spree_cm_commissioner/dashboard_crew_event_query_spec.rb
Labels: api, M

#1162 close #1156 return pie_chart api group_by product_id
  app/queries/spree_cm_commissioner/pie_chart_event_aggregator_queries.rb
Labels: api, XS

#1164 close #1163 handle total_count and revenue classifications job via cancled and resumed order state
  app/interactors/spree_cm_commissioner/conversion_pre_calculator.rb
  app/interactors/spree_cm_commissioner/products_taxons_total_count_pre_calculator.rb
  app/jobs/spree_cm_commissioner/conversion_pre_calculator_job.rb
  app/jobs/spree_cm_commissioner/products_taxons_total_count_pre_calculator_job.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  db/migrate/20240226092103_add_revenue_to_spree_products_taxons.rb
  spec/jobs/spree_cm_commissioner/conversion_pre_calculator_job_spec.rb
  spec/jobs/spree_cm_commissioner/products_taxons_total_count_pre_calculator_job_spec.rb
Labels: api, S

#1149 close #1148 add dashboard for organizer to view all guests information
  app/controllers/spree/events/base_controller.rb
  app/controllers/spree/events/guests_controller.rb
  app/controllers/spree_cm_commissioner/application_controller_decorator.rb
  app/helpers/spree_cm_commissioner/admin/guest_helper.rb
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/models/spree_cm_commissioner/check_in.rb
  app/models/spree_cm_commissioner/check_in_ability.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/id_card.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  app/views/spree/admin/user_taxons/edit.html.erb
  app/views/spree/admin/user_taxons/index.html.erb
  app/views/spree/admin/user_taxons/new.html.erb
  app/views/spree/events/guests/_form.html.erb
  app/views/spree/events/guests/edit.html.erb
  app/views/spree/events/guests/index.html.erb
  app/views/spree/events/shared/_event_switcher.html.erb
  app/views/spree/events/shared/_filters.html.erb
  app/views/spree/events/shared/_header.html.erb
  app/views/spree/events/shared/_main_menu.html.erb
  app/views/spree/layouts/event.html.erb
  config/routes.rb
  db/migrate/20240222100510_add_event_id_column_to_spree_cm_commissioner_guests.rb
  db/migrate/20240223030503_add_slug_to_taxons.rb
  db/migrate/20240223080038_add_entry_type_to_guests.rb
  lib/spree_cm_commissioner/test_helper/factories/guest_factory.rb
Labels: feature, L

#1072 Close #1061 Add Account Name and Account Number to Spree Vendors
  app/controllers/spree/billing/payment_qrcodes_controller.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/billing/shared/_invoice.html.erb
  app/views/spree/billing/vendors/_form.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: backend

#1178 close #1171 enchance dashboard-crew-event classification_serializer
  app/controllers/spree/api/v2/operator/dashboard_crew_events_controller.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/queries/spree_cm_commissioner/dashboard_crew_event_query.rb
  app/serializers/spree_cm_commissioner/v2/operator/dashboard_crew_event_serializer.rb
  spec/queries/spree_cm_commissioner/dashboard_crew_event_query_spec.rb
Labels: api, M

#1180 close #1179 adding case to dashboard_crew_event_query_spec to test query looped or not
  spec/queries/spree_cm_commissioner/dashboard_crew_event_query_spec.rb
Labels: spec, XS
