Repository channainfo/commissioner, pull requests merged in 2024-08, with the labels that each got.

#1688 close #1658 guest order api
  app/controllers/spree/api/v2/storefront/cart_payment_method_groups_controller.rb
  app/controllers/spree/api/v2/storefront/guest_orders_controller.rb
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/controllers/spree/api/v2/storefront/line_items_controller.rb
  app/controllers/spree_cm_commissioner/api/v2/storefront/cart_controller_decorator.rb
  app/controllers/spree_cm_commissioner/api/v2/storefront/checkout_controller_decorator.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  config/routes.rb
Labels: api

#1689 close #1687 claim guest order to user
  app/controllers/spree/api/v2/storefront/user_order_transfer_controller.rb
  app/interactors/spree_cm_commissioner/user_order_transfer_handler.rb
  config/routes.rb
  spec/interactors/spree_cm_commissioner/user_order_transfer_handler_spec.rb
Labels: api

#1674 close #1599 change invoice recurring logic
  app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/subscription.rb
  app/views/spree/billing/orders/index.html.erb
  config/locales/en.yml
  config/locales/km.yml
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
  spec/queries/spree_cm_commissioner/subscription_orders_query_spec.rb
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
  spec/services/spree_cm_commissioner/penalty_calculator_spec.rb
  spec/spec_helper.rb
Labels: backend, billing

#1675 Close #1673 Create order promotion api that available on specific products
  app/controllers/spree/api/v2/storefront/order_promotions_controller.rb
  config/routes.rb
Labels: api, backend

#1723 close #1722 add address field to cm guest
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/spree_cm_commissioner/guest.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  db/migrate/20240731095720_add_address_to_spree_cm_commissioner.rb
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
Labels: api, backend

#1720 Close #1719 allow customer to have recurring promotion
  app/controllers/spree/billing/customers_controller.rb
  app/interactors/spree_cm_commissioner/customer_promotion_creator.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/billing/shared/_customer_promotion_form.html.erb
  app/views/spree/billing/shared/_customer_promotion_table.html.erb
  app/views/spree/billing/subscriptions/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/interactors/spree_cm_commissioner/customer_promotion_creator_spec.rb
  spec/models/spree/line_item_spec.rb
Labels: backend, billing

#1733 close #1732 set order channel API
  app/models/spree_cm_commissioner/order_decorator.rb
  app/serializers/spree/v2/storefront/cart_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  spec/serializers/spree/v2/storefront/cart_serializer_spec.rb
  spec/services/spree_cm_commissioner/imports/import_order_service_spec.rb
Labels: api

#1731 close #1730 authenticate with telegram init data
  app/interactors/spree_cm_commissioner/user_telegram_web_app_authenticator.rb
  app/services/spree_cm_commissioner/user_authenticator.rb
  spec/interactors/spree_cm_commissioner/user_telegram_web_app_authenticator_spec.rb
  spec/services/spree_cm_commissioner/user_authenticator_spec.rb
Labels: feature

#1716 close #1715 user guest api
  app/controllers/spree/api/v2/storefront/user_guests_controller.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  config/routes.rb
  db/migrate/20240729080553_add_user_to_spree_cm_commissioner_guests.rb
Labels: api

#1724 Close #1721 handle media convert job status callback from AWS lambda
  .env.example
  app/controllers/spree/api/webhook/media_convert_queues_controller.rb
  app/interactors/spree_cm_commissioner/media/signer.rb
  app/interactors/spree_cm_commissioner/sqs/media_convert_job_status.rb
  app/models/spree_cm_commissioner/video_on_demand.rb
  db/migrate/20240802023034_change_column_cdn_id_to_remote_job_id_in_cm_video_on_demands.rb
  db/migrate/20240802024216_add_column_output_groups_to_video_on_demands.rb
  db/migrate/20240803035226_add_column_completed_at_to_cm_video_on_demands.rb
  lib/spree_cm_commissioner/test_helper/factories/video_on_demand_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/webhook_subscriber_factory.rb
  spec/controllers/spree/api/webhook/base_controller_spec.rb
  spec/fixtures/media_convert_queue-complete.json
  spec/fixtures/media_convert_queue-submitted.json
  spec/interactors/spree_cm_commissioner/media/signed_cookie_generator_spec.rb
  spec/interactors/spree_cm_commissioner/media/signed_path_generator_spec.rb
  spec/interactors/spree_cm_commissioner/media/signed_url_generator_spec.rb
  spec/interactors/spree_cm_commissioner/sqs/media_convert_job_status_spec.rb
  spec/request/spree/api/webhook/media_convert_queues_spec.rb
Labels: feature

#1743 close #1742 guest qr code template
  app/assets/stylesheets/spree_cm_commissioner/backend/commissioner_admin.css.scss
  app/assets/stylesheets/spree_cm_commissioner/backend/guest_qr_code.scss
  app/controllers/spree/admin/guest_qr_codes_controller.rb
  app/overrides/spree/admin/variants/index/guest_qr_codes_button.html.erb.deface
  app/views/spree/admin/guest_qr_codes/index.html.erb
  app/views/spree/admin/shared/_guest_qr_code.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: api

#1740 close #1739 change order status from failed to voided
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/payments/_list.html.erb
  app/views/spree/billing/reports/failed_orders.html.erb
  app/views/spree/billing/reports/index.html.erb
  config/locales/en.yml
Labels: backend, billing

#1758 close #1757 add apply promotion permission to user role
  app/controllers/spree/billing/roles_controller.rb
Labels: bug, backend, billing

#1718 Close #1711 Billing report overview bug
  app/controllers/spree/billing/reports_controller.rb
  app/queries/spree_cm_commissioner/subscription_revenue_overview_query.rb
  spec/controllers/spree/billing/report_controller_spec.rb
Labels: bug, backend, billing

#1707 Close #1700 Rename orders index page
  app/views/spree/billing/orders/index.html.erb
Labels: backend, billing

#1705 close #1704 generate unique guest bib number in event scope
  app/interactors/spree_cm_commissioner/conversion_pre_calculator.rb
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  app/models/concerns/spree_cm_commissioner/option_type_attr_type.rb
  app/models/concerns/spree_cm_commissioner/order_bib_number_concern.rb
  app/models/concerns/spree_cm_commissioner/variant_options_concern.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/variant_options.rb
  app/serializers/spree_cm_commissioner/v2/operator/guest_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  db/migrate/20240717111317_add_bib_number_and_prefix_to_cm_guests.rb
  db/migrate/20240801034832_add_bib_index_to_cm_guests.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  spec/interactors/spree_cm_commissioner/conversion_pre_calculator_spec.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
  spec/serializers/spree_cm_commissioner/v2/operator/line_item_serializer_spec.rb
Labels: XS, validation

#1744 Close #1734 create a page for the guest card focusing on bib card background and color
  app/controllers/spree/admin/guest_card_classes_controller.rb
  app/models/spree_cm_commissioner/bib_card_background_image.rb
  app/models/spree_cm_commissioner/guest_card_class.rb
  app/models/spree_cm_commissioner/guest_card_classes/bib_card_class.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/views/spree/admin/guest_card_classes/_form.html.erb
  app/views/spree/admin/guest_card_classes/classes/_bib_card_class.html.erb
  app/views/spree/admin/guest_card_classes/edit.html.erb
  app/views/spree/admin/guest_card_classes/index.html.erb
  app/views/spree/admin/guest_card_classes/new.html.erb
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20240807090340_create_spree_cm_commissioner_guest_card_classes.rb
Labels: enhancement, feature

#1746 close #1745 add event variant serializer
  app/serializers/spree_cm_commissioner/v2/operator/line_item_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/event_option_value_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/event_variant_serializer.rb
  spec/serializers/spree_cm_commissioner/v2/operator/line_item_serializer_spec.rb
Labels: api

#1759 close #1749 add pagination to guest qr codes
  app/assets/stylesheets/spree_cm_commissioner/backend/guest_qr_code.scss
  app/controllers/spree/admin/guest_qr_codes_controller.rb
  app/helpers/spree/billing/navigation_helper_decorator.rb
  app/overrides/spree/admin/variants/index/guest_orders_button.html.erb.deface
  app/overrides/spree/admin/variants/index/guest_qr_codes_button.html.erb.deface
  app/views/spree/admin/guest_qr_codes/_guest_qr_code.html.erb
  app/views/spree/admin/guest_qr_codes/_guest_qr_codes_pagination.erb
  app/views/spree/admin/guest_qr_codes/_guest_qr_codes_print_template.html.erb
  app/views/spree/admin/guest_qr_codes/index.html.erb
  config/locales/en.yml
Labels: enhancement, backend

#1748 close #1747 save variant options to its public metadata
  app/jobs/spree_cm_commissioner/option_type_variants_public_metadata_updater_job.rb
  app/jobs/spree_cm_commissioner/option_value_variants_public_metadata_updater_job.rb
  app/jobs/spree_cm_commissioner/variants_public_metadata_updater_job.rb
  app/models/concerns/spree_cm_commissioner/option_type_attr_type.rb
  app/models/concerns/spree_cm_commissioner/option_value_attr_type.rb
  app/models/concerns/spree_cm_commissioner/variant_options_concern.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/variant_options.rb
  lib/tasks/variants_public_metadata_updater.rake
  spec/models/concerns/spree_cm_commissioner/option_type_attr_type_spec.rb
  spec/models/concerns/spree_cm_commissioner/option_value_attr_type_spec.rb
  spec/models/concerns/spree_cm_commissioner/variant_options_concern_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/queries/spree_cm_commissioner/dashboard_crew_event_query_spec.rb
Labels: enhancement

#1708 close #1706 allow swap bib number
  app/controllers/spree/events/guests_controller.rb
  app/interactors/spree_cm_commissioner/bib_number_swapper.rb
  app/views/spree/events/guests/_form.html.erb
  app/views/spree/events/guests/_swap_guest_bib_number.html.erb
  app/views/spree/events/guests/edit.html.erb
  app/views/spree/events/guests/index.html.erb
  config/routes.rb
  spec/interactors/spree_cm_commissioner/bib_number_swapper_spec.rb
  spec/models/spree_cm_commissioner/variant_options_spec.rb
Labels: feature, M

#1786 Close #1769 Billing report overview bug
  app/controllers/spree/billing/reports_controller.rb
  app/interactors/spree_cm_commissioner/invoice_creator.rb
  app/queries/spree_cm_commissioner/subscription_revenue_overview_query.rb
  app/views/spree/billing/payments/_list.html.erb
  app/views/spree/billing/reports/balance_due.html.erb
  app/views/spree/billing/reports/index.html.erb
  app/views/spree/billing/shared/_pop_up_confirmation.html.erb
  spec/controllers/spree/billing/report_controller_spec.rb
  spec/interactors/spree_cm_commissioner/invoice_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
Labels: bug, backend, billing

#1771 close #1770 generate bib number for remaining guests (anonymous)
  app/models/concerns/spree_cm_commissioner/line_item_guests_concern.rb
  app/models/concerns/spree_cm_commissioner/order_bib_number_concern.rb
  spec/models/spree/line_item_spec.rb
Labels: enhancement, feature

#1780 close #1779 Remove .complete from guest generate bib number
  app/models/spree_cm_commissioner/guest.rb
Labels: enhancement

#1785 close #1784 add bib number to guest qr-code
  app/views/spree/admin/guest_qr_codes/_guest_qr_code.html.erb
  app/views/spree/admin/guest_qr_codes/_guest_qr_codes_print_template.html.erb
  app/views/spree/admin/guest_qr_codes/index.html.erb
Labels: backend

#1788 close #1787 send order details to telegram web app user when order completed
  app/factory/spree_cm_commissioner/order_telegram_message_factory.rb
  app/factory/spree_cm_commissioner/telegram_message_factory.rb
  app/interactors/spree_cm_commissioner/order_complete_telegram_sender.rb
  app/jobs/spree_cm_commissioner/order_complete_telegram_sender_job.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/user_identity_provider.rb
  spec/cassettes/SpreeCmCommissioner_OrderCompleteTelegramSender/_call/when_order_is_associated_with_a_user_user_is_connected_to_Telegram/send_photo_to_provider_chat_ID.yml
  spec/interactors/spree_cm_commissioner/order_complete_telegram_sender_spec.rb
  spec/jobs/spree_cm_commissioner/order_complete_telegram_sender_job_spec.rb
  spec/models/spree_cm_commissioner/user_identity_provider_spec.rb
Labels: feature

#1793 close #1792 fix undefine method line_items_number_cont
  app/models/spree_cm_commissioner/line_item_decorator.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/order_spec.rb
Labels: bug

#1765 close #1764 import bulk guest order details csv
  app/controllers/spree/admin/base_import_orders_controller.rb
  app/controllers/spree/admin/import_existing_orders_controller.rb
  app/controllers/spree/admin/import_new_orders_controller.rb
  app/interactors/spree_cm_commissioner/import_csv_template_downloader.rb
  app/jobs/spree_cm_commissioner/import_order_job.rb
  app/models/spree_cm_commissioner/imports/import_order.rb
  app/overrides/spree/admin/shared/sub_menu/_orders/import_order.html.erb.deface
  app/services/spree_cm_commissioner/imports/import_order_service.rb
  app/views/spree/admin/import_existing_orders/_form.html.erb
  app/views/spree/admin/import_existing_orders/index.html.erb
  app/views/spree/admin/import_existing_orders/new.html.erb
  app/views/spree/admin/import_existing_orders/show.html.erb
  app/views/spree/admin/import_new_orders/_form.html.erb
  app/views/spree/admin/import_new_orders/_import_new_order_instruction.html.erb
  app/views/spree/admin/import_new_orders/index.html.erb
  app/views/spree/admin/import_new_orders/new.html.erb
  app/views/spree/admin/import_new_orders/show.html.erb
  app/views/spree/admin/shared/_import_order_tabs.html.erb
  config/routes.rb
  db/migrate/20240813092508_add_preferences_to_spree_cm_commissioner_import.rb
  db/migrate/20240814072342_change_import_type_to_integer_in_spree_cm_commissioner_import.rb
  spec/services/spree_cm_commissioner/imports/import_order_service_spec.rb
Labels: backend

#1775 Close #1773 add field name to table cm guest card classes
  app/views/spree/admin/guest_card_classes/classes/_bib_card_class.html.erb
  app/views/spree/admin/guest_card_classes/index.html.erb
  app/views/spree/admin/guest_card_classes/new.html.erb
  db/migrate/20240807090340_create_spree_cm_commissioner_guest_card_classes.rb
Labels: enhancement, feature

#1794 close #1778 setup models for product places
  app/models/spree_cm_commissioner/place.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/product_place.rb
  db/migrate/20240815065712_create_spree_cm_commissioner_product_places.rb
  spec/models/spree_cm_commissioner/place_spec.rb
  spec/models/spree_cm_commissioner/product_place_spec.rb
  spec/models/spree_cm_commissioner/product_spec.rb
Labels: enhancement

#1797 1795 add product place view
  app/controllers/spree/admin/product_places_controller.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/overrides/spree/admin/shared/_product_tabs/places.html.erb.deface
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/product_place_serializer.rb
  app/views/spree/admin/product_places/index.html.erb
  app/views/spree/admin/product_places/new.html.erb
  app/views/spree/admin/shared/_product_places_sidebar_tabs.html.erb
  app/views/spree/admin/shared/_product_places_sub_tabs.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20240819072041_add_position_to_product_places.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
Labels: enhancement, api

#1791 Close #1790 fix error with background image upload in guest card classes page
  app/controllers/spree/admin/guest_card_classes_controller.rb
  app/models/spree_cm_commissioner/bib_card_background_image.rb
  app/models/spree_cm_commissioner/guest_card_classes/bib_card_background_image.rb
  app/models/spree_cm_commissioner/guest_card_classes/bib_card_class.rb
  app/views/spree/admin/guest_card_classes/classes/_bib_card_class.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: bug

#1801 close #1800 remove All tab from product place view
  app/overrides/spree/admin/shared/_product_tabs/places.html.erb.deface
  app/views/spree/admin/shared/_product_places_sub_tabs.html.erb
Labels: enhancement

#1799 Close #1796 allow users to download imported orders csv
  app/controllers/spree/admin/base_import_orders_controller.rb
  app/controllers/spree/admin/import_existing_orders_controller.rb
  app/interactors/spree_cm_commissioner/imported_csv_downloader.rb
  app/models/spree_cm_commissioner/import.rb
  app/views/spree/admin/import_existing_orders/_form.html.erb
  app/views/spree/admin/import_existing_orders/index.html.erb
  app/views/spree/admin/import_existing_orders/show.html.erb
  app/views/spree/admin/import_new_orders/_form.html.erb
  app/views/spree/admin/import_new_orders/index.html.erb
  app/views/spree/admin/import_new_orders/show.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: enhancement, backend

#1781 Close #1768 Create an API for guest card classes
  app/controllers/spree/api/v2/storefront/guest_card_classes_controller.rb
  app/serializers/spree_cm_commissioner/v2/storefront/bib_card_class_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_card_class_serializer.rb
  config/routes.rb
  spec/controllers/spree/billing/report_controller_spec.rb
Labels: api, backend

#1809 Close #1808 update video upload flow
  app/controllers/spree/admin/video_on_demands_controller.rb
  app/interactors/spree_cm_commissioner/video_on_demand_creator.rb
  app/interactors/spree_cm_commissioner/video_on_demand_updater.rb
  app/models/concerns/spree_cm_commissioner/video_on_demand_bitwise.rb
  app/views/spree/admin/shared/_direct_upload.html.erb
  app/views/spree/admin/video_on_demands/_form.html.erb
  app/views/spree/admin/video_on_demands/edit.html.erb
  app/views/spree/admin/video_on_demands/index.html.erb
Labels: enhancement, L

#1802 Close #1798 create new table variant guest card
  app/controllers/spree/admin/variant_guest_card_classes_controller.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/variant_guest_card_class.rb
  app/overrides/spree/admin/shared/_product_tabs/guest_card.html.erb.deface
  app/views/spree/admin/variant_guest_card_classes/_variant_guest_card_class.html.erb
  app/views/spree/admin/variant_guest_card_classes/index.html.erb
  config/routes.rb
  db/migrate/20240820025943_create_spree_cm_commissioner_variant_guest_card_classes.rb
  spec/models/spree/variant_spec.rb
Labels: backend, migration

#1822 Close #1821 Add preferred_background_color and preferred_foreground_color to taxon
  app/controllers/spree/admin/taxons_controller_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/overrides/spree/admin/taxons/_form/background_color_and_foreground_color.html.erb.deface
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20240823081417_add_background_color_and_foreground_color_to_taxon.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: enhancement, backend

#1823 close #1818 add organization to user
  app/models/concerns/spree_cm_commissioner/taxon_kind.rb
  app/views/spree/admin/user_events/_new_user.html.erb
  app/views/spree/admin/user_events/_users.html.erb
Labels: enhancement

#1805 close #1804 import orders service enhancement
  app/controllers/spree/admin/base_import_orders_controller.rb
  app/controllers/spree/admin/import_orders_controller.rb
  app/jobs/spree_cm_commissioner/import_order_job.rb
  app/models/spree_cm_commissioner/import.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/services/spree_cm_commissioner/imports/import_order_service.rb
  app/views/spree/admin/import_existing_orders/_form.html.erb
  app/views/spree/admin/import_existing_orders/index.html.erb
  app/views/spree/admin/import_new_orders/_form.html.erb
  app/views/spree/admin/import_new_orders/index.html.erb
  app/views/spree/admin/import_orders/_form.html.erb
  app/views/spree/admin/import_orders/index.html.erb
  app/views/spree/admin/import_orders/new.html.erb
  config/locales/en.yml
  db/migrate/20240821080044_add_slug_to_spree_cm_commissioner_imports.rb
  spec/services/spree_cm_commissioner/imports/import_order_service_spec.rb
Labels: enhancement

#1827 close #1826 support multiple telegram web bot
  app/controllers/spree/admin/telegram_bots_controller.rb
  app/interactors/spree_cm_commissioner/order_complete_telegram_sender.rb
  app/interactors/spree_cm_commissioner/user_telegram_web_app_authenticator.rb
  app/models/spree_cm_commissioner/telegram_bot.rb
  app/models/spree_cm_commissioner/user_identity_provider.rb
  app/models/spree_cm_commissioner/user_identity_provider_telegram_bot.rb
  app/overrides/spree/admin/shared/sub_menu/_integrations/telegram_bot.html.erb.deface
  app/services/spree_cm_commissioner/user_authenticator.rb
  app/views/spree/admin/telegram_bots/_form.html.erb
  app/views/spree/admin/telegram_bots/edit.html.erb
  app/views/spree/admin/telegram_bots/index.html.erb
  app/views/spree/admin/telegram_bots/new.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20240823093714_create_cm_telegram_bots.rb
  db/migrate/20240823124521_create_cm_user_identity_provider_telegram_bots.rb
  lib/spree_cm_commissioner/test_helper/factories/telegram_bot_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/user_identity_provider_factory.rb
  spec/interactors/spree_cm_commissioner/order_complete_telegram_sender_spec.rb
  spec/interactors/spree_cm_commissioner/user_telegram_web_app_authenticator_spec.rb
  spec/models/spree_cm_commissioner/telegram_bot_spec.rb
  spec/models/spree_cm_commissioner/user_identity_provider_telegram_bot_spec.rb
  spec/queries/spree_cm_commissioner/line_item_searcher_query_spec.rb
  spec/services/spree_cm_commissioner/user_authenticator_spec.rb
Labels: feature

#1830 close #1829 fix telegram incorrect translation & remove unnessary struct
  app/interactors/spree_cm_commissioner/user_telegram_web_app_authenticator.rb
  app/views/spree/admin/telegram_bots/edit.html.erb
  app/views/spree/admin/telegram_bots/index.html.erb
  app/views/spree/admin/telegram_bots/new.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: bug

#1828 close #1815 add age and gender to spree addresses
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20240823035622_add_age_and_gender_to_spree_addresses.rb
Labels: feature

#1782 close #1633 add metafield
  app/controllers/spree/admin/metafields_controller.rb
  app/models/concerns/spree_cm_commissioner/metafield.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/overrides/spree/admin/shared/_product_tabs/metafields.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/services/spree_cm_commissioner/metafields/product_metadata_service.rb
  app/views/spree/admin/metafields/_private_metafields_form.html.erb
  app/views/spree/admin/metafields/_public_metafields_form.html.erb
  app/views/spree/admin/metafields/edit.html.erb
  config/routes.rb
  db/migrate/20240813030608_add_metadata_to_cm_guests.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: feature

#1664 Close #1656 validate longitude and latitude for self check-in
  app/controllers/spree/api/v2/storefront/self_check_in_controller.rb
  config/locales/en.yml
Labels: enhancement, api

#1825 Close #1824 add button after select_tag to update guest card class in dividually
  app/views/spree/admin/variant_guest_card_classes/_variant_guest_card_class.html.erb
  app/views/spree/admin/variant_guest_card_classes/index.html.erb
Labels: enhancement

#1811 close #1810 allow subscription start_date to be in the past
  app/controllers/spree/billing/customers_controller.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
  app/models/spree_cm_commissioner/subscription.rb
  spec/controllers/spree/billing/report_controller_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/queries/spree_cm_commissioner/subscription_orders_query_spec.rb
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
  spec/services/spree_cm_commissioner/penalty_calculator_spec.rb
Labels: bug, backend, billing

#1843 close #1842 fixed customer's promotion adjustment isn't properly caluculated
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
Labels: bug, backend, billing

#1846 close #1840 enhancement order search payment_method with state
  app/models/spree_cm_commissioner/order_decorator.rb
  app/overrides/spree/admin/orders/_search/payment_method_search_field.html.erb.deface
  spec/controllers/spree/billing/report_controller_spec.rb
Labels: backend, XS

#1845 close #1844 add seat mapper option type & its generator tools
  app/interactors/spree_cm_commissioner/bib_number_swapper.rb
  app/models/concerns/spree_cm_commissioner/option_type_attr_type.rb
  app/models/concerns/spree_cm_commissioner/option_value_attr_type.rb
  app/models/concerns/spree_cm_commissioner/variant_options_concern.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/variant_options.rb
  app/serializers/spree_cm_commissioner/v2/operator/guest_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  app/views/spree/admin/option_types/_array_field.html.erb
  app/views/spree/admin/option_types/_option_value_fields.html.erb
  app/views/spree/admin/variants/_option_values.html.erb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20240828080422_add_seat_number_to_cm_guests.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory.rb
  spec/interactors/spree_cm_commissioner/bib_number_swapper_spec.rb
  spec/models/concerns/spree_cm_commissioner/option_value_attr_type_spec.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
  spec/models/spree_cm_commissioner/variant_options_spec.rb
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
  spec/serializers/spree_cm_commissioner/v2/operator/line_item_serializer_spec.rb
  tools/seat_maps/koh_pich_q_solo_concert_seat_map_generator.rb
Labels: feature

#1835 close #1834 telegram bots send message with webhook
  app/controllers/spree/admin/telegram_bots_controller.rb
  app/controllers/spree/api/webhook/telegram_bots_controller.rb
  app/models/spree_cm_commissioner/telegram_bot.rb
  app/views/shared/_asset_field.html.erb
  app/views/spree/admin/telegram_bots/_form.html.erb
  app/views/spree/admin/telegram_bots/edit.html.erb
  config/routes.rb
  db/migrate/20240827084957_add_preferences_and_secure_token_columns_to_cm_telegram_bots.rb
  lib/spree_cm_commissioner/test_helper/factories/telegram_bot_factory.rb
  spec/models/spree_cm_commissioner/telegram_bot_spec.rb
Labels: feature, S

#1855 close #1854 add visible to product taxon
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  app/views/spree/admin/classifications/edit.html.erb
  db/migrate/20240830102144_add_visible_to_spree_products_taxons.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: enhancement

#1860 close #1859 fix wrong stock availability check when there is no booking
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query.rb
  app/services/spree_cm_commissioner/checkout/update_decorator.rb
  spec/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query_spec.rb
Labels: enhancement

#1858 close #1857 add queue to telegram sender
  app/controllers/spree/api/webhook/telegram_bots_controller.rb
  app/interactors/spree_cm_commissioner/telegram_start_message_sender.rb
  app/jobs/spree_cm_commissioner/order_complete_telegram_sender_job.rb
  app/jobs/spree_cm_commissioner/telegram_start_message_sender_job.rb
  spec/cassettes/SpreeCmCommissioner_TelegramStartMessageSender/_call/send_photo_to_chat_id.yml
  spec/interactors/spree_cm_commissioner/telegram_start_message_sender_spec.rb
  spec/jobs/spree_cm_commissioner/telegram_start_message_sender_job_spec.rb
Labels: enhancement

#1862 close #1861 send guest card link to telegram bot user
  app/controllers/spree_cm_commissioner/guest_cards_controller.rb
  app/factory/spree_cm_commissioner/order_telegram_message_factory.rb
  app/interactors/spree_cm_commissioner/order_complete_telegram_sender.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/views/spree_cm_commissioner/guest_cards/show.html.erb
  config/routes.rb
  spec/cassettes/SpreeCmCommissioner_OrderCompleteTelegramSender/_call/when_order_is_associated_with_a_user_user_is_connected_to_Telegram/send_message_to_provider_chat_ID.yml
  spec/cassettes/SpreeCmCommissioner_OrderCompleteTelegramSender/_call/when_order_is_associated_with_a_user_user_is_connected_to_Telegram/send_messs_to_provider_chat_ID.yml
  spec/factory/spree_cm_commissioner/order_telegram_message_factory_spec.rb
  spec/interactors/spree_cm_commissioner/order_complete_telegram_sender_spec.rb
Labels: enhancement

#1865 close #1862 add high demand to variants and line_items
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/overrides/spree/admin/variants/_form/add_high_demand_field.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  db/migrate/20240831141649_add_high_demand_to_spree_variants.rb
  spec/jobs/spree_cm_commissioner/telegram_start_message_sender_job_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: api, XS

#1867 close #1866 improve telegram send message
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/factory/spree_cm_commissioner/order_telegram_message_factory.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
Labels: enhancement
