Repository channainfo/commissioner, pull requests merged in 2024-04, with the labels that each got.

#1267 Close #1266 Taxon selection format change in Customer Billing
  app/controllers/spree/billing/products_controller.rb
  app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/views/spree/billing/customers/_form.html.erb
  app/views/spree/billing/products/_form.html.erb
Labels: backend

#1294 close #1292 add age and emergency contact to kyc
  app/helpers/spree_cm_commissioner/admin/kycable_helper.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  spec/interactors/spree_cm_commissioner/admin/kycable_helper_spec.rb
Labels: feature, XS

#1304 Close #1303 Billing price bug
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/views/spree/billing/shared/_invoice.html.erb
Labels: bug, backend

#1309 close #1308 add backup background color to Line_item mailer
  app/views/spree_cm_commissioner/line_item_mailer/_mailer_stylesheets.html.erb
Labels: backend, XS

#1311 close #1310 undefined method pluralize order notifications
  app/views/spree/admin/orders/notifications.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: bug, XS

#1317 Close #1315 UI and validation change in billing
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/billing/customers/index.html.erb
  app/views/spree/billing/report/active_subscribers.html.erb
  app/views/spree/billing/report/balance_due.html.erb
  app/views/spree/billing/report/failed_orders.html.erb
  app/views/spree/billing/report/overdue.html.erb
  app/views/spree/billing/report/paid.html.erb
  app/views/spree/billing/report/show.html.erb
  config/locales/en.yml
Labels: backend

#1327 close #1326 add line item pricing computer
  app/models/concerns/spree_cm_commissioner/line_item_guests_concern.rb
  app/models/spree_cm_commissioner/pricing_actions/calculate_adjustment.rb
  app/models/spree_cm_commissioner/pricing_rules/base_date.rb
  app/models/spree_cm_commissioner/pricing_rules/custom_dates.rb
  app/models/spree_cm_commissioner/pricing_rules/early_bird.rb
  app/models/spree_cm_commissioner/pricing_rules/extra_adults.rb
  app/models/spree_cm_commissioner/pricing_rules/extra_kids.rb
  app/models/spree_cm_commissioner/pricing_rules/group_booking.rb
  app/models/spree_cm_commissioner/pricing_rules/weekend.rb
  app/models/spree_cm_commissioner/pricings/line_item_pricings_calculator.rb
  app/models/spree_cm_commissioner/pricings/variant_pricing_models_computer.rb
  app/models/spree_cm_commissioner/pricings/variant_pricing_rates_computer.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/pricings/date_options.rb
  lib/spree_cm_commissioner/pricings/guest_options.rb
  lib/spree_cm_commissioner/pricings/options.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_action_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_model_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_rule_factory.rb
  spec/models/spree_cm_commissioner/pricing_actions/calculate_adjustment_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/base_date_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/custom_dates_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/early_bird_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/extra_adults_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/extra_kids_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/group_booking_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/weekend_spec.rb
  spec/models/spree_cm_commissioner/pricings/line_item_pricings_calculator_spec.rb
  spec/models/spree_cm_commissioner/pricings/variant_pricing_models_computer_spec.rb
  spec/models/spree_cm_commissioner/pricings/variant_pricing_rates_computer_spec.rb
Labels: feature, L

#1322 Close #1307 create a wished API for the wishlist
  app/controllers/spree_cm_commissioner/api/v2/storefront/wishlist_controller_decorator.rb
Labels: api, backend

#1331 close #1330 product review api
  Gemfile
  Gemfile.lock
  app/controllers/spree/api/v2/storefront/feedback_reviews_controller.rb
  app/controllers/spree/api/v2/storefront/reviews_controller.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/feedback_review_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/review_serializer.rb
  config/routes.rb
  lib/generators/spree_cm_commissioner/install/install_generator.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/test_helper/factories/review_factory.rb
  spec/request/spree/api/v2/controller/feedback_reviews_controller_spec.rb
  spec/request/spree/api/v2/controller/reviews_controller_spec.rb
Labels: api, M

#1302 Close #1281 Billing invoice not create bug
  app/controllers/spree/billing/invoice_controller.rb
  app/helpers/spree_cm_commissioner/billing/qrcodes_helper.rb
  app/models/spree_cm_commissioner/promotion/rules/fixed_date.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/views/spree/billing/shared/_invoice.html.erb
Labels: bug, backend

#1339 close #1316 refactor for the platform telegram integration
  app/controllers/spree/admin/product_completion_steps_controller.rb
  app/controllers/spree/api/chatrace/base_controller.rb
  app/controllers/spree/api/chatrace/check_ins_controller.rb
  app/controllers/spree/api/chatrace/guests_controller.rb
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/helpers/spree_cm_commissioner/admin/kycable_helper.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/concerns/spree_cm_commissioner/variant_option_values_concern.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/product_completion_step.rb
  app/models/spree_cm_commissioner/product_completion_steps/chatrace_telegram.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/overrides/spree/admin/shared/_product_tabs/product_completion_steps.html.erb.deface
  app/overrides/spree/admin/webhooks_subscribers/index/table.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  app/services/spree_cm_commissioner/cart/add_guest.rb
  app/views/spree/admin/kyc/_form.html.erb
  app/views/spree/admin/product_completion_steps/_form.html.erb
  app/views/spree/admin/product_completion_steps/edit.html.erb
  app/views/spree/admin/product_completion_steps/index.html.erb
  app/views/spree/admin/product_completion_steps/new.html.erb
  config/routes.rb
  db/migrate/20240306071028_add_nationality_data_to_taxons.rb
  db/migrate/20240417085917_enable_pgcrypto.rb
  db/migrate/20240417085929_add_fields_to_cm_guests.rb
  db/migrate/20240422074448_create_cm_product_completion_steps.rb
  lib/spree_cm_commissioner/test_helper/factories/guest_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  lib/spree_cm_commissioner/test_helper/factories/product_completion_step_factory.rb
  spec/interactors/spree_cm_commissioner/admin/kycable_helper_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/variant_spec.rb
  spec/models/spree_cm_commissioner/product_completion_step_spec.rb
  spec/models/spree_cm_commissioner/product_completion_steps/chatrace_telegram_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: feature

#1347 Close #1335 Add button to print all invoices
  app/assets/stylesheets/spree_cm_commissioner/backend/invoice.scss
  app/controllers/spree/billing/report_controller.rb
  app/views/spree/billing/report/balance_due.html.erb
  app/views/spree/billing/shared/_invoice.html.erb
  config/routes.rb
Labels: backend, billing

#1349 close#1346 search trip from stop
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/location_checkbox_manager.js
  app/assets/javascripts/spree_cm_commissioner/trip_stop_selection.js
  app/controllers/concerns/spree_cm_commissioner/transit/taxon_bitwise.rb
  app/controllers/spree/transit/places_controller.rb
  app/controllers/spree/transit/trips_controller.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/trip.rb
  app/models/spree_cm_commissioner/trip_stop.rb
  app/queries/spree_cm_commissioner/trip_search_query.rb
  app/views/spree/transit/places/_form.html.erb
  app/views/spree/transit/trips/_form.html.erb
  db/migrate/20240408033939_create_cm_trip_stops.rb
  lib/spree_cm_commissioner/trip_result.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
Labels: backend, transit

#1359 close #1358 use cdn image for assets url
  app/helpers/spree_cm_commissioner/telegram/base_helper.rb
  app/models/spree_cm_commissioner/asset.rb
  app/overrides/spree/admin/users/_form/profile_pic.html.erb.deface
  app/serializers/spree_cm_commissioner/json_ld/vendor_image_serializer.rb
  app/views/spree/admin/feature_images/_form.html.erb
  app/views/spree/admin/feature_images/index.html.erb
  app/views/spree/admin/homepage_background/_form.html.erb
  app/views/spree/admin/homepage_banner/_form.html.erb
  app/views/spree/admin/homepage_banner/index.html.erb
  app/views/spree/admin/id_cards/_form.html.erb
  app/views/spree/admin/vendor_photos/_form.html.erb
  app/views/spree/admin/vendor_photos/index.html.erb
  app/views/spree/admin/vendors/_form.html.erb
  app/views/spree_cm_commissioner/order_mailer/event/_event_detail.html.erb
Labels: enhancement, S

#1357 Close #1356 fix bug in wished api
  app/controllers/spree/api/v2/storefront/wished_controller.rb
  app/controllers/spree_cm_commissioner/api/v2/storefront/wishlist_controller_decorator.rb
Labels: api

#1361 close #1360 refactor image url to fully constructed url instead of path
  app/models/spree_cm_commissioner/digital_decorator.rb
  app/models/spree_cm_commissioner/icon_decorator.rb
  app/serializers/spree/v2/storefront/line_item_order_serializer.rb
  app/serializers/spree_cm_commissioner/api/v2/platform/digital_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/api/v2/platform/icon_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/icon_serializer_decorator.rb
  spec/models/spree/digital_spec.rb
  spec/models/spree/icon_spec.rb
  spec/serializers/spree/v2/storefront/icon_serializer_spec.rb
Labels: enhancement

#1354 close #1353 add search guest qr-data to line_item_query_searcher
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  lib/spree_cm_commissioner/test_helper/factories/guest_factory.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
Labels: api, M

#1320 close #1313 setup pricing model/rate model migrations
  app/models/concerns/spree_cm_commissioner/line_item_pricings_concern.rb
  app/models/concerns/spree_cm_commissioner/priceable.rb
  app/models/concerns/spree_cm_commissioner/pricing_ruleable.rb
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/models/spree_cm_commissioner/applied_pricing_model.rb
  app/models/spree_cm_commissioner/applied_pricing_rate.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/price_decorator.rb
  app/models/spree_cm_commissioner/pricing_action.rb
  app/models/spree_cm_commissioner/pricing_model.rb
  app/models/spree_cm_commissioner/pricing_rate.rb
  app/models/spree_cm_commissioner/pricing_rule.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  db/migrate/20240317030612_create_spree_cm_commissioner_pricing_rates.rb
  db/migrate/20240317030641_create_spree_cm_commissioner_pricing_models.rb
  db/migrate/20240317030717_create_spree_cm_commissioner_pricing_actions.rb
  db/migrate/20240317030909_create_spree_cm_commissioner_pricing_rules.rb
  db/migrate/20240318092658_add_pricings_columns_to_line_items.rb
  db/migrate/20240318114350_create_spree_cm_commissioner_applied_pricing_models.rb
  db/migrate/20240318114449_create_spree_cm_commissioner_applied_pricing_rates.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_action_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_model_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_rate_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_rule_factory.rb
  spec/models/concerns/spree_cm_commissioner/pricing_ruleable_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/price_spec.rb
  spec/models/spree_cm_commissioner/applied_pricing_model_spec.rb
  spec/models/spree_cm_commissioner/applied_pricing_rate_spec.rb
  spec/models/spree_cm_commissioner/pricing_action_spec.rb
  spec/models/spree_cm_commissioner/pricing_model_spec.rb
  spec/models/spree_cm_commissioner/pricing_rate_spec.rb
  spec/models/spree_cm_commissioner/pricing_rule_spec.rb
Labels: L, migration

#1363 close #1362 fix bug precalculate total_ticket and revenue of product_taxon
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  spec/jobs/spree_cm_commissioner/conversion_pre_calculator_job_spec.rb
Labels: backend, S

#1369 close #1368 add select time from_date to_date in taxon_detail form
  app/overrides/spree/admin/taxons/_form/to_date_form_date.html.erb.deface
Labels: backend, XS

#1257 close #1256 added transit order validation
  app/finders/spree_cm_commissioner/line_items/find_by_variant_decorator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/line_item_seat.rb
  app/models/spree_cm_commissioner/trip.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/queries/spree_cm_commissioner/trip_search_query.rb
  app/views/spree/transit/trips/_form.html.erb
  config/initializers/spree_permitted_attributes.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/order_factory.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/stock/availability_validator_spec.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
  spec/queries/spree_cm_commissioner/trip_seat_layout_query_spec.rb
Labels: backend, transit

#1365 close #1364 get review by product id
  app/controllers/spree/api/v2/storefront/reviews_controller.rb
  config/routes.rb
Labels: api, S
