Repository channainfo/commissioner, pull requests merged in 2024-03, with the labels that each got.

#1182 Close #1181 Add Quantity Field to Cm_Customers
  app/views/spree/billing/customers/_form.html.erb
  app/views/spree/billing/shared/_invoice.html.erb
  config/locales/en.yml
  db/migrate/20240119110257_add_quantity_to_cm_customers.rb
Labels: backend

#1185 close #1167 fix bug telegram bot chat_id nil bad request
  app/interactors/spree_cm_commissioner/telegram_debug_pin_code_sender.rb
  app/interactors/spree_cm_commissioner/telegram_notification_sender.rb
  app/jobs/spree_cm_commissioner/telegram_notification_sender_job.rb
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
  spec/jobs/spree_cm_commissioner/telegram_notification_sender_job_spec.rb
Labels: bug, spec, S

#1184 close #1183 add start end date to taxon
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: api, XS

#1190 close #1188 add nationality to kyc using taxon
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/helpers/spree_cm_commissioner/admin/kycable_helper.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/concerns/spree_cm_commissioner/taxon_kind.rb
  app/models/spree_cm_commissioner/guest.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  app/views/spree/admin/kyc/_form.html.erb
  db/migrate/20240304100236_add_nationality_to_guests.rb
  db/migrate/20240306071028_add_nationality_data_to_taxons.rb
  lib/generators/spree_cm_commissioner/install/install_generator.rb
  lib/generators/spree_cm_commissioner/install/templates/config/data/nationalities.yml
  spec/interactors/spree_cm_commissioner/admin/kycable_helper_spec.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
Labels: feature, S

#1189 close #1168 fix bug sendgrid delivery error Personalizations
  app/mailers/spree/order_mailer_decorator.rb
Labels: bug, M

#1194 close #1169 fix bug noticed delivery_methods response unsuccessful
  app/interactors/spree_cm_commissioner/user_device_token_register.rb
  spec/interactors/spree_cm_commissioner/user_device_token_register_spec.rb
Labels: bug, core, M

#1177 close #1176 update started at attribute type validation format
  app/models/concerns/spree_cm_commissioner/attr_type_validation.rb
  app/models/concerns/spree_cm_commissioner/variant_option_values_concern.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/overrides/spree/admin/option_types/_form/attr_type.html.erb.deface
  app/overrides/spree/admin/option_types/_option_value_fields/option_value_replacer.html.erb.deface
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  config/locales/en.yml
  config/locales/km.yml
  spec/models/concerns/spree_cm_commissioner/attr_type_validation_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: backend, S

#1198 close #1197 readme avoid excessive looping using rails logger stringio object
  README.md
Labels: documentation

#1201 close #1199 filter guest line_item_ids by kyc field for manual check_in
  app/controllers/spree/api/v2/operator/line_items_controller.rb
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  config/routes.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
Labels: api, M

#1187 Close #1186 Trip Seats Layout Query
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/trip.rb
  app/models/spree_cm_commissioner/vehicle.rb
  app/queries/spree_cm_commissioner/trip_search_query.rb
  app/queries/spree_cm_commissioner/trip_seat_layout_query.rb
  db/migrate/20240222041403_add_vehicle_id_to_products.rb
  db/migrate/20240229043606_add_date_and_variant_id_to_cm_line_item_seats.rb
  db/migrate/20240307080330_create_cm_trips.rb
  db/migrate/20240313044245_add_origin_destination_index_to_cm_trips.rb
  db/migrate/20240313044455_remove_origin_destintaion_vehicle_from_product.rb
  db/migrate/20240313080154_add_vehicle_type_id_index_to_cm_vehicle_seats.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_seat_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/order_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/vehicle_type_factory.rb
  lib/spree_cm_commissioner/trip_result.rb
  lib/spree_cm_commissioner/trip_seat_layout_result.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
  spec/queries/spree_cm_commissioner/trip_seat_layout_query_spec.rb
Labels: backend, transit

#1214 close #1208 add seat selection availability flag on route
  app/queries/spree_cm_commissioner/trip_seat_layout_query.rb
  db/migrate/20240314035607_add_allow_seat_selection_to_cm_trips.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/order_factory.rb
  lib/spree_cm_commissioner/trip_seat_layout_result.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
  spec/queries/spree_cm_commissioner/trip_seat_layout_query_spec.rb
Labels: backend, transit

#1210 Close #1193 Account name and number validation error
  app/models/spree_cm_commissioner/vendor_decorator.rb
  config/locales/en.yml
Labels: backend, billing

#1212 Close #1207 change fields validation and fields labels in billing
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/billing/customers/_form.html.erb
  app/views/spree/billing/customers/index.html.erb
  config/locales/en.yml
Labels: backend, billing

#1219 close #1215 allow user to input actual guests & validate extra guests
  app/models/concerns/spree_cm_commissioner/line_item_guests_concern.rb
  app/models/concerns/spree_cm_commissioner/variant_guests_concern.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/variant_spec.rb
Labels: enhancement, S

#1218 close #1217 filtered seats for order that is completed
  app/queries/spree_cm_commissioner/trip_search_query.rb
  app/queries/spree_cm_commissioner/trip_seat_layout_query.rb
  lib/spree_cm_commissioner/test_helper/factories/order_factory.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
  spec/queries/spree_cm_commissioner/trip_seat_layout_query_spec.rb
Labels: backend, transit

#1226 close #1225 a dd Note: Subtitle is used as country code for nationality taxon
  app/overrides/spree/admin/taxons/_form/sub_title.html.erb.deface
  config/locales/en.yml
Labels: enhancement, XS

#1209 close #1206 enchencement check_ins manual searcher support app auto complete
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  app/serializers/spree_cm_commissioner/v2/operator/line_item_order_serializer.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
Labels: enhancement, api, M

#1228 close #1227 added allow seat selection on vehicle_type
  app/controllers/spree/transit/places_controller.rb
  app/controllers/spree/transit/vehicle_types_controller.rb
  app/models/spree_cm_commissioner/vehicle_seat.rb
  app/models/spree_cm_commissioner/vehicle_type.rb
  app/views/spree/transit/vehicle_types/_form.html.erb
  db/migrate/20240318080243_add_allow_seat_selection_to_cm_vehicle_types.rb
Labels: backend, transit

#1196 close #1195 export guest data to csv
  app/controllers/spree/events/guests_controller.rb
  app/interactors/spree_cm_commissioner/generate_guests_csv.rb
  app/views/spree/events/guests/index.html.erb
  app/views/spree/events/shared/_filters.html.erb
  spec/interactors/spree_cm_commissioner/generate_guests_csv_spec.rb
Labels: feature, S

#1220 close #1213 creat qr code for line_items and scan line_item_qr
  app/controllers/spree/api/v2/storefront/line_item_qrs_controller.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  config/routes.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
Labels: api, M

#1243 close #1241 add default adults for variant
  app/models/concerns/spree_cm_commissioner/variant_guests_concern.rb
  spec/models/spree/variant_spec.rb
Labels: enhancement, S

#1238 close #1237 add hidden field to option type serializer
  app/serializers/spree/v2/storefront/option_type_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/option_type_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: api, XS

#1248 close #1246 enchance pie_chart api and fix bug in pie_chart_dashboard screen
  app/queries/spree_cm_commissioner/pie_chart_event_aggregator_queries.rb
  app/serializables/spree_cm_commissioner/pie_chart_event_aggregator.rb
  app/serializers/spree_cm_commissioner/v2/operator/pie_chart_event_aggregator_serializer.rb
Labels: api, S

#1252 close #1249 rafactor: remove cache from ticket qr controller
  app/controllers/spree/api/v2/operator/line_items_controller.rb
Labels: enhancement, XS

#1253 close #1250 add line_items to guest_serializer
  app/serializers/spree_cm_commissioner/v2/operator/guest_serializer.rb
Labels: enhancement, XS

#1254 close #1251 refactor: only filter complete order guest
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
Labels: enhancement, XS

#1262 close #1261 enchance select forms field in taxonomy
  app/overrides/spree/admin/taxons/_form/sub_title.html.erb.deface
  app/views/spree/admin/classifications/edit.html.erb
  app/views/spree/admin/classifications/new.html.erb
  app/views/spree/admin/user_taxons/_form.html.erb
Labels: enhancement, XS

#1263 close #1255 add manual check in organizer dashboard
  app/controllers/spree/events/check_ins_controller.rb
  app/controllers/spree/events/guests_controller.rb
  app/helpers/spree_cm_commissioner/admin/guest_helper.rb
  app/views/spree/events/check_ins/index.html.erb
  app/views/spree/events/guests/_form.html.erb
  app/views/spree/events/guests/edit.html.erb
  app/views/spree/events/guests/index.html.erb
  app/views/spree/events/shared/_main_menu.html.erb
  app/views/spree/layouts/event.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: enhancement, M

#1260 close #1259 add rake task to ensure event id present for guests
  app/jobs/spree_cm_commissioner/ensure_event_id_for_guests_job.rb
  app/models/spree_cm_commissioner/guest.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  lib/tasks/ensure_event_for_guests.rake
  spec/jobs/spree_cm_commissioner/ensure_event_id_for_guests_job_spec.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
Labels: S

#1265 close #1264 refactor check-in organizer dashboard
  app/controllers/spree/events/guests_controller.rb
  app/views/spree/events/check_ins/index.html.erb
  app/views/spree/events/guests/_check_in_status.html.erb
  app/views/spree/events/guests/edit.html.erb
  app/views/spree/events/guests/index.html.erb
  app/views/spree/events/shared/_filters.html.erb
  app/views/spree/events/shared/_main_menu.html.erb
  app/views/spree/layouts/event.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: enhancement, XS

#1270 close #1269 create recalculate in event product
  app/controllers/spree/admin/classifications_controller.rb
  app/views/spree/admin/classifications/index.html.erb
  app/views/spree/admin/shared/_products.html.erb
  config/routes.rb
Labels: backend, S

#1235 close #1232 data entry and send email guest
  app/controllers/spree/events/guests_controller.rb
  app/controllers/spree_cm_commissioner/line_item_qr_images_controller.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/views/spree/events/guests/_form.html.erb
  app/views/spree/events/guests/edit.html.erb
  app/views/spree/events/shared/_event_switcher.html.erb
  app/views/spree/order_mailer/ticket_email.html.erb
  app/views/spree/order_mailer/ticket_email.text.erb
  app/views/spree_cm_commissioner/line_item_mailer/_greeting.html.erb
  config/routes.rb
Labels: backend, L

#1274 close #1272 create check_in and uncheck_in with state changes
  app/controllers/spree/events/guests_controller.rb
  app/controllers/spree/events/state_changes_controller.rb
  app/interactors/spree_cm_commissioner/check_in_bulk_creator.rb
  app/interactors/spree_cm_commissioner/check_in_destroyer.rb
  app/models/spree_cm_commissioner/guest.rb
  app/views/spree/events/guests/_check_in_status.html.erb
  app/views/spree/events/guests/edit.html.erb
  app/views/spree/events/shared/_guest_tabs.html.erb
  app/views/spree/events/state_changes/index.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  spec/interactors/spree_cm_commissioner/check_in_destroyer_spec.rb
Labels: backend, M

#1279 close #1278 change line_item-mailer back ground image
  app/assets/images/mailer/line_item-mailer-bg.png
  app/mailers/spree/order_mailer_decorator.rb
  app/views/spree_cm_commissioner/layouts/line_item_mailer.html.erb
  app/views/spree_cm_commissioner/line_item_mailer/_mailer_stylesheets.html.erb
Labels: enhancement, XS

#1273 close #1271 fix authorization organizer dashboard
  app/controllers/concerns/spree_cm_commissioner/events/role_authorization.rb
  app/controllers/spree/events/base_controller.rb
  app/controllers/spree/events/errors_controller.rb
  app/controllers/spree/events/guests_controller.rb
  app/controllers/spree_cm_commissioner/application_controller_decorator.rb
  app/errors/spree_cm_commissioner/unauthorized_event_error.rb
  app/views/spree/events/errors/_error.html.erb
  app/views/spree/events/errors/forbidden.html.erb
  app/views/spree/events/errors/resource_not_found.html.erb
  config/routes.rb
Labels: bug, enhancement, XS

#1284 close #1283 fix organizer dashboard url bug
  app/views/spree/events/shared/_guest_tabs.html.erb
Labels: bug, XS

#1285 close #1282 fixed deleting taxon and product bug
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
Labels: backend, billing

#1287 close #1286 reassign event id for guest when assigned wrong
  app/jobs/spree_cm_commissioner/ensure_event_id_for_guests_job.rb
  spec/jobs/spree_cm_commissioner/ensure_event_id_for_guests_job_spec.rb
Labels: bug, hotfix
