Repository channainfo/commissioner, pull requests merged in 2024-06, with the labels that each got.

#1473 close #1462 manually create new invoice
  Gemfile
  Gemfile.lock
  app/controllers/spree/billing/customers_controller.rb
  app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
  app/models/spree_cm_commissioner/customer.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/subscription.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/views/spree/billing/customers/index.html.erb
  app/views/spree/billing/orders/_line_item.html.erb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/shared/_customer_tabs.html.erb
  app/views/spree/billing/shared/_main_menu.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
Labels: backend, billing

#1480 close #1472 disable inventory tracking for subscribable product
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/views/spree/billing/places/index.html.erb
  app/views/spree/billing/products/_form.html.erb
  app/views/spree/billing/reports/_overview.html.erb
  app/views/spree/billing/shared/_order_tabs.html.erb
Labels: backend, billing

#1487 close #1486 override stock availability with real time check with existing orders
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/stock/availability_checker.rb
  app/models/spree_cm_commissioner/stock/availability_validator_decorator.rb
  app/models/spree_cm_commissioner/stock/line_item_availability_checker.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query.rb
  app/queries/spree_cm_commissioner/variant_availability/permanent_stock_query.rb
  spec/models/spree/stock/availability_validator_spec.rb
  spec/models/spree_cm_commissioner/stock/availability_checker_spec.rb
  spec/models/spree_cm_commissioner/stock/line_item_availability_checker_spec.rb
  spec/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query_spec.rb
  spec/queries/spree_cm_commissioner/variant_availability/permanent_stock_query_spec.rb
Labels: enhancement

#1489 close #1488 replace stock management UI
  app/controllers/spree/admin/stock_managements_controller.rb
  app/overrides/spree/admin/shared/_product_tabs/stock_managements.html.erb.deface
  app/views/spree/admin/stock_managements/_variant_stock_items.html.erb
  app/views/spree/admin/stock_managements/index.html.erb
  config/routes.rb
Labels: backend

#1482 Close #1475 Allow to select date in new subscription
  app/views/spree/billing/subscriptions/_form.html.erb
Labels: backend, billing

#1493 Close #1484 Monthly filtering invoices
  app/controllers/spree/billing/orders_controller.rb
  app/views/spree/billing/orders/_search.html.erb
Labels: backend, billing

#1495 close #1492 fixed adjustment negative amount
  app/controllers/spree/billing/adjustments_controller.rb
  app/models/spree_cm_commissioner/adjustment_decorator.rb
  app/overrides/spree/admin/shared/_order_summary/adjustment_total.html.erb.deface
  app/views/spree/billing/adjustments/_adjustment.html.erb
  app/views/spree/billing/shared/_invoice.html.erb
Labels: backend, billing

#1483 Close #1481 Change customer validation in Billing
  app/controllers/spree/billing/customers_controller.rb
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/billing/shared/_order_tabs.html.erb
  config/locales/en.yml
Labels: backend, billing

#1497 Close #1496 Fix order duplication bug in report page
  app/controllers/spree/billing/reports_controller.rb
  app/queries/spree_cm_commissioner/subscription_revenue_overview_query.rb
Labels: backend, billing

#1491 close #1490 add otp_enabled, otp_email, otp_phone_number to user perm…
  app/models/spree_cm_commissioner/user_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20240521040143_add_opt_fields_to_spree_user.rb
  spec/models/spree_cm_commissioner/user_spec.rb
Labels: XS

#1332 close #1326 add line item pricing rate/model computer
  app/models/concerns/spree_cm_commissioner/line_item_guests_concern.rb
  app/models/spree_cm_commissioner/pricing_actions/calculate_adjustment.rb
  app/models/spree_cm_commissioner/pricing_rules/base_date.rb
  app/models/spree_cm_commissioner/pricing_rules/custom_dates.rb
  app/models/spree_cm_commissioner/pricing_rules/early_bird.rb
  app/models/spree_cm_commissioner/pricing_rules/extra_adults.rb
  app/models/spree_cm_commissioner/pricing_rules/extra_kids.rb
  app/models/spree_cm_commissioner/pricing_rules/group_booking.rb
  app/models/spree_cm_commissioner/pricing_rules/weekend.rb
  app/models/spree_cm_commissioner/pricings/line_item_pricings_calculator.rb
  app/models/spree_cm_commissioner/pricings/variant_pricing_models_computer.rb
  app/models/spree_cm_commissioner/pricings/variant_pricing_rates_computer.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/pricings/date_options.rb
  lib/spree_cm_commissioner/pricings/guest_options.rb
  lib/spree_cm_commissioner/pricings/options.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_action_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_model_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/pricing_rule_factory.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree_cm_commissioner/pricing_actions/calculate_adjustment_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/base_date_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/custom_dates_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/early_bird_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/extra_adults_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/extra_kids_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/group_booking_spec.rb
  spec/models/spree_cm_commissioner/pricing_rules/weekend_spec.rb
  spec/models/spree_cm_commissioner/pricings/line_item_pricings_calculator/non_reservation_usecases_spec.rb
  spec/models/spree_cm_commissioner/pricings/line_item_pricings_calculator/reservation_usecases_spec.rb
  spec/models/spree_cm_commissioner/pricings/line_item_pricings_calculator_spec.rb
  spec/models/spree_cm_commissioner/pricings/variant_pricing_models_computer_spec.rb
  spec/models/spree_cm_commissioner/pricings/variant_pricing_rates_computer_spec.rb
  spec/support/guest_options_helper.rb
Labels: feature, L

#1386 close #1385 pricing rate admin interface
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/select_field_auto_filter.js
  app/controllers/spree/admin/pricing_rates_controller.rb
  app/controllers/spree/admin/pricing_rules_controller.rb
  app/models/concerns/spree_cm_commissioner/pricing_ruleable.rb
  app/models/spree_cm_commissioner/pricing_rate.rb
  app/models/spree_cm_commissioner/pricing_rules/custom_dates.rb
  app/models/spree_cm_commissioner/pricing_rules/early_bird.rb
  app/overrides/spree/admin/shared/_product_tabs/pricing_rates.html.erb.deface
  app/views/spree/admin/pricing_rates/_form.html.erb
  app/views/spree/admin/pricing_rates/_pricing_rates.html.erb
  app/views/spree/admin/pricing_rates/edit.html.erb
  app/views/spree/admin/pricing_rates/index.html.erb
  app/views/spree/admin/pricing_rates/new.html.erb
  app/views/spree/admin/pricing_rules/index.html.erb
  app/views/spree/admin/shared/_pricing_rate_sidebar.html.erb
  app/views/spree_cm_commissioner/pricing_rules/_custom_dates.html.erb
  app/views/spree_cm_commissioner/pricing_rules/_early_bird.html.erb
  app/views/spree_cm_commissioner/pricing_rules/_extra_adults.html.erb
  app/views/spree_cm_commissioner/pricing_rules/_extra_kids.html.erb
  app/views/spree_cm_commissioner/pricing_rules/_group_booking.html.erb
  app/views/spree_cm_commissioner/pricing_rules/_weekend.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  lib/generators/spree_cm_commissioner/install/templates/app/javascript/spree_cm_commissioner/utilities.js
Labels: backend, L

#1388 close #1387 pricing model admin interface
  app/controllers/spree/admin/pricing_actions_controller.rb
  app/controllers/spree/admin/pricing_models_controller.rb
  app/models/spree_cm_commissioner/pricing_actions/calculate_adjustment.rb
  app/models/spree_cm_commissioner/pricing_model.rb
  app/models/spree_cm_commissioner/pricing_rules/weekend.rb
  app/overrides/spree/admin/shared/_product_tabs/pricing_models.html.erb.deface
  app/views/spree/admin/pricing_models/_form.html.erb
  app/views/spree/admin/pricing_models/_pricing_actions.html.erb
  app/views/spree/admin/pricing_models/_pricing_models.html.erb
  app/views/spree/admin/pricing_models/edit.html.erb
  app/views/spree/admin/pricing_models/index.html.erb
  app/views/spree/admin/pricing_models/new.html.erb
  app/views/spree/admin/pricing_rules/index.html.erb
  app/views/spree/admin/shared/_pricing_model_sidebar.html.erb
  app/views/spree_cm_commissioner/pricing_actions/_calculate_adjustment.html.erb
  config/routes.rb
Labels: backend, L

#1511 close #1510 deprecate variant permanent_stock
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/stock_item_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/overrides/spree/admin/variants/_form/add_permanent_stock.html.erb.deface
  app/overrides/spree/admin/variants/index/permanent_stock.html.erb.deface
  app/overrides/spree/admin/variants/index/variants_header.html.erb.deface
  app/queries/spree_cm_commissioner/reservation_variant_quantity_availability_query.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/stock_item_serializer.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/variant_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_factory.rb
  spec/interactors/spree_cm_commissioner/accommodation_search_detail_spec.rb
  spec/interactors/spree_cm_commissioner/order_accepted_state_updater_spec.rb
  spec/interactors/spree_cm_commissioner/order_rejected_state_updater_spec.rb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/vendor_updater_spec.rb
  spec/models/concerns/spree_cm_commissioner/option_value_attr_type_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/vendor_spec.rb
  spec/models/spree_cm_commissioner/promotion/actions/create_date_specific_item_adjustments_spec.rb
  spec/queries/spree_cm_commissioner/accommodation_query_spec.rb
  spec/queries/spree_cm_commissioner/reservation_variant_quantity_availability_query_spec.rb
  spec/request/spree/api/v2/accommodations_spec.rb
  spec/request/spree/api/v2/nearby_places_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: enhancement, S

#1514 close #1513 update variant vendor_id when product vendor_id updated
  app/assets/javascripts/spree_cm_commissioner/report_hide_filter.js
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  spec/models/spree/product_spec.rb
Labels: bug, S

#1507 close #1506 add send_at and unique job to customer notificaion
  app/interactors/spree_cm_commissioner/customer_notification_sender.rb
  app/views/spree/admin/customer_notifications/index.html.erb
  spec/interactors/spree_cm_commissioner/customer_notification_sender_spec.rb
  spec/interactors/spree_cm_commissioner/notification_send_creator_spec.rb
Labels: enhancement, M

#1503 close #1502 add encrypted_confirm_pin_code attribute to spree_users
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20240604015854_add_encrypted_confirm_pin_code_to_spree_users.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
Labels: XS

#1515 close #1471 add video upload field to S3
  app/controllers/spree/admin/video_on_demands_controller.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/video_on_demand.rb
  app/overrides/spree/admin/shared/_product_tabs/video_on_demand.html.erb.deface
  app/views/spree/admin/video_on_demands/_form.html.erb
  app/views/spree/admin/video_on_demands/edit.html.erb
  app/views/spree/admin/video_on_demands/index.html.erb
  app/views/spree/admin/video_on_demands/new.html.erb
  config/routes.rb
  db/migrate/20240531074327_create_cm_video_on_demands.rb
Labels: backend, L

#1457 close #1442 create event ticket object
  app/controllers/spree/api/v2/storefront/google_wallet_object_tokens_controller.rb
  app/models/spree_cm_commissioner/google_wallet.rb
  app/models/spree_cm_commissioner/google_wallet_hero.rb
  app/models/spree_cm_commissioner/google_wallet_logo.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/product_google_wallet.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/google_wallet_serializer.rb
  app/services/spree_cm_commissioner/google_wallets/base_object_builder.rb
  app/services/spree_cm_commissioner/google_wallets/event_ticket_object_builder.rb
  config/routes.rb
  db/migrate/20240528020329_create_cm_google_wallets.rb
  db/migrate/20240529101637_add_number_to_spree_line_items.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: feature, M

#1499 close #1498 manage google wallet class
  app/controllers/spree/admin/google_wallets_controller.rb
  app/helpers/spree/admin/base_helper_decorator.rb
  app/models/spree_cm_commissioner/event_ticket_google_wallet.rb
  app/models/spree_cm_commissioner/google_wallet.rb
  app/overrides/spree/admin/shared/_product_tabs/google_wallet_html.erb.deface
  app/views/spree/admin/google_wallets/_form.html.erb
  app/views/spree/admin/google_wallets/edit.html.erb
  app/views/spree/admin/google_wallets/new.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: backend, M

#1526 close #1525 create notificaion tabs in customer notification
  app/controllers/spree/admin/notifications_controller.rb
  app/models/spree_cm_commissioner/customer_notification.rb
  app/views/spree/admin/notifications/index.html.erb
  app/views/spree/admin/shared/_customer_notification_tabs.html.erb
  config/routes.rb
Labels: backend, M

#1477 Close #1476 filter wishlists by variant id
  app/controllers/spree/api/v2/storefront/wishlists_controller_decorator.rb
  app/serializers/spree/v2/storefront/wished_item_serializer_decorator.rb
  spec/controllers/spree/api/v2/storefront/wishlists_controller_decorator_spec.rb
Labels: enhancement

#1530 close #1529 preference fields are missing
  app/helpers/spree/admin/base_helper_decorator.rb
Labels: bug

#1539 Close #1538 add wished_item to UserMethods through wishlist
  app/controllers/spree/api/v2/storefront/wished_items_controller.rb
  app/models/spree_cm_commissioner/user_methods_decorator.rb
Labels: bug

#1543 Close #1542 Small update about add wishedItem to user through wishlist
  app/models/spree_cm_commissioner/user_decorator.rb
  app/models/spree_cm_commissioner/user_methods_decorator.rb
Labels: enhancement

#1541 close #1540 added current invoice indicator
  app/controllers/spree/billing/base_controller.rb
  app/controllers/spree/billing/orders_controller.rb
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/billing/customers/index.html.erb
  app/views/spree/billing/orders/_line_item.html.erb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/products/index.html.erb
  config/locales/en.yml
Labels: backend, billing

#1532 close #1531 improve notification admin
  app/controllers/spree/admin/customer_notifications_controller.rb
  app/controllers/spree/admin/notifications_controller.rb
  app/models/spree_cm_commissioner/customer_notification.rb
  app/serializers/spree/v2/storefront/customer_notification_serializer.rb
  app/views/spree/admin/customer_notifications/_form.html.erb
  app/views/spree/admin/notifications/index.html.erb
  db/migrate/20240617092542_remove_send_all_from_cm_customer_notifications.rb
  db/migrate/20240617093442_add_action_label_to_cm_customer_notifications.rb
  spec/serializers/spree/v2/storefront/customer_notification_serializer_spec.rb
Labels: enhancement

#1504 close #1501 google wallet class api
  app/controllers/spree/admin/google_wallets_controller.rb
  app/controllers/spree/api/v2/storefront/google_wallet_object_tokens_controller.rb
  app/models/spree_cm_commissioner/google_wallet.rb
  app/services/spree_cm_commissioner/google_wallets/base_event_ticket_class.rb
  app/services/spree_cm_commissioner/google_wallets/event_ticket_class_creator.rb
  app/services/spree_cm_commissioner/google_wallets/event_ticket_class_updater.rb
  app/views/spree/admin/google_wallets/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  lib/spree_cm_commissioner/test_helper/factories/image_factory.rb
  spec/services/spree_cm_commissioner/google_wallets/base_event_ticket_class_spec.rb
Labels: api, backend, M

#1517 close #1516 added invoice and order recurring
  app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
  db/migrate/20240605104235_add_last_invoice_date_to_cm_customers.rb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
Labels: backend, billing

#1548 close #1547 fix option values can't be reorder
  app/overrides/spree/admin/option_types/edit/option_header_replacer.html.erb.deface
Labels: bug

#1550 close #1549 manaully check stock for deliverable product
  app/models/spree_cm_commissioner/stock/availability_checker.rb
  spec/models/spree_cm_commissioner/stock/availability_checker_spec.rb
Labels: enhancement

#1553 close #1552 generate number for line item
  app/models/spree_cm_commissioner/line_item_decorator.rb
  lib/tasks/ensure_number_for_line_items.rake
  spec/models/spree/line_item_spec.rb
Labels: enhancement

#1557 close #1460 add self check-in feature
  app/controllers/spree/api/v2/operator/event_qrs_controller.rb
  app/controllers/spree/api/v2/operator/taxons_controller.rb
  app/controllers/spree/api/v2/storefront/self_check_in_controller.rb
  app/interactors/spree_cm_commissioner/event_qr_generator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/operator/dashboard_crew_event_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/event_qr_serializer.rb
  app/serializers/spree_cm_commissioner/v2/storefront/self_check_in_serializer.rb
  config/routes.rb
  db/migrate/20240607061230_add_secure_token_field_to_user.rb
  spec/interactors/spree_cm_commissioner/event_qr_generator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: enhancement

#1560 close #1559 make sure events query more accurate
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  app/queries/spree_cm_commissioner/dashboard_crew_event_query.rb
  app/serializers/spree/v2/storefront/cart_serializer_decorator.rb
  app/views/spree/admin/line_items/_form.html.erb
  spec/models/spree/line_item_spec.rb
  spec/queries/spree_cm_commissioner/dashboard_crew_event_query_spec.rb
  spec/serializers/spree/v2/storefront/cart_serializer_spec.rb
Labels: enhancement

#1570 Close #1569 add before action of spree current user to wishedItem
  app/controllers/spree/api/v2/storefront/wished_items_controller.rb
Labels: bug

#1580 close #1579 google wallet class enhancement
  app/helpers/spree/admin/base_helper_decorator.rb
  app/models/spree_cm_commissioner/event_ticket_google_wallet.rb
  app/services/spree_cm_commissioner/google_wallets/base_event_ticket_class.rb
Labels: enhancement, backend
