Repository channainfo/commissioner, pull requests merged in 2024-09, with the labels that each got.

#1872 close #1871 create job update gateway status
  app/interactors/spree_cm_commissioner/update_payment_gateway_status.rb
  app/overrides/spree/admin/payments/_list/add_gateway_status_to_list_head.html.erb.deface
  app/overrides/spree/admin/payments/_list/add_gateway_status_to_list_row.html.erb.deface
  db/migrate/20240901092548_add_gateway_status_to_spree_payments.rb
  lib/tasks/update_gateway_status.rake
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
Labels: system

#1886 close #1885 move payment gateway status table column to spree_vpago
  app/overrides/spree/admin/payments/_list/add_gateway_status_to_list_head.html.erb.deface
  app/overrides/spree/admin/payments/_list/add_gateway_status_to_list_row.html.erb.deface
Labels: backend

#1889 close #1888 add update order status button
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/overrides/spree/admin/shared/_order_summary/order_status.html.erb.deface
  config/locales/en.yml
  config/routes.rb
Labels: backend

#1882 close #1881 add uniq guest seat_number and spec model
  app/assets/javascripts/spree_cm_commissioner/routes.js
  app/controllers/spree/admin/guests_controller.rb
  app/controllers/spree/api/v2/platform/seat_number_layouts_controller.rb
  app/models/concerns/spree_cm_commissioner/option_value_attr_type.rb
  app/models/concerns/spree_cm_commissioner/variant_options_concern.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/variant_options.rb
  app/serializers/spree_cm_commissioner/api/v2/platform/seat_number_layouts_serializer.rb
  app/views/spree/admin/guests/_form.html.erb
  app/views/spree/admin/guests/_table.html.erb
  app/views/spree/admin/guests/index.html.erb
  app/views/spree/admin/option_types/_array_field.html.erb
  config/routes.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
Labels: enhancement

#1895 close #1894 add phone number to order
  app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/overrides/spree/admin/orders/customer_details/_form/phone_number_field.html.erb.deface
  spec/models/spree/order_spec.rb
Labels: enhancement

#1902 close #1901 create update_taxons task and remove unnecessary attribute
  app/controllers/spree/admin/taxons_controller_decorator.rb
  lib/tasks/update_taxons.rake
Labels: bug

#1899 Close #1898 Add event status to taxon
  app/overrides/spree/admin/taxons/_form/event_status.html.erb.deface
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20240907061117_add_show_event_status_to_spree_taxon.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: backend

#1916 close #1911 add guest individual search with seat_number and phone_number
  app/models/spree_cm_commissioner/guest.rb
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  app/serializers/spree_cm_commissioner/v2/operator/guest_serializer.rb
  db/migrate/20240909080722_add_phone_number_to_spree_cm_commissioner_guest.rb
  spec/serializers/spree_cm_commissioner/v2/operator/line_item_serializer_spec.rb
Labels: api, XS

#1918 close #1917 allow app storefront scan guest Qr code to get information
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  db/migrate/20240909114051_add_index_to_token_in_cm_guests.rb
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
Labels: api, XS

#1913 close #1912 added vendor penalty rate
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/billing/vendors/_form.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: backend, billing

#1760 Close #1756 Billing report use_custom_date_range bug
  app/assets/javascripts/spree_cm_commissioner/report_hide_filter.js
  app/controllers/spree/billing/reports_controller.rb
  app/views/spree/billing/reports/_date_range_picker.html.erb
Labels: bug, backend, billing

#1922 close #1921 add operator guests API for individual check in
  app/controllers/spree/api/v2/operator/guests_controller.rb
  app/interactors/spree_cm_commissioner/check_in_bulk_creator.rb
  app/queries/spree_cm_commissioner/guest_searcher_query.rb
  app/serializers/spree_cm_commissioner/v2/operator/line_item_order_serializer.rb
  config/routes.rb
  spec/serializers/spree_cm_commissioner/v2/operator/line_item_serializer_spec.rb
Labels: enhancement, api

#1929 close #1928 remove unnesscesasry space from csv data
  app/controllers/spree/admin/guests_controller.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/spree_cm_commissioner/guest.rb
  app/services/spree_cm_commissioner/imports/base_import_order_service.rb
  app/services/spree_cm_commissioner/imports/update_order_service.rb
  app/views/spree/admin/guests/_form.html.erb
  spec/services/spree_cm_commissioner/imports/update_order_service_spec.rb
Labels: enhancement, backend

#1925 close #1924 enchance guest_card qr render with js
  app/controllers/spree/api/v2/storefront/qr_urls_controller.rb
  app/controllers/spree_cm_commissioner/guest_cards_controller.rb
  app/serializers/spree_cm_commissioner/v2/storefront/qr_url_serializer.rb
  app/views/spree_cm_commissioner/guest_cards/show.html.erb
  config/routes.rb
Labels: release

#1933 close #1932 fix bug guest_card and return cancel order when check in
  app/controllers/spree_cm_commissioner/guest_cards_controller.rb
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/queries/spree_cm_commissioner/guest_searcher_query.rb
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  app/views/spree_cm_commissioner/guest_cards/show.html.erb
Labels: enhancement

#1908 close #1906 added customer deactivation
  app/models/spree_cm_commissioner/customer.rb
  app/views/spree/billing/customers/_form.html.erb
  app/views/spree/billing/customers/index.html.erb
  db/migrate/20240909051440_add_status_to_cm_customers.rb
Labels: backend, billing

#1927 close #1926 add last invoice remaining to current invoice total as adjustment
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/views/spree/billing/vendors/_form.html.erb
  config/locales/en.yml
  lib/spree_cm_commissioner/test_helper/factories/subscription_factory.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
Labels: backend, billing

#1910 close #1909 query for active customer for invoice recurring only
  app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
  app/models/spree_cm_commissioner/customer.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
Labels: backend, billing

#1873 Close #1736 Billing export report to csv
  app/assets/javascripts/spree_cm_commissioner/report_hide_filter.js
  app/controllers/spree/billing/reports_controller.rb
  app/controllers/spree/billing/roles_controller.rb
  app/queries/spree_cm_commissioner/subscription_orders_query.rb
  app/services/spree_cm_commissioner/exports/export_order_csv_service.rb
  app/views/spree/billing/reports/_date_range_picker.html.erb
  app/views/spree/billing/reports/export.html.erb
  app/views/spree/billing/reports/index.html.erb
  app/views/spree/billing/shared/sub_menu/_report.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/queries/spree_cm_commissioner/subscription_orders_query_spec.rb
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
Labels: backend, billing

#1914 Close #1890 billing add place filter to export and report page
  app/controllers/spree/billing/reports_controller.rb
  app/services/spree_cm_commissioner/exports/export_order_csv_service.rb
  app/views/spree/billing/reports/_date_range_picker.html.erb
  app/views/spree/billing/reports/export.html.erb
  config/locales/en.yml
Labels: backend, billing

#1915 Close #1891 billing add place name to csv file
  app/controllers/spree/billing/reports_controller.rb
  app/services/spree_cm_commissioner/exports/export_order_csv_service.rb
  app/views/spree/billing/reports/balance_due.html.erb
Labels: backend, billing

#1967 Close #1965 make docker a more development-friendly
  Dockerfile
  README.md
  docker-compose.yml
  spec/spec_helper.rb
Labels: backend, docker

#1976 close #1975 Fix kyc resource not found
  app/controllers/spree/api/v2/storefront/guests_controller.rb
Labels: bug, S
