Repository channainfo/commissioner, pull requests merged in 2024-12, with the labels that each got.

#1586 close #1585 add vendor stop
  app/models/spree_cm_commissioner/service_calendar.rb
  app/models/spree_cm_commissioner/trip.rb
  app/models/spree_cm_commissioner/trip_stop.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/models/spree_cm_commissioner/vendor_stop.rb
  db/migrate/20240626073702_create_cm_vendor_stops.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  spec/models/spree_cm_commissioner/trip_stop_spec.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: backend, transit

#2104 close #2103 add check_in and uncheck_in to admin order_guest
  app/controllers/spree/admin/guests_controller.rb
  app/views/spree/admin/guests/_check_in_status.html.erb
  app/views/spree/admin/guests/edit.html.erb
  config/routes.rb
Labels: backend, XS

#2065 Close #2064 Billing balance due popup confirmation tab js not load
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/update_popup_confirmation.js
  app/views/spree/billing/reports/balance_due.html.erb
  app/views/spree/billing/shared/_pop_up_confirmation.html.erb
Labels: backend, billing

#1980 Close #1979: Create API for upcoming and previous events on the organizer profile screen
  app/controllers/spree/api/v2/storefront/events_controller.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/overrides/spree/admin/taxons/_form/vendor.html.erb.deface
  app/queries/spree_cm_commissioner/organizer_profile_event_query.rb
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  config/routes.rb
  db/migrate/20240926044328_add_vendor_to_spree_taxon.rb
  spec/queries/spree_cm_commissioner/organizer_profile_event_query_spec.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: api, backend

#2048 Close #2047 implement JWT on email confirmation
  app/controllers/spree/api/v2/storefront/anonymous_order_controller.rb
  app/helpers/spree/base_helper_decorator.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_items.html.erb
  config/routes.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/order_jwt_token.rb
Labels: L

#2119 close #2118 Add place to place serializer
  app/serializers/spree_cm_commissioner/v2/storefront/product_place_serializer.rb
Labels: enhancement

#2123 close #2122 void last invoice if penalty
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
  spec/controllers/spree/billing/report_controller_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
  spec/queries/spree_cm_commissioner/subscription_orders_query_spec.rb
Labels: enhancement, backend, billing

#2117 close #2116 add promotion related field to serializer
  app/overrides/spree/admin/promotions/_form/auto_apply_field.html.erb.deface
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/promotion_serializer.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree_cm_commissioner/v2/storefront/promotion_serializer_spec.rb
Labels: enhancement

#2041 close #2040 allow import guest infos when import
  app/interactors/spree_cm_commissioner/import_csv_template_downloader.rb
  app/models/spree_cm_commissioner/guest.rb
  app/services/spree_cm_commissioner/imports/create_order_service.rb
  app/services/spree_cm_commissioner/imports/update_order_service.rb
  app/views/spree/admin/guest_qr_codes/_guest_qr_code.html.erb
  app/views/spree/admin/guest_qr_codes/index.html.erb
Labels: enhancement, backend

#1594 Close #1576 enhance validation for self check-in
  app/controllers/spree/api/v2/storefront/self_check_in_controller.rb
  config/locales/en.yml
Labels: enhancement

#2125 Close #2124 Add vendor state to vendor serializer
  app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/accommodation_serializer_spec.rb
  spec/serializers/spree/v2/storefront/vendor_serializer_spec.rb
Labels: api, XS

#2132 close #2128: add index to event_id in cm_guests to fix slow query
  db/migrate/20241210103106_add_index_to_event_id_in_cm_guests.rb
Labels: chore

#2113 close #2112 enqueue add to cart
  app/controllers/spree/api/v2/storefront/queue_cart/line_items_controller.rb
  app/interactors/spree_cm_commissioner/enqueue_cart/add_item.rb
  app/interactors/spree_cm_commissioner/enqueue_cart/add_item_status_marker.rb
  app/jobs/spree_cm_commissioner/enqueue_cart/add_item_job.rb
  app/serializables/spree_cm_commissioner/queue_item.rb
  app/serializers/spree/v2/storefront/firestore_queue_serializer.rb
  config/routes.rb
  spec/interactors/spree_cm_commissioner/enqueue_cart/add_item_status_marker_spec.rb
  spec/jobs/spree_cm_commissioner/add_item_job_spec.rb
Labels: enhancement, api

#2141 close #2140 handle job fail case on queue add item
  app/controllers/spree/api/v2/storefront/queue_cart/line_items_controller.rb
Labels: enhancement, api

#2142 close #2133 enchance N+1 admin/products
  app/controllers/spree_cm_commissioner/admin/products_controller_decorator.rb
Labels: enhancement

#2149 close #2148 segment data by date add item queue
  app/interactors/spree_cm_commissioner/enqueue_cart/add_item_status_marker.rb
Labels: enhancement, api

#2146 close #2139 improving adding product guest card
  app/controllers/spree/admin/variant_guest_card_classes_controller.rb
  app/views/spree/admin/variant_guest_card_classes/_variant_guest_card_class.html.erb
  app/views/spree/admin/variant_guest_card_classes/index.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: enhancement

#2151 close #2150 remove nested translation for spree.currency
  app/views/spree/billing/shared/_pop_up_confirmation.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: bug

#2160 close #2159 added reason when voiding reason
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
Labels: backend, billing

#2131 Close #2130 Update JWT email confirmation
  app/controllers/spree/api/v2/storefront/anonymous_line_item_controller.rb
  app/controllers/spree/api/v2/storefront/anonymous_order_controller.rb
  app/helpers/spree/base_helper_decorator.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_items.html.erb
  config/routes.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/line_item_jwt_token.rb
  lib/spree_cm_commissioner/order_jwt_token.rb
Labels: enhancement

#2158 close #2129 fix calculate ticket flow
  app/controllers/spree/api/v2/operator/recalculate_tickets_controller.rb
  config/routes.rb
Labels: enhancement, api, XS

#2197 close #2196 prevent assigning random address to user
  app/models/spree_cm_commissioner/order/address_book_decorator.rb
  spec/models/spree_cm_commissioner/order/address_book_decorator_spec.rb
Labels: bug

#2199 close #2198 fix could not create new promotion
  app/models/spree_cm_commissioner/promotion_decorator.rb
  app/overrides/spree/admin/promotions/_form/auto_apply_field.html.erb.deface
Labels: bug

#2172 Close #2171 Update line_item to line_items on anonymous line items
  app/controllers/spree/api/v2/storefront/anonymous_line_items_controller.rb
  app/helpers/spree/base_helper_decorator.rb
  config/routes.rb
Labels: enhancement
