Repository channainfo/commissioner, pull requests merged in 2024-05, with the labels that each got.

#1374 close #1373 fix wrong spelling cancle to canceled
  app/models/spree_cm_commissioner/order_decorator.rb
Labels: XS

#1380 close #1379 add upload later field to guests table
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  db/migrate/20240502051314_add_upload_later_to_guest.rb
Labels: api, M

#1377 Close #1371 one invoice can has many subscriptions
  app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/views/spree/billing/report/balance_due.html.erb
  app/views/spree/billing/shared/_invoice.html.erb
  app/views/spree/billing/subscriptions/_form.html.erb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
Labels: backend, billing

#1390 close #1389 add delivery type attribute type
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/overrides/spree/admin/option_types/_option_value_fields/option_value_replacer.html.erb.deface
Labels: backend, S

#1394 close #1393 making sure shipping flow from backend work
  app/controllers/spree_cm_commissioner/admin/orders_controller_decorator.rb
  app/overrides/spree/admin/shipping_methods/_form/vendor.html.erb.deface
Labels: enhancement, S

#1397 close #1396 add-delivery-option-option-value-serializer
  app/models/concerns/spree_cm_commissioner/variant_option_values_concern.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: backend, S

#1395 close #1342 add guest serializer spec
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
Labels: spec, XS

#1403 close #1402 rename option-values fields
  app/models/concerns/spree_cm_commissioner/variant_option_values_concern.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: enhancement

#1247 close #1241 export guest csv in background with sidekiq
  app/controllers/spree/events/data_exports_controller.rb
  app/controllers/spree/events/guests_controller.rb
  app/interactors/spree_cm_commissioner/generate_guests_csv.rb
  app/jobs/spree_cm_commissioner/export_csv_job.rb
  app/models/spree_cm_commissioner/ability_decorator.rb
  app/models/spree_cm_commissioner/export.rb
  app/models/spree_cm_commissioner/exports/export_guest_csv.rb
  app/models/spree_cm_commissioner/guest.rb
  app/services/spree_cm_commissioner/exports/export_guest_csv_service.rb
  app/views/spree/events/data_exports/index.html.erb
  app/views/spree/events/guests/index.html.erb
  app/views/spree/events/shared/_guest_tabs.html.erb
  app/views/spree/events/shared/_main_menu.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20240327082849_create_spree_cm_commissioner_exports.rb
  db/migrate/20240506023613_add_index_to_uuid_in_cm_exports.rb
  db/migrate/20240506025443_add_finished_at_to_exports.rb
  lib/spree_cm_commissioner/test_helper/factories/export_guest_csv_factory.rb
  spec/interactors/spree_cm_commissioner/generate_guests_csv_spec.rb
  spec/services/spree_cm_commissioner/exports/export_guest_csv_service_spec.rb
Labels: enhancement, L

#1405 close #1404 fix id for nil class for shipping method form
  app/overrides/spree/admin/shipping_methods/_form/vendor.html.erb.deface
Labels: bug

#1384 Close #1376 fixed the wished api
  app/controllers/spree/api/v2/storefront/wished_controller.rb
  config/routes.rb
Labels: bug

#1401 close #1400 improve adding user to event and adding event to using experience
  app/controllers/spree/admin/user_events_controller.rb
  app/controllers/spree/admin/user_taxons_controller.rb
  app/models/spree_cm_commissioner/user_event.rb
  app/overrides/spree/admin/users/_tabs/tabs.html.erb.deface
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  app/views/spree/admin/user_events/_events.html.erb
  app/views/spree/admin/user_events/_new_event.html.erb
  app/views/spree/admin/user_events/_new_user.html.erb
  app/views/spree/admin/user_events/_users.html.erb
  app/views/spree/admin/user_events/index.html.erb
  app/views/spree/admin/user_events/new.html.erb
  app/views/spree/admin/user_taxons/_form.html.erb
  app/views/spree/admin/user_taxons/edit.html.erb
  app/views/spree/admin/user_taxons/index.html.erb
  config/routes.rb
Labels: enhancement, M

#1391 close #1352 send_all_now to all customer_notifications
  app/controllers/spree/admin/customer_notifications_controller.rb
  app/interactors/spree_cm_commissioner/customer_notification_sender.rb
  app/jobs/spree_cm_commissioner/customer_notification_sender_job.rb
  app/views/spree/admin/customer_notifications/index.html.erb
  app/views/spree/admin/shared/_send_all_form.html.erb
  app/views/spree/admin/shared/_send_test_form.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  spec/interactors/spree_cm_commissioner/customer_notification_sender_job_spec.rb
  spec/interactors/spree_cm_commissioner/customer_notification_sender_spec.rb
Labels: backend, L

#1412 close #1409 only build shipments & inventory units for line item that required delivery
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/stock/inventory_unit_builder_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/serializers/spree/v2/storefront/line_item_order_serializer.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  spec/models/spree/stock/inventory_unit_builder_spec.rb
  spec/models/spree/variant_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: enhancement

#1418 Close #1417 edit adjustment bug in billing
  app/controllers/spree/billing/adjustments_controller.rb
Labels: bug, backend, billing

#1420 close #1305 enchance customer notification ui
  app/models/spree_cm_commissioner/user_decorator.rb
  app/views/spree/admin/shared/_send_test_form.html.erb
Labels: enhancement, backend, L

#1392 close #1372 change issued-date from created_at to start_date
  app/controllers/spree/billing/report_controller.rb
  app/views/spree/billing/customers/_form.html.erb
  app/views/spree/billing/report/active_subscribers.html.erb
  app/views/spree/billing/report/balance_due.html.erb
  app/views/spree/billing/report/paid.html.erb
  app/views/spree/billing/report/show.html.erb
Labels: backend, billing

#1428 Close #1427 Filter invoice by invoice printed or not yet
  app/models/spree_cm_commissioner/invoice.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/views/spree/billing/report/balance_due.html.erb
  config/locales/en.yml
Labels: backend, billing

#1415 close #1414 add sequence to trip stop
  app/controllers/spree/transit/routes_controller.rb
  app/controllers/spree/transit/trip_stops_controller.rb
  app/controllers/spree/transit/trips_controller.rb
  app/models/spree_cm_commissioner/trip_stop.rb
  app/views/spree/transit/shared/_route_tabs.html.erb
  app/views/spree/transit/trip_stops/index.html.erb
  config/routes.rb
  db/migrate/20240510103536_add_sequence_to_cm_trip_stops.rb
  spec/models/spree/line_item_spec.rb
Labels: backend, transit

#1408 close #1407 add button for download import csv file template
  app/controllers/spree/admin/import_orders_controller.rb
  app/interactors/spree_cm_commissioner/import_csv_template_downloader.rb
  app/views/spree/admin/import_orders/index.html.erb
  config/routes.rb
Labels: enhancement, feature, XS

#1432 Close #1431 add invoice print button to each invoice in balance due page
  app/controllers/spree/billing/invoice_controller.rb
  app/views/spree/billing/report/balance_due.html.erb
Labels: backend, billing

#1350 Close #1348 Edit customer can have multiple taxons and add location f…
  app/controllers/spree/billing/customers_controller.rb
  app/controllers/spree/billing/places_controller.rb
  app/models/spree_cm_commissioner/customer.rb
  app/models/spree_cm_commissioner/customer_taxon.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/place.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/views/spree/billing/customers/_form.html.erb
  app/views/spree/billing/customers/index.html.erb
  app/views/spree/billing/orders/_search.html.erb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/places/_form.html.erb
  app/views/spree/billing/places/edit.html.erb
  app/views/spree/billing/places/index.html.erb
  app/views/spree/billing/places/new.html.erb
  app/views/spree/billing/shared/_main_menu.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20240424080551_create_cm_customer_taxons.rb
  db/migrate/20240425042912_remove_taxon_id_from_cm_customer.rb
  db/migrate/20240429080434_add_place_id_to_cm_customer.rb
  db/migrate/20240516031731_add_code_to_cm_place.rb
  lib/spree_cm_commissioner/test_helper/factories/customers_taxons_factory.rb
  spec/models/spree_cm_commissioner/customer_spec.rb
Labels: backend, billing

#1434 Close #1433 Create a new WishedItems API to handle actions like and unlike
  app/controllers/spree/api/v2/storefront/wished_controller.rb
  app/controllers/spree/api/v2/storefront/wished_items_controller.rb
  config/routes.rb
Labels: api

#1429 close #1203 integrate otp with pin code
  app/controllers/spree/api/v2/storefront/pin_code_otp_checkers_controller.rb
  app/controllers/spree/api/v2/storefront/pin_code_otp_generators_controller.rb
  app/interactors/spree_cm_commissioner/pin_code_creator.rb
  app/models/spree_cm_commissioner/pin_code.rb
  app/models/spree_cm_commissioner/pin_code_otp.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20240521040143_add_opt_fields_to_spree_user.rb
  spec/request/spree/api/v2/controller/pin_code_otp_checkers_controller_spec.rb
  spec/request/spree/api/v2/controller/pin_code_otp_generators_controller_spec.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
  spec/services/spree_cm_commissioner/user_authenticator_spec.rb
Labels: security, blockchain

#1421 close #1413 add pending guests api for kyc upload later experience
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/controllers/spree/api/v2/storefront/pending_line_items_controller.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  config/routes.rb
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: api, L

#1451 close #1441 add commission to product of vendors
  app/controllers/spree/admin/product_commissions_controller.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/models/spree_cm_commissioner/webhooks/rules/order_vendors.rb
  app/overrides/spree/admin/vendors/edit/vendor_tabs.html.erb.deface
  app/services/spree_cm_commissioner/orders/generate_commissions_decorator.rb
  app/views/spree/admin/product_commissions/index.html.erb
  app/views/spree/admin/shared/_vendor_tabs.html.erb
  config/routes.rb
  db/migrate/20240527043322_add_commission_rate_to_spree_products.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/vendor_spec.rb
  spec/services/spree/orders/generate_commissions_spec.rb
Labels: enhancement, backend

#1444 close #1443 when selecting customer product taxon, it will only show …
  app/controllers/spree/billing/customers_controller.rb
  app/views/spree/billing/customers/_form.html.erb
  app/views/spree/billing/customers/index.html.erb
Labels: backend, billing

#1426 Close #1425 Filter invoice by each month
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/report_hide_filter.js
  app/controllers/spree/billing/reports_controller.rb
  app/controllers/spree/billing/roles_controller.rb
  app/errors/spree_cm_commissioner/exceeding_range_error.rb
  app/views/spree/billing/reports/_date_range_picker.html.erb
  app/views/spree/billing/reports/_overview.html.erb
  app/views/spree/billing/reports/active_subscribers.html.erb
  app/views/spree/billing/reports/balance_due.html.erb
  app/views/spree/billing/reports/failed_orders.html.erb
  app/views/spree/billing/reports/index.html.erb
  app/views/spree/billing/reports/overdue.html.erb
  app/views/spree/billing/reports/paid.html.erb
  app/views/spree/billing/shared/sub_menu/_report.html.erb
  config/locales/en.yml
  config/routes.rb
Labels: backend, billing

#1463 close # 1461 fix canceled order to make sure it can not create check_in
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
Labels: bug, XS

#1447 Close #1445 Show more columns in Places index page
  app/models/spree_cm_commissioner/place.rb
  app/views/spree/billing/places/index.html.erb
Labels: backend, billing

#1436 close #1423 push notification to user by taxon
  app/controllers/spree/admin/customer_notifications_controller.rb
  app/controllers/spree/admin/notification_sender_controller.rb
  app/controllers/spree/admin/notification_users_controller.rb
  app/interactors/spree_cm_commissioner/notification_send_creator.rb
  app/models/spree_cm_commissioner/customer_notification.rb
  app/models/spree_cm_commissioner/notification_taxon.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/queries/spree_cm_commissioner/users_by_event_fetcher_query.rb
  app/views/spree/admin/customer_notifications/_form.html.erb
  app/views/spree/admin/customer_notifications/index.html.erb
  app/views/spree/admin/shared/_send_all_form.html.erb
  app/views/spree/admin/shared/_send_test_form.html.erb
  config/routes.rb
  db/migrate/20240524040448_create_spree_cm_notification_taxons.rb
  lib/spree_cm_commissioner/test_helper/factories/notification_taxons_factory.rb
  spec/interactors/spree_cm_commissioner/notification_send_creator_spec.rb
Labels: backend, L

#1468 Close #1454 Only show the leaves of the taxon tree
  app/controllers/spree/billing/products_controller.rb
  app/views/spree/billing/products/_form.html.erb
  app/views/spree/billing/products/new.html.erb
Labels: backend, billing

#1470 Close #1469 Change date format billing
  app/views/spree/billing/subscriptions/_form.html.erb
  config/locales/en.yml
Labels: backend, billing
