Repository channainfo/commissioner, pull requests merged in 2024-11, with the labels that each got.

#2036 close #2035 fixed invoice recurring not working
  app/jobs/spree_cm_commissioner/subscription_order_executor_job.rb
  app/views/spree/billing/shared/_pop_up_confirmation.html.erb
  lib/tasks/subscriptions_order_creator.rake
Labels: backend, billing

#2031 Close #2027 enhance text with openai
  .env.example
  .gitignore
  .rubocop.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/interactors/spree_cm_commissioner/ai/enhancer_adapter/openai.rb
  app/interactors/spree_cm_commissioner/ai/text_enhancer.rb
  config/initializers/openai.rb
  docker-compose.yml
  lib/spree_cm_commissioner.rb
  spec/cassettes/SpreeCmCommissioner_Ai_EnhancerAdapter_Openai/_enhence_text/enhance_the_text.yml
  spec/cassettes/SpreeCmCommissioner_Ai_TextEnhancer/_call/return_the_enhanced_text.yml
  spec/interactors/spree_cm_commissioner/ai/enhancer_adapter/openai_spec.rb
  spec/interactors/spree_cm_commissioner/ai/text_enhancer_spec.rb
  spec/support/vcr.rb
  spree_cm_commissioner.gemspec
Labels: ai

#2050 close #2049-avoid-triggering-telegram-job-for-subscription
  app/models/concerns/spree_cm_commissioner/order_requestable.rb
Labels: backend, billing

#2030 Close #2025 Billing update export csv to include adjustments
  app/services/spree_cm_commissioner/exports/export_order_csv_service.rb
  app/views/spree/billing/shared/_pop_up_confirmation.html.erb
Labels: backend, billing

#2056 Close #2055 Fix invoice calculation
  app/views/spree/billing/shared/_invoice.html.erb
Labels: backend, billing

#2037 Close #2033 enhance BookMe+ order confirmation
  app/assets/images/mailer/event-mailer-bg.png
  app/views/spree/order_mailer/confirm_email.html.erb
  app/views/spree_cm_commissioner/layouts/order_mailer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_customer_info.html.erb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  app/views/spree_cm_commissioner/order_mailer/_mailer_stylesheets.html.erb
  app/views/spree_cm_commissioner/order_mailer/_order_total.html.erb
  app/views/spree_cm_commissioner/order_mailer/_support_contact.html.erb
  app/views/spree_cm_commissioner/order_mailer/_your_booking.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_items.html.erb
  app/views/spree_cm_commissioner/order_mailer/purchased_items/_summary.html.erb
  config/locales/en.yml
  config/locales/km.yml
Labels: enhancement, L

#2061 close #2057 add purchasable_on to product and taxon
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/overrides/spree/admin/products/_form/purchasable_on_status.html.erb.deface
  app/overrides/spree/admin/taxons/_form/purchasable_on_status.html.erb.deface
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  db/migrate/20241118184033_add_purchasable_on_to_spree_taxons.rb
  db/migrate/20241118184157_add_purchasable_on_to_spree_products.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: api, backend, XS

#2063 close #2062 enchance guest_card ui avoid show null or N/A row
  app/views/spree_cm_commissioner/guest_cards/show.html.erb
Labels: enhancement, XS

#2059 close #2058 invalidate cache for frequently use API
  .env.example
  app/controllers/concerns/spree_cm_commissioner/content_cachable.rb
  app/controllers/spree/admin/base_controller_decorator.rb
  app/controllers/spree_cm_commissioner/action_controller/api_decorator.rb
  app/controllers/spree_cm_commissioner/application_controller_decorator.rb
  app/interactors/spree_cm_commissioner/invalidate_cache_request.rb
  app/jobs/spree_cm_commissioner/invalidate_cache_request_job.rb
  app/views/spree/admin/homepage_section/index.html.erb
  config/routes.rb
  spec/cassettes/SpreeCmCommissioner_InvalidateCacheRequest/_call/requested_to_invalidate_cache_return_response.yml
  spec/interactors/spree_cm_commissioner/invalidate_cache_request_spec.rb
  spec/jobs/spree_cm_commissioner/invalidate_cache_request_job_spec.rb
Labels: feature

#2067 close #2066 add deploy badge version to admin dashboard
  app/overrides/spree/admin/shared/_version/deploy_tag_version_badge.html.erb.deface
Labels: backend, XS

#2070 close #2069 fix set pin code error
  config/initializers/spree_permitted_attributes.rb
Labels: bug, XS

#2060 close #1991 add virtual waiting room API
  .env.example
  Gemfile.lock
  app/controllers/concerns/spree_cm_commissioner/waiting_room_authorization.rb
  app/controllers/spree/admin/system_controller.rb
  app/controllers/spree/api/v2/resource_controller_decorator.rb
  app/controllers/spree/api/v2/storefront/waiting_room_sessions_controller.rb
  app/interactors/spree_cm_commissioner/waiting_guests_caller.rb
  app/interactors/spree_cm_commissioner/waiting_room_latest_system_metadata_puller.rb
  app/interactors/spree_cm_commissioner/waiting_room_session_creator.rb
  app/jobs/spree_cm_commissioner/waiting_guests_caller_job.rb
  app/jobs/spree_cm_commissioner/waiting_room_latest_system_metadata_puller_job.rb
  app/models/spree_cm_commissioner/waiting_room_session.rb
  app/serializers/spree_cm_commissioner/v2/storefront/waiting_room_session_serializer.rb
  app/services/spree_cm_commissioner/waiting_room_system_metadata_fetcher.rb
  app/services/spree_cm_commissioner/waiting_room_system_metadata_setter.rb
  app/views/spree/admin/system/show.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
  db/migrate/20241119032456_create_cm_waiting_room_sessions.rb
  spec/cassettes/SpreeCmCommissioner_ServerInstancesBulkCreator/_call/request_all_tasks_create_active_servers_inactive_all_services.yml
  spec/interactors/spree_cm_commissioner/waiting_guests_caller_spec.rb
  spec/interactors/spree_cm_commissioner/waiting_room_session_creator_spec.rb
  spec/models/spree_cm_commissioner/waiting_room_session_spec.rb
  spec/request/spree/api/v2/products_spec.rb
  spec/serializers/spree/v2/storefront/option_value_serializer_spec.rb
  spree_cm_commissioner.gemspec
Labels: feature

#2075 close #2074 remove api cache
  app/controllers/concerns/spree_cm_commissioner/waiting_room_authorization.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
Labels: backend

#2079 Close #2078 set the cache header for CDN
  .gitignore
  app/controllers/concerns/spree_cm_commissioner/content_cachable.rb
  spec/controllers/application_controller_spec.rb
Labels: engagement

#2089 close #2088 avoid carrying voided invoice forward
  app/controllers/spree/billing/payments_controller.rb
  app/interactors/spree_cm_commissioner/subscriptions_order_creator.rb
Labels: backend, billing

#2090 Close #2087 Improve UI in order_mailer to preview the QR code in the admin panel
  app/controllers/spree_cm_commissioner/orders_controller.rb
  app/mailers/spree/order_mailer_decorator.rb
  app/views/spree/order_mailer/confirm_email.html.erb
  app/views/spree_cm_commissioner/order_mailer/_greeting.html.erb
  app/views/spree_cm_commissioner/order_mailer/_mailer_stylesheets.html.erb
Labels: enhancement, S

#2085 Close #2084 Enhance email confirmation background color on dark mode
  app/views/spree_cm_commissioner/layouts/order_mailer.html.erb
  app/views/spree_cm_commissioner/order_mailer/_mailer_stylesheets.html.erb
Labels: enhancement, S

#2086 close #2080 fix bug taxon reposition not work
  app/models/spree_cm_commissioner/taxon_decorator.rb
  spec/models/spree/taxon_spec.rb
Labels: bug, S

#2095 close #2094 add second to order state changes timestamp
  app/overrides/spree/admin/state_changes/index/add_second_to_timestamp.html.erb.deface
Labels: backend

#2099 close #2098 check in by guest qrcode
  app/views/spree/admin/guest_qr_codes/_guest_qr_code.html.erb
Labels: backend

#2097 close #2096 filter order by vendor
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/overrides/spree/admin/orders/_search/vendor_search_field.html.erb.deface
  spec/models/spree/line_item_spec.rb
Labels: enhancement, backend

#2093 close #2092 fix undefined-method-money-for-string
  app/overrides/spree/admin/payments/_form/amount_text_field.html.erb.deface
Labels: bug
