Repository channainfo/commissioner, pull requests merged in 2024-07, with the labels that each got.

#1568 Close #1562 Month filtering bug
  app/views/spree/billing/reports/_date_range_picker.html.erb
Labels: bug

#1589 Close #1581 Billing user role bug
  app/controllers/spree/billing/roles_controller.rb
  app/views/spree/billing/adjustments/_adjustment.html.erb
  app/views/spree/billing/adjustments/_adjustments_table.html.erb
  app/views/spree/billing/adjustments/index.html.erb
  app/views/spree/billing/businesses/index.html.erb
  app/views/spree/billing/customers/index.html.erb
  app/views/spree/billing/option_types/index.html.erb
  app/views/spree/billing/orders/_form.html.erb
  app/views/spree/billing/orders/index.html.erb
  app/views/spree/billing/payments/_list.html.erb
  app/views/spree/billing/payments/index.html.erb
  app/views/spree/billing/places/index.html.erb
  app/views/spree/billing/products/index.html.erb
  app/views/spree/billing/reports/active_subscribers.html.erb
  app/views/spree/billing/reports/balance_due.html.erb
  app/views/spree/billing/roles/index.html.erb
  app/views/spree/billing/shared/_main_menu.html.erb
  app/views/spree/billing/shared/_order_tabs.html.erb
  app/views/spree/billing/shared/sortable_tree/_taxonomy.html.erb
  app/views/spree/billing/shared/sub_menu/_product.html.erb
  app/views/spree/billing/shared/sub_menu/_report.html.erb
  app/views/spree/billing/shared/sub_menu/_setting.html.erb
  app/views/spree/billing/subscriptions/index.html.erb
  app/views/spree/billing/users/index.html.erb
  app/views/spree/billing/variants/index.html.erb
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
Labels: bug, billing

#1382 close #1381 create review selectors with spree taxon
  app/controllers/spree/admin/taxon_star_ratings_controller.rb
  app/interactors/spree_cm_commissioner/star_rating_modifier.rb
  app/models/concerns/spree_cm_commissioner/taxon_kind.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/taxon_star_rating.rb
  app/overrides/spree/admin/shared/_product_tabs/star_rating.html.erb.deface
  app/views/spree/admin/shared/_taxon_star_rating_tabs.html.erb
  app/views/spree/admin/taxon_star_ratings/index.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20240513032118_create_spree_cm_commissioner_taxon_star_rating.rb
  db/migrate/20240514071430_create_spree_cm_commissioner_taxon_review.rb
Labels: backend, M

#1596 close #1595 fixed updating user role error
  app/controllers/concerns/spree_cm_commissioner/billing/role_authorization.rb
Labels: bug, billing

#1603 close #1587 refactor to support offline check-in
  app/controllers/spree/api/chatrace/check_ins_controller.rb
  app/controllers/spree/api/v2/operator/check_in_bulks_controller.rb
  app/controllers/spree/api/v2/operator/check_ins_controller.rb
  app/controllers/spree/api/v2/storefront/self_check_in_controller.rb
  app/controllers/spree/events/guests_controller.rb
  app/interactors/spree_cm_commissioner/check_in_bulk_creator.rb
  app/queries/spree_cm_commissioner/line_item_searcher_query.rb
  app/serializers/spree_cm_commissioner/v2/operator/guest_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/line_item_order_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/line_item_serializer.rb
  spec/interactors/spree_cm_commissioner/check_in_bulk_creator_spec.rb
  spec/queries/spree_cm_commissioner/line_item_seacher_query_spec.rb
  spec/queries/spree_cm_commissioner/line_item_searcher_query_spec.rb
  spec/serializers/spree_cm_commissioner/v2/operator/line_item_serializer_spec.rb
Labels: enhancement

#1605 close #1604 update event id if it invalid
  app/controllers/spree/admin/classifications_controller.rb
  app/interactors/spree_cm_commissioner/conversion_pre_calculator.rb
  app/views/spree/admin/guests/_table.html.erb
  spec/interactors/spree_cm_commissioner/conversion_pre_calculator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_creator_spec.rb
Labels: enhancement

#1607 close #1606 add phone / line item number to order filter admin
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/overrides/spree/admin/orders/_line_items/_line_items.html.erb.deface
  app/overrides/spree/admin/orders/_search/intel_phone_number_search_field.html.erb.deface
  app/overrides/spree/admin/orders/_search/line_item_number_search_field.html.erb.deface
Labels: enhancement, backend

#1609 close #1608 no auto fill value to ransack in event/guests dashboard
  app/views/spree/events/shared/_filters.html.erb
Labels: enhancement

#1593 close #1591 fix bug device token and Refactor Notification
  app/controllers/spree/admin/notification_sender_controller.rb
  app/interactors/spree_cm_commissioner/customer_notification_cron_executor.rb
  app/interactors/spree_cm_commissioner/customer_notification_sender.rb
  app/interactors/spree_cm_commissioner/notification_send_creator.rb
  app/interactors/spree_cm_commissioner/unique_device_token_cron_executor.rb
  app/interactors/spree_cm_commissioner/user_device_token_register.rb
  app/jobs/spree_cm_commissioner/customer_notification_cron_job.rb
  app/jobs/spree_cm_commissioner/unique_device_token_cron_job.rb
  app/views/spree/admin/device_tokens/index.html.erb
  lib/tasks/customer_notification_cron_scheduler.rake
  lib/tasks/remove_duplicate_device_tokens.rake
  spec/interactors/spree_cm_commissioner/customer_notification_sender_spec.rb
  spec/interactors/spree_cm_commissioner/notification_send_creator_spec.rb
  spec/interactors/spree_cm_commissioner/user_device_token_register_spec.rb
  spec/jobs/spree_cm_commissioner/customer_notification_cron_job_spec.rb
Labels: bug, backend

#1558 Close: #1556 add meta-data to file video upload
  app/controllers/spree/admin/video_on_demands_controller.rb
  app/helpers/spree_cm_commissioner/admin/video_on_demand_helper.rb
  app/interactors/spree_cm_commissioner/video_on_demand_creator.rb
  app/interactors/spree_cm_commissioner/video_on_demand_updater.rb
  app/models/concerns/spree_cm_commissioner/video_on_demand_bitwise.rb
  app/models/spree_cm_commissioner/video_on_demand.rb
  app/views/spree/admin/video_on_demands/_form.html.erb
  config/locales/en.yml
  db/migrate/20240624082727_add_video_quality_to_cm_video_on_demands.rb
  db/migrate/20240624092531_add_video_protocol_to_cm_video_on_demands.rb
  db/migrate/20240627022903_add_frame_rate_to_cm_video_on_demands.rb
  db/migrate/20240704021831_add_uuid_to_cm_video_on_demand.rb
Labels: L

#1602 Close #1588 refactor presigned url to work with different bucket and …
  README.md
  app/controllers/spree/api/v2/storefront/s3_signed_urls_controller.rb
  app/models/spree_cm_commissioner/s3_presigned_url.rb
  app/models/spree_cm_commissioner/s3_presigned_url_builder.rb
  app/models/spree_cm_commissioner/s3_signed_url.rb
  spec/models/spree_cm_commissioner/s3_presigned_url_builder_spec.rb
  spec/models/spree_cm_commissioner/s3_presigned_url_spec.rb
Labels: enhancement

#1620 Close #1600 Monthly filtering based on cashier place
  app/controllers/spree/billing/customers_controller.rb
  app/controllers/spree/billing/orders_controller.rb
  app/controllers/spree/billing/reports_controller.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/models/spree_cm_commissioner/user_place.rb
  app/queries/spree_cm_commissioner/subscription_orders_query.rb
  app/queries/spree_cm_commissioner/subscription_revenue_overview_query.rb
  app/views/spree/billing/users/_form.html.erb
  db/migrate/20240705081425_create_cm_user_places.rb
  spec/queries/spree_cm_commissioner/subscription_orders_query_spec.rb
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
Labels: backend, billing

#1622 Close #1619 billing user role bug additional fix
  app/controllers/spree/billing/roles_controller.rb
  app/views/spree/billing/reports/balance_due.html.erb
  app/views/spree/billing/shared/_customer_tabs.html.erb
  app/views/spree/billing/shared/_vendor_switcher.html.erb
Labels: bug

#1637 close #1636 add KYC social contact platform
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/spree_cm_commissioner/guest.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  app/views/spree/admin/kyc/_form.html.erb
  db/migrate/20240709114205_add_social_contact_to_cm_guests.rb
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: feature, S

#1639 close #1638 make delivery required base entirely on variant option type
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/variant_spec.rb
  spec/models/spree_cm_commissioner/stock/availability_checker_spec.rb
Labels: enhancement

#1642 close #1641 set line item from_date & to_date base on variant option values
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/concerns/spree_cm_commissioner/option_type_attr_type.rb
  app/models/concerns/spree_cm_commissioner/variant_options_concern.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/variant_options.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  lib/spree_cm_commissioner/test_helper/factories/taxon_factory.rb
  spec/models/concerns/spree_cm_commissioner/variant_options_concern_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/option_type_spec.rb
  spec/models/spree_cm_commissioner/variant_options_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: enhancement

#1644 close #1643 auto create option value when editing variant
  app/controllers/spree_cm_commissioner/admin/variants_controller_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/overrides/spree/admin/variants/_form/option_types_replacer.html.erb.deface
  app/overrides/spree/admin/variants/edit/card-header.html.erb.deface
  app/overrides/spree/admin/variants/edit/variant_status.html.erb.deface
  app/views/spree/admin/variants/_date_field.html.erb
  app/views/spree/admin/variants/_default_field.html.erb
  app/views/spree/admin/variants/_option_values.html.erb
  app/views/spree/admin/variants/_time_field.html.erb
Labels: enhancement

#1628 close #1627 notification feature images api
  app/models/spree_cm_commissioner/customer_notification.rb
  app/models/spree_cm_commissioner/feature_image.rb
  app/models/spree_cm_commissioner/store_decorator.rb
  app/serializers/spree/v2/storefront/customer_notification_serializer.rb
  spec/serializers/spree/v2/storefront/customer_notification_serializer_spec.rb
Labels: enhancement, api

#1629 Close #1616 allow on or off for upload later
  app/controllers/spree/admin/kyc_controller.rb
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/models/spree_cm_commissioner/guest.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  app/views/spree/admin/kyc/edit.html.erb
  config/locales/en.yml
  config/locales/km.yml
  db/migrate/20240705092324_add_allowed_upload_later_to_spree_product.rb
  spec/serializers/spree/v2/storefront/guest_serializer_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
Labels: enhancement, L

#1648 close #1647 discontinue base on product
  app/models/spree_cm_commissioner/variant_decorator.rb
  spec/models/spree/variant_spec.rb
Labels: bug, enhancement

#1624 Close #1601 create term and condition of promotion to store
  app/overrides/spree/admin/stores/_form/store_term_and_condition_promotion.html.erb.deface
  app/serializers/spree/v2/storefront/store_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  config/locales/en.yml
  config/locales/km.yml
  db/migrate/20240705093357_add_term_and_condition_promotion_to_spree_stores.rb
Labels: feature, backend

#1551 Close #1544 process job from SQS media convert callback
  .env.example
  .vscode/settings.json
  Gemfile.lock
  README.md
  app/controllers/spree/api/webhook/media_convert_queues_controller.rb
  app/interactors/spree_cm_commissioner/media/signed_cookie_generator.rb
  app/interactors/spree_cm_commissioner/media/signed_path_generator.rb
  app/interactors/spree_cm_commissioner/media/signed_url_generator.rb
  app/interactors/spree_cm_commissioner/media/signer.rb
  config/routes.rb
  docs/private_key.pem
  docs/public_key.pem
  docs/webhook/sqs.rb
  docs/webhook/sqs/params_job_complete.json
  docs/webhook/sqs/params_job_error.json
  docs/webhook/sqs/params_job_processing.json
  docs/webhook/sqs/params_job_submitted.json
  spec/fixtures/test_private_key.txt
  spec/fixtures/test_public_key.txt
  spec/interactors/spree_cm_commissioner/media/signed_cookie_generator_spec.rb
  spec/interactors/spree_cm_commissioner/media/signed_path_generator_spec.rb
  spec/interactors/spree_cm_commissioner/media/signed_url_generator_spec.rb
  spec/spec_helper.rb
  spec/support/helper.rb
  spree_cm_commissioner.gemspec
Labels: core, backend

#1534 Close #1533 create api promotion coupon code
  app/controllers/spree/api/v2/storefront/user_promotion_controller.rb
  app/models/spree_cm_commissioner/promotion_decorator.rb
  app/models/spree_cm_commissioner/store_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree/v2/storefront/store_promotion_serializer.rb
  app/serializers/spree/v2/storefront/store_serializer_decorator.rb
  app/serializers/spree/v2/storefront/user_promotion_serializer.rb
  config/routes.rb
Labels: api, backend, L

#1653 close #1652 added subscription quantity validation
  app/models/spree_cm_commissioner/subscription.rb
  config/locales/en.yml
  spec/interactors/spree_cm_commissioner/subscribed_order_creator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
  spec/queries/spree_cm_commissioner/subscription_orders_query_spec.rb
  spec/queries/spree_cm_commissioner/subscription_revenue_overview_query_spec.rb
  spec/services/spree_cm_commissioner/penalty_calculator_spec.rb
Labels: backend, billing

#1630 Close #1613 upload video to s3 with presigned url
  app/controllers/spree/admin/s3_presigned_urls_controller.rb
  app/controllers/spree/admin/video_on_demands_controller.rb
  app/interactors/spree_cm_commissioner/video_on_demand_creator.rb
  app/interactors/spree_cm_commissioner/video_on_demand_updater.rb
  app/models/spree_cm_commissioner/video_on_demand.rb
  app/views/spree/admin/shared/_direct_upload.html.erb
  app/views/spree/admin/shared/_video_on_demand_helper_script.html.erb
  app/views/spree/admin/video_on_demands/_form.html.erb
  app/views/spree/admin/video_on_demands/edit.html.erb
  app/views/spree/admin/video_on_demands/index.html.erb
  app/views/spree/admin/video_on_demands/new.html.erb
  config/routes.rb
  db/migrate/20240715041800_add_slug_to_video_on_demand.rb
  db/migrate/20240715042121_add_status_to_video_on_demand.rb
  db/migrate/20240715042206_add_cdn_id_to_video_on_demand.rb
Labels: L

#1658 Close #1657 Billing Invoice update
  app/assets/stylesheets/spree_cm_commissioner/backend/invoice.scss
  app/views/spree/billing/shared/_invoice.html.erb
  app/views/spree/billing/shared/_vendor_logo.html.erb
Labels: backend, billing

#1646 Close #1623 Billing load confirmation popup when capture or void payment
  app/controllers/spree/billing/reports_controller.rb
  app/views/spree/billing/orders/_line_item.html.erb
  app/views/spree/billing/reports/_pop_up_confirmation.html.erb
  app/views/spree/billing/reports/balance_due.html.erb
  config/locales/en.yml
Labels: backend, billing

#1564 close #1563 add confirm pin code checker
  app/controllers/spree/api/v2/storefront/confirm_pin_code_checkers_controller.rb
  app/interactors/spree_cm_commissioner/confirm_pin_code_checker.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  config/initializers/spree_permitted_attributes.rb
  config/routes.rb
  db/migrate/20240619103418_rename_encrypted_confirm_pin_code_to_confirm_pin_code_digest_to_spree_users.rb
  db/migrate/20240619104325_add_confirm_pin_code_enabled_to_spree_users.rb
  spec/interactors/spree_cm_commissioner/confirm_pin_code_checker_spec.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
Labels: api, M

#1660 close #1634 enhancement import order
  app/controllers/spree/admin/import_orders_controller.rb
  app/interactors/spree_cm_commissioner/import_csv_template_downloader.rb
  app/models/spree_cm_commissioner/guest.rb
  app/services/spree_cm_commissioner/imports/import_order_service.rb
  app/views/spree/admin/import_orders/_form.html.erb
  app/views/spree/admin/import_orders/new.html.erb
  spec/services/spree_cm_commissioner/imports/import_order_service_spec.rb
Labels: enhancement

#1666 Close #1665 Billing Invoice Update V2
  app/assets/stylesheets/spree_cm_commissioner/backend/invoice.scss
  app/views/spree/billing/shared/_invoice.html.erb
  app/views/spree/billing/shared/_vendor_logo.html.erb
Labels: backend, billing

#1663 close #1662 add allow_anonymous_booking to spree_product
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/overrides/spree/admin/products/_form/allow_anonymous_booking.html.erb.deface
  app/overrides/spree/admin/products/new/allow_anonymous_booking.html.erb.deface
  app/overrides/spree/admin/products/new/include_kyc_checkbox.html.erb.deface
  app/overrides/spree/admin/products/new/need_confirmation_checkbox.html.erb.deface
  app/overrides/spree/admin/products/new/subscribable_checkbox.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  db/migrate/20240715022155_add_allow_anonymous_booking_to_spree_product.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: backend

#1670 Close #1668 Billing pop up modal fix
  app/views/spree/billing/payments/_list.html.erb
  app/views/spree/billing/reports/balance_due.html.erb
  app/views/spree/billing/shared/_pop_up_confirmation.html.erb
Labels: backend, billing

#1677 Close #1676 Filter and search balance due
  app/models/spree_cm_commissioner/invoice.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/views/spree/billing/reports/balance_due.html.erb
  config/locales/en.yml
Labels: backend, billing

#1521 close #1520 remove commission amount implementation, use spree_vpago instead
  app/controllers/spree_cm_commissioner/admin/adjustments_controller_decorator.rb
  app/helpers/spree/admin/base_helper_decorator.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/overrides/spree/admin/adjustments/_adjustment/payable_table_body.html.erb.deface
  app/overrides/spree/admin/adjustments/_adjustments_table/payable_table_header.html.erb.deface
  app/services/spree_cm_commissioner/orders/generate_commissions_decorator.rb
  app/views/shared/_asset_field.html.erb
  spec/services/spree/orders/generate_commissions_spec.rb
Labels: enhancement

#1682 close #1681 Add discontinue_on field to product and variant serializer
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/serializers/spree/v2/storefront/variant_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/variant_serializer_spec.rb
Labels: XS

#1684 Close #1683 added customer promotion rule
  app/models/spree_cm_commissioner/customer_promotion_rule.rb
  app/models/spree_cm_commissioner/promotion/rules/customers.rb
  app/views/spree/admin/promotions/rules/_customers.html.erb
  config/locales/en.yml
  db/migrate/20240722095117_create_spree_promotion_rule_customers.rb
  lib/spree_cm_commissioner/engine.rb
Labels: backend, billing

#1680 Close #1679 Billing add filter columns in order page
  app/views/spree/billing/orders/_search.html.erb
Labels: backend, billing

#1691 close #1678 implement video required on product
  app/controllers/spree/admin/video_on_demands_controller.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/overrides/spree/admin/products/_form/use_video_as_default.html.erb.deface
  app/overrides/spree/admin/shared/_product_tabs/video_on_demand.html.erb.deface
  app/serializers/spree/v2/storefront/product_serializer_decorator.rb
  app/views/spree/admin/video_on_demands/_form.html.erb
  app/views/spree/admin/video_on_demands/index.html.erb
  config/routes.rb
  db/migrate/20240724025704_add_position_to_cm_video_on_demands.rb
  db/migrate/20240725034550_add_use_video_as_default_to_spree_products.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
Labels: L

#1695 Close #1693 Create super admin for billing
  app/controllers/spree/admin/base_controller_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/views/spree/billing/roles/index.html.erb
  app/views/spree/billing/users/_form.html.erb
  spec/controllers/spree/admin/base_controller_spec.rb
Labels: backend, billing

#1697 Close #1696 Delete total invoice from report page
  app/views/spree/billing/reports/index.html.erb
Labels: backend, billing

#1699 Close #1698 Sort orders in report page
  app/views/spree/billing/reports/balance_due.html.erb
  app/views/spree/billing/reports/failed_orders.html.erb
  app/views/spree/billing/reports/index.html.erb
  app/views/spree/billing/reports/overdue.html.erb
  app/views/spree/billing/reports/paid.html.erb
Labels: backend, billing

#1703 Close #1702 Add select year filter in report page
  app/controllers/spree/billing/reports_controller.rb
  app/views/spree/billing/reports/_date_range_picker.html.erb
Labels: backend, billing
