Repository channainfo/commissioner, pull requests merged in 2024-01, with the labels that each got.

#945 close #944 add kyc field to guest line item
  app/serializers/spree_cm_commissioner/v2/storefront/guest_line_item_serializer.rb
Labels: enhancement, XS

#948 close #947 change from customer to guest for kyc
  app/helpers/spree_cm_commissioner/admin/kycable_helper.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/views/spree/admin/kyc/_form.html.erb
  spec/interactors/spree_cm_commissioner/admin/kycable_helper_spec.rb
Labels: enhancement, XS

#949 Close #946 In vendor page allow to add taxons
  app/controllers/spree/admin/vendors_controller_decorator.rb
  app/views/spree/admin/vendors/_form.html.erb
  db/migrate/20240102043145_add_position_to_taxon_vendors.rb
Labels: enhancement, M

#951 close #950 add kyc fields to guest line item api
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_line_item_serializer.rb
Labels: enhancement, api, XS

#935 close #931 guest id card api
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/controllers/spree/api/v2/storefront/id_cards_controller.rb
  app/interactors/spree_cm_commissioner/guest_id_card_manager.rb
  app/interactors/spree_cm_commissioner/id_card_image_updater.rb
  app/interactors/spree_cm_commissioner/profile_image_updater.rb
  app/models/spree_cm_commissioner/back_image.rb
  app/models/spree_cm_commissioner/id_card.rb
  app/serializers/spree/v2/storefront/id_card_serializer.rb
  config/routes.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/s3_url_generator.rb
  lib/spree_cm_commissioner/test_helper/factories/guest_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/id_card_factory.rb
  spec/interactors/spree_cm_commissioner/guest_id_card_manager_spec.rb
  spec/request/spree/api/v2/controller/id_cards_controller_spec.rb
Labels: api, backend, M

#958 close #957 fixed billing invoice not displaying vendor's logo
  app/views/spree/billing/shared/_vendor_logo.html.erb
  app/views/spree/billing/shared/_vendor_switcher.html.erb
Labels: backend, billing

#956 Close #952 Add origin and destination to route
  app/controllers/spree/transit/routes_controller.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/views/spree/transit/routes/_form.html.erb
  app/views/spree/transit/routes/index.html.erb
  app/views/spree/transit/routes/new.html.erb
  db/migrate/20240103095327_add_origin_destination_to_product.rb
Labels: feature, backend, transit

#961 Close #954 Add vendors to the taxon API
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: api, backend, M

#963 close #962 change reference from taxon to occupation for guest
  app/controllers/spree/api/v2/storefront/guests_controller.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
  db/migrate/20240104083828_change_taxon_reference_to_occupation_in_spree_cm_commissioner_guests.rb
Labels: enhancement, XS, migration

#960 close #953 upgrade to spree 4.6
  Gemfile.lock
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/services/spree_cm_commissioner/webhooks/subscribers/handle_request_decorator.rb
  app/services/spree_cm_commissioner/webhooks/subscribers/make_request.rb
  config/initializers/spree_permitted_attributes.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  lib/spree_cm_commissioner/test_helper/factories/option_value_factory.rb
  spec/models/spree/webhooks/subscriber_spec.rb
  spec/serializers/spree/v2/storefront/product_serializer_spec.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
  spec/services/spree/webhooks/subscribers/handle_request_spec.rb
  spec/services/spree_cm_commissioner/webhooks/subscribers/make_request_spec.rb
  spree_cm_commissioner.gemspec
Labels: M, migration

#965 close #964 add kyc fields to guest api
  app/models/spree_cm_commissioner/guest.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
Labels: enhancement, XS

#970 Close #969 Make sure origin and destination they aren't the same
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/selected_field_filter_origin_destination.js
  app/views/spree/transit/routes/_form.html.erb
Labels: enhancement, backend, transit

#972 close #971 predefine layer name
  app/controllers/spree/transit/vehicle_types_controller.rb
  app/models/spree_cm_commissioner/vehicle_seat.rb
  app/views/spree/transit/vehicle_seats/_form.html.erb
  app/views/spree/transit/vehicle_types/_seat_view.erb
  app/views/spree/transit/vehicle_types/edit.html.erb
Labels: backend, transit

#974 close #973 add status to vehicle type
  app/controllers/spree/transit/vehicle_types_controller.rb
  app/models/spree_cm_commissioner/vehicle_type.rb
  app/views/spree/transit/vehicle_types/_form.html.erb
  db/migrate/20240108074029_add_status_to_cm_vehicle_type.rb
Labels: backend, transit

#993 Close #979 Add Primary Photo to Vehicle
  app/views/spree/transit/shared/_vehicle_tabs.html.erb
  app/views/spree/transit/vehicle_photos/index.html.erb
  app/views/spree/transit/vehicles/index.html.erb
Labels: backend

#991 close #983 add roles to account api
  app/serializers/spree/v2/storefront/role_serializer.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
Labels: api, S

#978 Close #975 Display Vehicle/Vehicle-code in edit page
  app/models/spree_cm_commissioner/vehicle.rb
  app/views/spree/transit/vehicles/edit.html.erb
  app/views/spree/transit/vehicles/index.html.erb
Labels: backend

#994 close #992 set up in app checkin record database
  app/models/spree_cm_commissioner/check_in_record.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  db/migrate/20231229070937_create_spree_cm_commissioner_check_in_records.rb
Labels: core, M

#996 close #995 add id card to guest serializer
  app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
Labels: api, XS

#999 close #998 added filter tab for active, darft, and archived vehicle_type
  app/controllers/spree/transit/vehicle_types_controller.rb
  app/views/spree/transit/vehicle_types/index.html.erb
Labels: backend, transit

#1006 close #1005 add auto apply promotions to vendor serializer
  app/models/concerns/spree_cm_commissioner/vendor_promotable.rb
  app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
  lib/spree_cm_commissioner/test_helper/factories/promotion_factory.rb
  spec/models/spree/vendor_spec.rb
  spec/serializers/spree/v2/storefront/accommodation_serializer_spec.rb
  spec/serializers/spree/v2/storefront/vendor_serializer_spec.rb
Labels: enhancement, S

#1009 close #986 check-ins api qr_data params
  app/controllers/spree/api/v2/storefront/check_ins_controller.rb
  app/models/spree_cm_commissioner/ability_decorator.rb
  app/models/spree_cm_commissioner/check_in.rb
  app/models/spree_cm_commissioner/check_in_ability.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/check_in_serializer.rb
  config/routes.rb
  db/migrate/20240112051020_rename_check_in_records_table_to_check_ins.rb
Labels: api, L

#981 close #980 added route_type field to vehicle
  app/models/spree_cm_commissioner/vehicle.rb
  app/views/spree/transit/vehicles/index.html.erb
  config/locales/en.yml
  db/migrate/20240108093344_add_route_type_to_cm_vehicle.rb
Labels: backend, transit

#913 Close #912 Transit Add DataType to taxon
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/location_checkbox_manager.js
  app/controllers/concerns/spree_cm_commissioner/transit/taxon_bitwise.rb
  app/controllers/spree/transit/taxons_controller.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/views/spree/admin/vendor_service_calendars/_form.html.erb
  app/views/spree/transit/routes/index.html.erb
  app/views/spree/transit/taxonomies/_filters.html.erb
  app/views/spree/transit/taxons/_form.html.erb
  app/views/spree/transit/taxons/edit.html.erb
  app/views/spree/transit/taxons/new.html.erb
  db/migrate/20231219111615_add_data_type_to_spree_taxon.rb
Labels: backend, transit

#1014 Close #997 Add Amenity to vehicle type
  app/controllers/spree/transit/amenities_controller.rb
  app/controllers/spree/transit/amenity_values_controller.rb
  app/controllers/spree/transit/vectors/amenity_values_controller.rb
  app/controllers/spree/transit/vectors/icons_controller.rb
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/overrides/spree/admin/option_types/_option_value_fields/option_value_replacer.html.erb.deface
  app/views/spree/transit/amenities/_form.html.erb
  app/views/spree/transit/amenities/_option_value_fields.html.erb
  app/views/spree/transit/amenities/edit.html.erb
  app/views/spree/transit/routes/index.html.erb
  app/views/spree/transit/shared/_amenity_tabs.html.erb
  app/views/spree/transit/shared/_main_menu.html.erb
  app/views/spree/transit/vectors/amenity_values/index.html.erb
  config/routes.rb
Labels: backend, transit

#1000 close #990 promotion rule by guest occupation
  app/models/spree_cm_commissioner/guest_occupation_promotion_rule.rb
  app/models/spree_cm_commissioner/promotion/rules/guest_occupations.rb
  app/views/spree/admin/promotions/rules/_guest_occupations.html.erb
  config/locales/en.yml
  config/locales/km.yml
  db/migrate/20240109081006_create_spree_cm_commissioner_guest_occupation_promotion_rules.rb
  lib/spree_cm_commissioner/engine.rb
  spec/models/spree_cm_commissioner/promotion/rules/guest_occupations_spec.rb
Labels: feature, M

#1008 close #1007 enhance homepage sections api/backend
  app/assets/javascripts/spree_cm_commissioner/backend.js
  app/assets/javascripts/spree_cm_commissioner/routes.js
  app/controllers/spree/admin/homepage_section_controller.rb
  app/controllers/spree/admin/homepage_section_relatable_controller.rb
  app/controllers/spree/api/v2/platform/homepage_section_relatable_options_controller.rb
  app/controllers/spree/api/v2/storefront/homepage_sections_controller.rb
  app/models/spree_cm_commissioner/homepage_section.rb
  app/models/spree_cm_commissioner/homepage_section_relatable.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/serializers/spree_cm_commissioner/api/v2/platform/homepage_section_relatable_options_serializer.rb
  app/views/spree/admin/homepage_section/edit.html.erb
  app/views/spree/admin/homepage_section_relatable/_form.html.erb
  app/views/spree/admin/homepage_section_relatable/edit.html.erb
  app/views/spree/admin/homepage_section_relatable/new.html.erb
  config/routes.rb
  lib/spree_cm_commissioner/test_helper/factories/homepage_section_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/homepage_section_relatable_factory.rb
  spec/models/spree_cm_commissioner/homepage_section_relatable_spec.rb
  spec/models/spree_cm_commissioner/homepage_section_spec.rb
Labels: enhancement, S

#1018 close #1012 api get line items ticket guests with qr datas
  app/controllers/spree/api/v2/operator/line_items_controller.rb
  app/serializers/spree_cm_commissioner/v2/operator/base_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/guest_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/line_item_order_serializer.rb
  app/serializers/spree_cm_commissioner/v2/operator/line_item_serializer.rb
  config/routes.rb
Labels: api, S

#1019 Close #1010 create a tab page and a page to list all vendors
  app/controllers/spree/admin/taxon_vendors_controller.rb
  app/overrides/spree/admin/taxons/edit/taxonomies_tabs.html.erb.deface
  app/views/spree/admin/shared/_taxonomies_tabs.html.erb
  config/routes.rb
Labels: enhancement, backend, L

#1023 Close #1022 List all vendors in taxonomies
  app/controllers/spree/admin/taxon_vendors_controller.rb
  app/overrides/spree/admin/taxons/edit/taxon_tabs.html.erb.deface
  app/overrides/spree/admin/taxons/edit/taxonomies_tabs.html.erb.deface
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  app/views/spree/admin/taxon_vendors/_form.html.erb
  app/views/spree/admin/taxon_vendors/edit.html.erb
  app/views/spree/admin/taxon_vendors/index.html.erb
  app/views/spree/admin/taxon_vendors/new.html.erb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: enhancement, M

#1026 close #1025 add name to guest_line_items_serializer
  app/serializers/spree_cm_commissioner/v2/storefront/guest_line_item_serializer.rb
Labels: enhancement, XS

#1032 Close #1029 create buttons for adding a new vendor and change the page title to taxonomies/taxon name/vendor
  app/controllers/spree/admin/taxon_vendors_controller.rb
  app/views/spree/admin/taxon_vendors/_form.html.erb
  app/views/spree/admin/taxon_vendors/edit.html.erb
  app/views/spree/admin/taxon_vendors/index.html.erb
  app/views/spree/admin/taxon_vendors/new.html.erb
Labels: enhancement, M

#1034 Close #1033 Modify Invoice for Billing
  app/views/spree/billing/shared/_invoice.html.erb
Labels: backend

#1027 close #1021 create guest occupation item adjustment
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/promotion/actions/create_guest_item_adjustments.rb
  app/models/spree_cm_commissioner/promotion_decorator.rb
  app/views/spree/admin/promotions/actions/_create_guest_item_adjustments.html.erb
  config/locales/en.yml
  config/locales/km.yml
  lib/spree_cm_commissioner/engine.rb
  spec/models/spree_cm_commissioner/promotion/actions/create_guest_item_adjustments_spec.rb
Labels: backend, M

#1036 close #1035 add show method to guest line items controller
  app/controllers/spree/api/v2/storefront/guest_line_items_controller.rb
Labels: enhancement, XS

#1040 close #1030 promotion rule by guest age
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/promotion/rules/guest.rb
  app/models/spree_cm_commissioner/promotion/rules/guest_ages.rb
  app/models/spree_cm_commissioner/promotion/rules/guest_occupations.rb
  app/views/spree/admin/promotions/rules/_guest_ages.html.erb
  config/locales/en.yml
  config/locales/km.yml
  docs/sql/subscriptions/add_new_promotion.md
  lib/spree_cm_commissioner/engine.rb
  spec/models/spree_cm_commissioner/promotion/rules/guest_ages_spec.rb
Labels: backend, M

#1046 Close #1043 Fix the error on page create_new_vendor when default value none
  app/controllers/spree/admin/taxon_vendors_controller.rb
  app/models/spree_cm_commissioner/taxon_vendor.rb
  app/views/spree/admin/taxon_vendors/_form.html.erb
  app/views/spree/admin/taxon_vendors/new.html.erb
Labels: enhancement, M

#1056 close #1051 setup database and CRUD user_taxons in admin dashboard
  app/controllers/spree/admin/user_taxons_controller.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/models/spree_cm_commissioner/user_event.rb
  app/models/spree_cm_commissioner/user_taxon.rb
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  app/views/spree/admin/user_taxons/_form.html.erb
  app/views/spree/admin/user_taxons/edit.html.erb
  app/views/spree/admin/user_taxons/index.html.erb
  app/views/spree/admin/user_taxons/new.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20240126073735_create_spree_cm_commissioner_user_taxons.rb
  spec/models/spree_cm_commissioner/user_spec.rb
  spec/models/spree_cm_commissioner/user_taxon_spec.rb
Labels: backend, M

#1060 close #1059 update homepage_section attribute(updated_at) when its relatable is updated
  app/models/spree_cm_commissioner/homepage_section_relatable.rb
  spec/models/spree_cm_commissioner/homepage_section_relatable_spec.rb
Labels: enhancement, S

#1063 close #1062 allow add & remove guest base on number of guest per quantity
  app/controllers/spree/api/v2/storefront/cart_guests_controller.rb
  app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
  app/models/concerns/spree_cm_commissioner/variant_guests_concern.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/serializers/spree_cm_commissioner/v2/storefront/guest_line_item_serializer.rb
  app/services/spree_cm_commissioner/cart/add_guest.rb
  app/services/spree_cm_commissioner/cart/remove_guest.rb
  config/routes.rb
  lib/spree_cm_commissioner/test_helper/factories/guest_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory .rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/variant_spec.rb
  spec/services/spree_cm_commissioner/cart/add_guest_spec.rb
  spec/services/spree_cm_commissioner/cart/remove_guest_spec.rb
Labels: feature, M
