Repository channainfo/commissioner, pull requests merged in 2025-05, with the labels that each got.

#2556 Close #2431 Refactor cm_place to use nestedset
  .github/workflows/test_and_build_gem.yml
  .vscode/settings.json
  app/models/spree_cm_commissioner/place.rb
  db/migrate/20250418072528_add_nested_set_columns_to_places.rb
  lib/spree_cm_commissioner/test_helper/factories/place_factory.rb
  lib/tasks/migrate_and_rebuild_place_hierarchy.rake
  lib/tasks/update_orphan_root_places.rake
  spec/models/spree_cm_commissioner/place_spec.rb
Labels: enhancement

#2594 Close #2593 encrypt the payload for vattanac bank
  app/interactors/spree_cm_commissioner/vattanac_bank_initiator.rb
  app/services/spree_cm_commissioner/aes_encryption_service.rb
  spec/interactors/spree_cm_commissioner/vattanac_bank_initiator_spec.rb
  spec/services/spree_cm_commissioner/aes_encryption_service_spec.rb
Labels: enhancement

#2605 Close #2604 add migration for taxon_option_type and taxon_option_value
  app/interactors/spree_cm_commissioner/create_event.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/taxon_option_type.rb
  app/models/spree_cm_commissioner/taxon_option_value.rb
  db/migrate/20250430091742_create_cm_taxon_option_types.rb
  db/migrate/20250430092928_create_cm_taxon_option_values.rb
  spec/models/spree_cm_commissioner/taxon_option_value_spec.rb
Labels: backend

#2603 Close #2581 add product_type to variant, line item
  app/interactors/spree_cm_commissioner/ensure_correct_product_type.rb
  app/interactors/spree_cm_commissioner/stock/permanent_inventory_items_generator.rb
  app/jobs/spree_cm_commissioner/ensure_correct_product_type_job.rb
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/models/spree_cm_commissioner/inventory_item.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/redis_stock/line_items_cached_inventory_items_builder.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  db/migrate/20250502025848_add_index_to_spree_products.rb
  db/migrate/20250502030001_add_product_type_to_spree_variants.rb
  db/migrate/20250502030002_add_product_type_to_spree_line_items.rb
  lib/spree_cm_commissioner/test_helper/factories/homepage_section_relatable_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/inventory_item_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/line_item_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/stock_location_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/variant_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/vendor_factory.rb
  lib/tasks/ensure_correct_product_type.rake
  spec/controllers/spree/api/v2/storefront/wishlists_controller_decorator_spec.rb
  spec/factory/spree_cm_commissioner/order_telegram_message_factory_spec.rb
  spec/interactors/spree_cm_commissioner/check_in_bulk_creator_spec.rb
  spec/interactors/spree_cm_commissioner/check_in_destroyer_spec.rb
  spec/interactors/spree_cm_commissioner/conversion_pre_calculator_spec.rb
  spec/interactors/spree_cm_commissioner/ensure_correct_product_type_spec.rb
  spec/interactors/spree_cm_commissioner/stock/permanent_inventory_items_generator_spec.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
  spec/interactors/spree_cm_commissioner/vendor_updater_spec.rb
  spec/jobs/spree_cm_commissioner/ensure_correct_product_type_job_spec.rb
  spec/jobs/spree_cm_commissioner/ensure_event_id_for_guests_job_spec.rb
  spec/lib/spree_cm_commissioner_spec.rb
  spec/models/concerns/spree_cm_commissioner/variant_options_concern_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree/order_spec.rb
  spec/models/spree/product_spec.rb
  spec/models/spree/stock_movement_spec.rb
  spec/models/spree/variant_spec.rb
  spec/models/spree/vendor_spec.rb
  spec/models/spree_cm_commissioner/customer_spec.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
  spec/models/spree_cm_commissioner/inventory_item_spec.rb
  spec/models/spree_cm_commissioner/promotion/actions/create_guest_item_adjustments_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/guest_age_group_spec.rb
  spec/models/spree_cm_commissioner/promotion/rules/guest_occupations_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/inventory_updater_spec.rb
  spec/models/spree_cm_commissioner/stock/availability_checker_spec.rb
  spec/models/spree_cm_commissioner/subscription_spec.rb
  spec/models/spree_cm_commissioner/variant_options_spec.rb
  spec/queries/spree_cm_commissioner/event_ticket_aggregator_query_spec.rb
  spec/queries/spree_cm_commissioner/line_item_searcher_query_spec.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
  spec/request/spree/api/v2/storefront/accommodations/variants_request_spec.rb
  spec/request/spree/api/v2/storefront/accommodations_request_spec.rb
  spec/services/spree/orders/generate_commissions_spec.rb
  spec/services/spree_cm_commissioner/imports/create_order_service_spec.rb
  spec/services/spree_cm_commissioner/imports/update_order_service_spec.rb
  spec/services/spree_cm_commissioner/organizer/export_guest_csv_service_spec.rb
Labels: enhancement

#2613 Close #2612 guest export with bib number
  app/services/spree_cm_commissioner/organizer/export_guest_csv_service.rb
Labels: enhancement, XS

#2597 Close #2519 run redis in spec
  .github/workflows/test_and_build_gem.yml
  Rakefile
  lib/generators/spree_cm_commissioner/install/install_generator.rb
  spec/redis_spec.rb
Labels: enhancement, spec

#2602 Close #2601 Vendor Trip Stop Place Search Query
  app/models/spree_cm_commissioner/trip.rb
  app/models/spree_cm_commissioner/trip_stop.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/vendor_stop.rb
  app/queries/spree_cm_commissioner/vendor_stop_place_query.rb
  db/migrate/20250506092929_add_trip_count_to_cm_vendor_stops.rb
  spec/queries/spree_cm_commissioner/trip_query_spec.rb
  spec/queries/spree_cm_commissioner/trip_search_query_spec.rb
  spec/queries/spree_cm_commissioner/vendor_stop_place_query_spec.rb
Labels: api, backend

#2590 Close #2589 add idcard tenant guest api
  app/serializers/spree/v2/tenant/guest_serializer.rb
  spec/serializers/spree/v2/tenant/guest_serializer_spec.rb
Labels: api, XS

#2600 Close #2585 sync inventory item when stock movement created from controller
  app/controllers/spree/admin/stock_managements_controller.rb
  app/interactors/spree_cm_commissioner/stock/inventory_items_adjuster.rb
  app/interactors/spree_cm_commissioner/stock/inventory_items_generator.rb
  app/interactors/spree_cm_commissioner/stock/permanent_inventory_items_generator.rb
  app/interactors/spree_cm_commissioner/stock/stock_movement_creator.rb
  app/jobs/spree_cm_commissioner/stock/inventory_items_adjuster_job.rb
  app/jobs/spree_cm_commissioner/stock/inventory_items_generator_job.rb
  app/models/spree_cm_commissioner/inventory_item.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/stock_item_decorator.rb
  app/models/spree_cm_commissioner/stock_movement_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/views/spree/admin/stock_managements/_variant_stock_items.html.erb
  config/initializers/spree_permitted_attributes.rb
  lib/spree_cm_commissioner/test_helper/factories/variant_factory.rb
  spec/interactors/spree_cm_commissioner/ensure_correct_product_type_spec.rb
  spec/interactors/spree_cm_commissioner/stock/inventory_items_adjuster_spec.rb
  spec/interactors/spree_cm_commissioner/stock/inventory_items_generator_spec.rb
  spec/interactors/spree_cm_commissioner/stock/permanent_inventory_items_generator_spec.rb
  spec/interactors/spree_cm_commissioner/stock/stock_movement_creator_spec.rb
  spec/jobs/spree_cm_commissioner/stock/inventory_items_adjuster_job_spec.rb
  spec/jobs/spree_cm_commissioner/stock/inventory_items_generator_job_spec.rb
  spec/models/spree/stock_movement_spec.rb
  spec/models/spree/variant_spec.rb
  spec/models/spree_cm_commissioner/inventory_item_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/cached_inventory_items_builder_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/inventory_updater_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/line_items_cached_inventory_items_builder_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/variant_cached_inventory_items_builder_spec.rb
  spec/models/spree_cm_commissioner/stock/order_availability_checker_spec.rb
  spec/models/spree_cm_commissioner/stock_item_decorator_spec.rb
  spec/request/spree/api/v2/storefront/accommodations/variants_request_spec.rb
  spec/request/spree/api/v2/storefront/accommodations_request_spec.rb
  spec/services/spree_cm_commissioner/organizer/export_guest_csv_service_spec.rb
  spec/spec_helper.rb
Labels: backend

#2517 Close #2516 fix tenant login email bug
  app/controllers/spree/api/v2/tenant/account_checker_controller.rb
  app/controllers/spree/api/v2/tenant/account_recovers_controller.rb
  app/controllers/spree/api/v2/tenant/reset_passwords_controller.rb
  app/interactors/spree_cm_commissioner/account_recover.rb
  app/interactors/spree_cm_commissioner/existing_account_checker.rb
  app/interactors/spree_cm_commissioner/user_forgotten_password_updater.rb
  app/interactors/spree_cm_commissioner/user_password_authenticator.rb
  app/models/concerns/spree_cm_commissioner/user_identity.rb
  app/overrides/spree/admin/users/index/body.html.erb.deface
  app/overrides/spree/admin/users/index/headers.html.erb.deface
  app/services/spree_cm_commissioner/user_authenticator.rb
  spec/interactors/spree_cm_commissioner/existing_account_checker_spec.rb
  spec/interactors/spree_cm_commissioner/user_password_authenticator_spec.rb
  spec/models/spree_cm_commissioner/user_spec.rb
  spec/request/spree/api/v2/account_checker_spec.rb
  spec/request/spree/spree_oauth_spec.rb
  spec/services/spree_cm_commissioner/user_authenticator_spec.rb
Labels: bug, L

#2621 Close #2620 remove logic of vehicle type from vehicle model
  app/models/spree_cm_commissioner/vehicle.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  spec/models/spree/line_item_spec.rb
  spec/queries/spree_cm_commissioner/trip_seat_layout_query_spec.rb
Labels: core, backend

#2633 Close #2632 Tenant CmsPages API
  app/controllers/spree/admin/cms_pages_controller_decorator.rb
  app/controllers/spree/api/v2/tenant/cms_pages_controller.rb
  app/controllers/spree_cm_commissioner/api/v2/storefront/cms_pages_controller_decorator.rb
  app/models/spree_cm_commissioner/cms_page_decorator.rb
  app/overrides/spree/admin/cms_pages/_form/tenant_fields.html.erb.deface
  app/overrides/spree/admin/cms_pages/index/cms_pages_tabs.html.erb.deface
  app/views/spree/admin/shared/_cms_pages_tabs.html.erb
  config/routes.rb
  db/migrate/20250512075319_add_tenant_id_to_spree_cms_pages.rb
Labels: api, XS

#2644 Close #2643 fix passing wrong send_name which cause sms to not send
  Gemfile.lock
  app/interactors/spree_cm_commissioner/pin_code_sender.rb
  app/interactors/spree_cm_commissioner/sms.rb
  app/interactors/spree_cm_commissioner/telegram_debug_pin_code_sender.rb
  app/jobs/spree_cm_commissioner/telegram_debug_pin_code_sender_job.rb
  lib/spree_cm_commissioner/version.rb
  spec/interactors/spree_cm_commissioner/pin_code_sender_spec.rb
  spec/interactors/spree_cm_commissioner/telegram_debug_pin_code_sender_spec.rb
  spec/jobs/spree_cm_commissioner/telegram_debug_pin_code_sender_job_spec.rb
Labels: bug, hotfix

#2629 Close #2626 fix new accommodation params mismatch with app
  app/controllers/spree/api/v2/storefront/accommodations/variants_controller.rb
  app/controllers/spree/api/v2/storefront/accommodations_controller.rb
  app/request_schemas/spree_cm_commissioner/accommodation_request_schema.rb
  app/request_schemas/spree_cm_commissioner/variant_request_schema.rb
  spec/request/spree/api/v2/storefront/accommodations/variants_request_spec.rb
  spec/request/spree/api/v2/storefront/accommodations_request_spec.rb
Labels: bug

#2641 Close #2638 migrate to not store checkout date
  app/finders/spree_cm_commissioner/accommodations/find.rb
  app/finders/spree_cm_commissioner/accommodations/find_variant.rb
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/spree_cm_commissioner/redis_stock/cached_inventory_items_builder.rb
  app/models/spree_cm_commissioner/redis_stock/variant_cached_inventory_items_builder.rb
  app/models/spree_cm_commissioner/stock/availability_checker.rb
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  spec/finders/spree_cm_commissioner/accommodations/find_spec.rb
  spec/finders/spree_cm_commissioner/accommodations/find_variant_spec.rb
  spec/models/concerns/spree_cm_commissioner/line_item_durationable_spec.rb
  spec/models/spree/line_item_spec.rb
  spec/models/spree_cm_commissioner/promotion/actions/create_date_specific_item_adjustments_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/line_items_cached_inventory_items_builder_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/variant_cached_inventory_items_builder_spec.rb
  spec/models/spree_cm_commissioner/stock/availability_checker_spec.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: enhancement

#2625 Close #2624 implement create ticket service
  app/interactors/spree_cm_commissioner/create_event.rb
  app/interactors/spree_cm_commissioner/create_ticket.rb
  db/migrate/20250509075429_add_max_order_quantity_to_spree_product.rb
  spec/models/spree_cm_commissioner/create_ticket_spec.rb
Labels: backend

#2652 Close #2651 move user roles assigner from interactors to services
  app/interactors/spree_cm_commissioner/user_roles_assigner.rb
  app/models/spree_cm_commissioner/role_decorator.rb
  app/overrides/spree/admin/users/_form/roles_fields.html.erb.deface
  app/services/spree_cm_commissioner/user_roles_assigner.rb
  config/locales/en.yml
  config/locales/km.yml
  lib/spree_cm_commissioner/test_helper/factories/role.rb
  spec/interactors/spree_cm_commissioner/user_roles_assigner_spec.rb
  spec/services/spree_cm_commissioner/user_roles_assigner_spec.rb
Labels: enhancement

#2636 Close #2635 implement transactional email
  app/interactors/spree_cm_commissioner/organizers_transactional_email_notifier.rb
  app/interactors/spree_cm_commissioner/transactional_email_sender.rb
  app/mailers/spree_cm_commissioner/event_transactional_mailer.rb
  app/models/concerns/spree_cm_commissioner/order_state_machine.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/transactional_email.rb
  app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
  app/views/spree_cm_commissioner/event_transactional_mailer/_event_banner.html.erb
  app/views/spree_cm_commissioner/event_transactional_mailer/_mailer_stylesheets.html.erb
  app/views/spree_cm_commissioner/event_transactional_mailer/_note.html.erb
  app/views/spree_cm_commissioner/event_transactional_mailer/_share_button.html.erb
  app/views/spree_cm_commissioner/event_transactional_mailer/send_to_organizer.html.erb
  app/views/spree_cm_commissioner/event_transactional_mailer/send_to_participant.html.erb
  app/views/spree_cm_commissioner/layouts/event_transactional_mailer.html.erb
  config/locales/en.yml
  db/migrate/20250509033437_create_spree_cm_commissioner_transactional_emails.rb
  lib/spree_cm_commissioner/test_helper/factories/taxon_home_banner_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/transactional_email_factory.rb
  spec/interactors/spree_cm_commissioner/transaction_email_sender_spec.rb
  spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
Labels: feature

#2662 Close #2661 implement custom method for vendor rules
  app/models/spree_cm_commissioner/option_type_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
Labels: enhancement

#2658 Close #2656 add jobs to update invalid nested places
  lib/tasks/update_invalid_self_root_places.rake
  lib/tasks/update_orphan_root_places.rake
Labels: enhancement

#2668 Close #2664 filter only vendor roles
  app/overrides/spree/admin/users/_form/roles_fields.html.erb.deface
Labels: bug

#2671 Close #2670 update github action config file
  .github/workflows/test_and_build_gem.yml
Labels: enhancement

#2659 Close #2657 fix min price nil
  app/models/spree_cm_commissioner/variant_decorator.rb
  spec/models/spree/variant_spec.rb
Labels: bug

#2675 Close #2674 fix bug link_to base_header_mailer
  app/mailers/spree_cm_commissioner/pin_code_mailer.rb
  app/views/spree/shared/_base_mailer_header.html.erb
Labels: bug, XS

#2679 Close #2676 CMS Page Enhancement
  app/models/spree_cm_commissioner/cms_page_decorator.rb
  app/overrides/spree/admin/cms_pages/_form/tenant_fields.html.erb.deface
Labels: enhancement, XS

#2680 Close #2155 fix read only blazer
  app/models/spree_cm_commissioner/user_decorator.rb
  spec/models/spree_cm_commissioner/promotion/actions/create_guest_item_adjustments_spec.rb
  spec/models/spree_cm_commissioner/user_spec.rb
Labels: bug

#2678 Close #2677 fix waiting room no method error
  app/interactors/spree_cm_commissioner/waiting_room_session_creator.rb
  app/interactors/spree_cm_commissioner/waiting_room_session_firebase_logger.rb
  app/jobs/spree_cm_commissioner/waiting_room_session_firebase_logger_job.rb
  spec/interactors/spree_cm_commissioner/waiting_room_session_creator_spec.rb
  spec/interactors/spree_cm_commissioner/waiting_room_session_firebase_logger_spec.rb
  spec/jobs/spree_cm_commissioner/waiting_room_session_firebase_logger_job_spec.rb
Labels: bug

#2673 Close #2672 sync updated event date to old line items
  app/interactors/spree_cm_commissioner/event_line_items_date_syncer.rb
  app/jobs/spree_cm_commissioner/event_line_items_date_syncer_job.rb
  app/models/concerns/spree_cm_commissioner/line_item_durationable.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/models/spree_cm_commissioner/taxon_decorator.rb
  app/overrides/spree/admin/taxons/_form/assets_form.html.erb.deface
  app/overrides/spree/admin/taxons/_form/available_on.html.erb.deface
  app/overrides/spree/admin/taxons/_form/background_color_and_foreground_color.html.erb.deface
  app/overrides/spree/admin/taxons/_form/custom_redirect_url.html.erb.deface
  app/overrides/spree/admin/taxons/_form/hide_video_banner.html.erb.deface
  app/overrides/spree/admin/taxons/_form/purchasable_on_status.html.erb.deface
  app/overrides/spree/admin/taxons/_form/show_badge_status.html.erb.deface
  app/overrides/spree/admin/taxons/_form/to_date_form_date.html.erb.deface
  app/overrides/spree/admin/variants/edit/variant_status.html.erb.deface
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  spec/interactors/spree_cm_commissioner/event_line_items_date_syncer_spec.rb
  spec/jobs/spree_cm_commissioner/event_line_items_date_syncer_job_spec.rb
  spec/models/spree/taxon_spec.rb
Labels: enhancement

#2623 Close #2577 add log to critical logic code
  app/interactors/spree_cm_commissioner/stock/stock_movement_creator.rb
  app/jobs/spree_cm_commissioner/application_job.rb
  app/jobs/spree_cm_commissioner/application_unique_job.rb
  app/models/concerns/spree_cm_commissioner/order_state_machine.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/stock_item_decorator.rb
  lib/cm_app_logger.rb
  spec/jobs/spree_cm_commissioner/application_job_spec.rb
  spec/jobs/spree_cm_commissioner/application_unique_job_spec.rb
  spec/lib/cm_app_logger_spec.rb
Labels: experiment
