Repository channainfo/commissioner, pull requests merged in 2025-04, with the labels that each got.

#2553 close #2552 sync inventory_item on update stock item
  app/controllers/spree/admin/stock_managements_controller.rb
  app/models/concerns/spree_cm_commissioner/product_type.rb
  app/models/spree_cm_commissioner/inventory_item.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/stock_movement_decorator.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/views/spree/admin/stock_managements/_events_popover.html.erb
  app/views/spree/admin/stock_managements/calendar.html.erb
  app/views/spree/admin/stock_managements/index.html.erb
  config/routes.rb
  db/migrate/20250304293518_create_cm_inventory_items.rb
  lib/generators/spree_cm_commissioner/install/install_generator.rb
  lib/generators/spree_cm_commissioner/install/templates/app/javascript/spree_dashboard/spree_cm_commissioner/utilities.js
  lib/spree_cm_commissioner/calendar_event.rb
  lib/tasks/create_default_non_permanent_inventory_items.rake
  spec/models/spree/product_spec.rb
  spec/models/spree/stock_movement_spec.rb
  spec/models/spree/variant_spec.rb
  spec/models/spree_cm_commissioner/inventory_item_spec.rb
Labels: feature

#2555 close #2554 create dynamic url for Vattanac bank
  .env.example
  app/controllers/spree/api/v2/storefront/vattanac_banks_controller.rb
  app/interactors/spree_cm_commissioner/user_vattanac_bank_web_app_authenticator.rb
  app/interactors/spree_cm_commissioner/vattanac_bank_initiator.rb
  app/models/spree_cm_commissioner/user_identity_provider.rb
  app/services/spree_cm_commissioner/aes_encryption_service.rb
  app/services/spree_cm_commissioner/rsa_service.rb
  app/services/spree_cm_commissioner/user_authenticator.rb
  config/routes.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/test_helper/factories/user_identity_provider_factory.rb
  lib/spree_cm_commissioner/user_session_jwt_token.rb
  spec/interactors/spree_cm_commissioner/vattanac_bank_initiator_spec.rb
  spec/services/spree_cm_commissioner/aes_encryption_service_spec.rb
  spec/services/spree_cm_commissioner/rsa_service_spec.rb
Labels: api, integration

#2557 Revert "close #2479 add reports preference to spree taxon"
  app/models/spree_cm_commissioner/taxon_decorator.rb
Labels: bug

#2560 Close #2559 create organizer url method
  app/models/spree_cm_commissioner/vendor_decorator.rb
Labels: backend

#2558 Bump version to 1.9.0
  lib/spree_cm_commissioner/version.rb
Labels: release

#2509 Close #2506 Order transition to complete, update stock in redis
  app/interactors/spree_cm_commissioner/inventory_item_syncer.rb
  app/jobs/spree_cm_commissioner/inventory_item_syncer_job.rb
  app/models/concerns/spree_cm_commissioner/order_state_machine.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  app/models/spree_cm_commissioner/redis_stock/inventory_updater.rb
  db/migrate/20250429094228_add_lock_version_to_cm_inventory_items.rb
  spec/interactors/spree_cm_commissioner/inventory_item_syncer_spec.rb
  spec/jobs/spree_cm_commissioner/inventory_item_syncer_job_spec.rb
  spec/models/concerns/spree_cm_commissioner/order_state_machine_spec.rb
  spec/models/spree_cm_commissioner/order_decorator_spec.rb
  spec/models/spree_cm_commissioner/redis_stock/inventory_updater_spec.rb
Labels: chore, core

#2580 Close #2574 add slug, description and preferences column to prototype table
  app/controllers/spree/admin/prototypes_controller_decorator.rb
  app/models/spree_cm_commissioner/prototype_decorator.rb
  app/overrides/spree/admin/prototypes/_form/description.html.erb.deface
  app/overrides/spree/admin/prototypes/_form/icon.html.erb.deface
  app/overrides/spree/admin/prototypes/_form/product_type.html.erb.deface
  db/migrate/20250425084929_add_description_to_spree_prototypes.rb
  db/migrate/20250425085938_add_preferences_to_spree_prototypes.rb
  db/migrate/20250428025645_add_slug_to_spree_prototypes.rb
Labels: enhancement, backend

#2586 Close #2584 implement CreateEvent service
  app/interactors/spree_cm_commissioner/create_event.rb
Labels: backend

#2537 Close #2536 Trip Connection uniqueness on from trip and to trip
  app/models/concerns/spree_cm_commissioner/option_type_attr_type.rb
  app/models/spree_cm_commissioner/trip_connection.rb
  app/models/spree_cm_commissioner/trip_stop.rb
  app/models/spree_cm_commissioner/variant_decorator.rb
  app/models/spree_cm_commissioner/variant_options.rb
Labels: enhancement
