Repository channainfo/commissioner, pull requests merged in 2025-02, with the labels that each got.

#2304 close #2303 images api
  app/controllers/spree/api/v2/organizer/images_controller.rb
  app/controllers/spree/api/v2/organizer/ticket_images_controller.rb
  app/interactors/spree_cm_commissioner/image_saver.rb
  app/serializers/spree/v2/organizer/image_serializer.rb
  app/serializers/spree/v2/organizer/ticket_serializer.rb
  config/locales/en.yml
  config/locales/km.yml
  config/routes.rb
Labels: api

#2325 close #2324 Tenant taxon serializer enhancement
  app/serializers/spree/v2/tenant/asset_serializer.rb
  app/serializers/spree/v2/tenant/taxon_serializer.rb
  app/serializers/spree/v2/tenant/taxonomy_serializer.rb
  spec/serializers/spree/v2/tenant/taxon_serializer_spec.rb
Labels: enhancement, api, XS

#2340 close #2337 Update and Retrieve account details included roles
  app/controllers/spree/api/v2/tenant/account_controller.rb
  app/serializers/spree/v2/tenant/address_serializer.rb
  app/serializers/spree/v2/tenant/role_serializer.rb
  app/serializers/spree/v2/tenant/taxon_serializer.rb
  app/serializers/spree/v2/tenant/user_device_token_serializer.rb
  app/serializers/spree/v2/tenant/user_serializer.rb
  config/routes.rb
  lib/spree_cm_commissioner/test_helper/factories/address_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/country_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/state_factory.rb
  spec/serializers/spree/v2/tenant/address_serializer_spec.rb
  spec/serializers/spree/v2/tenant/user_device_token_serializer_spec.rb
  spec/serializers/spree/v2/tenant/user_serializer_spec.rb
Labels: api, XS

#2343 Close #2342: Add troubleshooting db lock on taxonomy creation error
  README.md
Labels: bug

#2335 Close #2334: Add Dockerfile, and fix spec
  .gitignore
  Dockerfile
  app/controllers/spree/admin/base_controller_decorator.rb
  app/interactors/spree_cm_commissioner/order_accepted_state_updater.rb
  app/interactors/spree_cm_commissioner/order_rejected_state_updater.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  docker-compose.yml
  spec/interactors/spree_cm_commissioner/order_accepted_state_updater_spec.rb
  spec/interactors/spree_cm_commissioner/order_rejected_state_updater_spec.rb
  spec/serializers/spree/v2/storefront/option_value_serializer_spec.rb
  spec/spec_helper.rb
Labels: transit

#2327 close #2323 Tenant SignUp with PinCode and Login with Email and Password
  app/controllers/spree/api/v2/tenant/account_checker_controller.rb
  app/controllers/spree/api/v2/tenant/pin_code_checkers_controller.rb
  app/controllers/spree/api/v2/tenant/pin_code_generators_controller.rb
  app/controllers/spree/api/v2/tenant/user_registration_with_pin_codes_controller.rb
  app/models/concerns/spree_cm_commissioner/user_identity.rb
  app/models/spree_cm_commissioner/user_decorator.rb
  app/serializers/spree/v2/storefront/user_serializer_decorator.rb
  app/services/spree_cm_commissioner/user_authenticator.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20250212100328_add_foreign_key_to_spree_user_tenant_id.rb
  spec/models/spree_cm_commissioner/user_spec.rb
  spec/request/spree/spree_oauth_spec.rb
  spec/serializers/spree/v2/storefront/user_serializer_spec.rb
  spec/services/spree_cm_commissioner/user_authenticator_spec.rb
Labels: api, M

#2348 close #2347 create and delete tenant user device_token API
  app/controllers/spree/api/v2/tenant/base_controller.rb
  app/controllers/spree/api/v2/tenant/user_device_tokens_controller.rb
  config/routes.rb
Labels: api, XS

#2352 close #2307 Tenant Account Delete and Recover API
  app/controllers/spree/api/v2/tenant/account_deletions_controller.rb
  app/controllers/spree/api/v2/tenant/account_recovers_controller.rb
  config/routes.rb
Labels: api, XS

#2331 close #2330 self check in without location
  app/controllers/spree/api/v2/storefront/self_check_in_controller.rb
  app/models/concerns/spree_cm_commissioner/product_delegation.rb
  app/models/spree_cm_commissioner/line_item_decorator.rb
  app/overrides/spree/admin/products/_form/required_self_check_in_location.html.erb.deface
  app/serializers/spree/v2/storefront/line_item_serializer_decorator.rb
  db/migrate/20250214025007_add_required_self_check_in_location_to_spree_products.rb
  spec/serializers/spree/v2/storefront/line_item_serializer_spec.rb
Labels: enhancement

#2339 Close #2338 Enhancement image resolution
  app/models/spree_cm_commissioner/image_decorator.rb
  spec/models/spree/image_spec.rb
Labels: api, L

#2356 Close #2346 fix user event redirect link
  app/controllers/spree/admin/user_events_controller.rb
  app/overrides/spree/admin/users/_tabs/tabs.html.erb.deface
Labels: bug

#2363 close #2361 add indexes in cm guest for search and filter
  app/models/spree_cm_commissioner/guest.rb
  db/migrate/20250217075228_add_indexes_to_cm_guests.rb
Labels: enhancement, migration

#2354 close #2314 Tenant products API
  app/controllers/spree/api/v2/tenant/products_controller.rb
  app/controllers/spree_cm_commissioner/admin/products_controller_decorator.rb
  app/models/concerns/spree_cm_commissioner/tenant_updatable.rb
  app/models/spree_cm_commissioner/homepage_section.rb
  app/models/spree_cm_commissioner/product_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/overrides/spree/admin/products/_form/replace_vendor_label.html.erb.deface
  app/services/spree_cm_commissioner/user_authenticator.rb
  config/routes.rb
Labels: api, XS

#2362 close #2360 Tenant Scope Overrided
  app/controllers/spree/api/v2/tenant/base_controller.rb
  app/controllers/spree/api/v2/tenant/homepage_sections_controller.rb
  app/controllers/spree/api/v2/tenant/products_controller.rb
Labels: enhancement

#2357 close #2353 Build API tenant Booking cart flow
  app/controllers/spree/api/v2/tenant/base_controller.rb
  app/controllers/spree/api/v2/tenant/cart_controller.rb
  app/controllers/spree/api/v2/tenant/cart_guests_controller.rb
  app/controllers/spree/api/v2/tenant/homepage_sections_controller.rb
  app/controllers/spree/api/v2/tenant/products_controller.rb
  app/controllers/spree/api/v2/tenant/vendors_controller.rb
  app/models/spree_cm_commissioner/order_decorator.rb
  config/routes.rb
Labels: api, M

#2378 close #2377 tenant guest informations API
  app/controllers/spree/api/v2/tenant/cart_controller.rb
  app/controllers/spree/api/v2/tenant/guests_controller.rb
  app/serializers/spree/v2/tenant/guest_serializer.rb
  config/routes.rb
  spec/serializers/spree/v2/tenant/guest_serializer_spec.rb
Labels: api, XS

#2386 close #2385 validate available stock
  app/models/spree_cm_commissioner/variant_decorator.rb
  spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
Labels: enhancement

#2391 close #2390 create event slug method
  app/models/spree_cm_commissioner/taxon_decorator.rb
Labels: enhancement

#2380 close #2379 fix guest card cannot set back to none
  app/controllers/spree/admin/variant_guest_card_classes_controller.rb
  app/views/spree/admin/variant_guest_card_classes/index.html.erb
Labels: enhancement

#2393 close #2392 user association and apply/remove coupon to order
  app/controllers/spree/api/v2/tenant/cart_controller.rb
  config/routes.rb
Labels: api, XS

#2394 close #2381 ReadMe active-record-multitenant and scope product and homepage
  README.md
  app/controllers/spree/api/v2/tenant/homepage_sections_controller.rb
  app/controllers/spree/api/v2/tenant/products_controller.rb
Labels: documentation, XS

#2374 close #2371 Remove email Unique index Constraint from User And Scope it By Tenant
  app/models/concerns/spree_cm_commissioner/user_identity.rb
  db/migrate/20250220021751_remove_unique_constraint_from_email_in_spree_users.rb
  db/migrate/20250226092650_add_index_to_email_in_spree_users.rb
  spec/models/spree_cm_commissioner/user_spec.rb
Labels: enhancement, XS

#2396 close #2395 create user roles assigner interactor
  app/interactors/spree_cm_commissioner/user_roles_assigner.rb
  config/locales/en.yml
  config/locales/km.yml
  spec/interactors/spree_cm_commissioner/user_roles_assigner_spec.rb
Labels: backend

#2402 close #2401 enhance event url
  app/models/spree_cm_commissioner/taxon_decorator.rb
Labels: enhancement

#2403 close #2399 tenant user account linkages
  app/controllers/spree/api/v2/tenant/user_account_linkages_controller.rb
  app/serializers/spree/v2/tenant/user_identity_provider_serializer.rb
  config/routes.rb
Labels: api, XS
