Repository channainfo/commissioner, pull requests merged in 2025-01, with the labels that each got.

#2215 Close #2214 added icon to view vendor from product view
  app/overrides/spree/admin/products/_form/replace_vendor_label.html.erb.deface
Labels: enhancement

#2220 Close #2219 Organizer fetch ticket api
  app/controllers/spree/api/v2/organizer/base_controller.rb
  app/controllers/spree/api/v2/organizer/tickets_controller.rb
  app/serializers/spree/v2/organizer/base_serializer.rb
  app/serializers/spree/v2/organizer/ticket_serializer.rb
  config/routes.rb
Labels: api

#2205 close #2204 check item availability before add to queue
  app/controllers/spree/api/v2/storefront/queue_cart/line_items_controller.rb
  app/models/spree_cm_commissioner/stock/availability_checker.rb
  app/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query.rb
  config/locales/en.yml
  config/locales/km.yml
  spec/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query_spec.rb
Labels: bug, enhancement

#2209 Close #2208 Add the "canceled" state to the line item filter scop
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
Labels: api

#2203 close #2202 improve set up google wallet
  app/controllers/spree/admin/google_wallets_controller.rb
  app/helpers/spree/admin/google_wallets_helper.rb
  app/models/spree_cm_commissioner/event_ticket_google_wallet.rb
  app/models/spree_cm_commissioner/google_wallet.rb
  app/services/spree_cm_commissioner/google_wallets/base_event_ticket_class.rb
  app/views/spree/admin/google_wallets/_form.html.erb
  app/views/spree/admin/google_wallets/edit.html.erb
  config/routes.rb
Labels: enhancement

#2232 close #2231 Segment waiting-guests by date
  app/interactors/spree_cm_commissioner/waiting_guests_caller.rb
  app/interactors/spree_cm_commissioner/waiting_room_session_creator.rb
Labels: enhancement, XS

#2240 Close #2239 make block forwarding consistent
  .rubocop.yml
  app/controllers/spree_cm_commissioner/action_controller/api_decorator.rb
  app/controllers/spree_cm_commissioner/application_controller_decorator.rb
Labels: enhancement

#2243 close #2241 handle no available quantity case
  app/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query.rb
  spec/queries/spree_cm_commissioner/variant_availability/non_permanent_stock_query_spec.rb
Labels: enhancement

#2230 close #2229 missing translation on link account fail
  config/locales/en.yml
  config/locales/km.yml
Labels: bug

#2244 close #2236 fix noticed response content cachable
  app/controllers/concerns/spree_cm_commissioner/content_cachable.rb
Labels: bug, XS

#2242 Close #2233 Fix the canceled state when the payment state fails
  app/controllers/spree/api/v2/storefront/line_items_controller.rb
  app/models/concerns/spree_cm_commissioner/line_items_filter_scope.rb
  spec/models/spree/line_item_spec.rb
Labels: api

#2246 close #2225 out of stock even still instock
  app/controllers/spree/admin/stock_managements_controller.rb
  app/views/spree/admin/stock_managements/_variant_stock_items.html.erb
  app/views/spree/admin/stock_managements/index.html.erb
Labels: bug, enhancement

#2248 close #2187 separate UniqueJob and ApplicationJob
  app/jobs/application_unique_job.rb
  app/jobs/spree_cm_commissioner/application_unique_job.rb
  app/jobs/spree_cm_commissioner/chatrace_order_creator_job.rb
  app/jobs/spree_cm_commissioner/conversion_pre_calculator_job.rb
  app/jobs/spree_cm_commissioner/customer_content_notification_creator_job.rb
  app/jobs/spree_cm_commissioner/customer_notification_sender_job.rb
  app/jobs/spree_cm_commissioner/enqueue_cart/add_item_job.rb
  app/jobs/spree_cm_commissioner/export_csv_job.rb
  app/jobs/spree_cm_commissioner/import_order_job.rb
  app/jobs/spree_cm_commissioner/invalidate_cache_request_job.rb
  app/jobs/spree_cm_commissioner/option_type_variants_public_metadata_updater_job.rb
  app/jobs/spree_cm_commissioner/option_value_variants_public_metadata_updater_job.rb
  app/jobs/spree_cm_commissioner/order_complete_telegram_sender_job.rb
  app/jobs/spree_cm_commissioner/queue_order_webhooks_requests_job.rb
  app/jobs/spree_cm_commissioner/sms_job.rb
  app/jobs/spree_cm_commissioner/state_job.rb
  app/jobs/spree_cm_commissioner/telegram_debug_pin_code_sender_job.rb
  app/jobs/spree_cm_commissioner/telegram_notification_sender_job.rb
  app/jobs/spree_cm_commissioner/telegram_start_message_sender_job.rb
  app/jobs/spree_cm_commissioner/vendor_job.rb
  app/jobs/spree_cm_commissioner/webhook_subscriber_orders_sender_job.rb
Labels: bug, XS

#2273 Close #2267 fix vendor null problem
  app/overrides/spree/admin/products/_form/replace_vendor_label.html.erb.deface
Labels: enhancement

#2272 close #2270 allow calling generate vendor_commissions multiple time
  app/services/spree_cm_commissioner/orders/generate_commissions_decorator.rb
  spec/services/spree/orders/generate_commissions_spec.rb
Labels: bug

#2274 close #2271 pre create bib prefix on create guest (no need to wait order complete)
  app/models/concerns/spree_cm_commissioner/option_type_attr_type.rb
  app/models/concerns/spree_cm_commissioner/variant_options_concern.rb
  app/models/spree_cm_commissioner/guest.rb
  app/models/spree_cm_commissioner/variant_options.rb
  lib/spree_cm_commissioner/test_helper/factories/option_type_factory.rb
  lib/spree_cm_commissioner/test_helper/factories/product_factory.rb
  spec/models/spree_cm_commissioner/guest_spec.rb
Labels: enhancement

#2281 close #2280 allow import order with quantity
  app/interactors/spree_cm_commissioner/import_csv_template_downloader.rb
  app/services/spree_cm_commissioner/imports/create_order_service.rb
  spec/services/spree_cm_commissioner/imports/create_order_service_spec.rb
Labels: enhancement, backend

#2253 close #2252 remove passed events from homepage section in app
  app/controllers/spree/admin/base_controller_decorator.rb
  app/controllers/spree/admin/homepage_section_relatable_controller.rb
  app/models/spree_cm_commissioner/homepage_section_relatable.rb
  app/views/spree/admin/homepage_section_relatable/_form.html.erb
  db/migrate/20250116081414_remove_active_from_homepage_sections_relatables.rb
  db/migrate/20250117092553_add_available_on_and_discontinue_on_to_homepage_section_relatables.rb
  lib/spree_cm_commissioner/test_helper/factories/homepage_section_relatable_factory.rb
  spec/models/spree_cm_commissioner/homepage_section_relatable_spec.rb
Labels: enhancement

#2286 close #2285 product available on and discontinue on not showing time when edit
  app/overrides/spree/admin/products/_form/available_on.html.erb.deface
  app/overrides/spree/admin/products/_form/discontinue_on.html.erb.deface
Labels: bug, enhancement

#2290 close #2289 implement muilti_tenantcy ERD and migration
  app/models/spree_cm_commissioner/tenant.rb
  db/migrate/20250122083010_create_cm_tenants.rb
  db/migrate/20250122084511_add_tenant_id_to_spree_vendors.rb
  db/migrate/20250124033405_add_tenant_id_to_spree_users.rb
  db/migrate/20250124034040_add_tenant_id_to_cm_notifications.rb
  db/migrate/20250124034128_add_tenant_id_to_spree_orders.rb
  db/migrate/20250124034153_add_tenant_id_to_spree_products.rb
  spree_cm_commissioner.gemspec
Labels: backend, S

#2294 close #2293 create api tenant vendor and add tenant to Oauth application
  app/controllers/spree/api/v2/tenant/base_controller.rb
  app/controllers/spree/api/v2/tenant/vendors_controller.rb
  app/models/spree_cm_commissioner/oauth_application_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/overrides/spree/admin/oauth_applications/_form/tenant_fields.html.erb.deface
  app/serializers/spree/v2/tenant/base_serializer.rb
  app/serializers/spree/v2/tenant/vendor_image_serializer.rb
  app/serializers/spree/v2/tenant/vendor_serializer.rb
  config/routes.rb
  db/migrate/20250123162946_add_tenant_id_to_spree_oauth_applications.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/test_helper/factories/tenant_factory.rb
  spec/serializers/spree/v2/tenant/vendor_serializer_spec.rb
Labels: api, XS

#2299 close #2293 create api tenant vendor and add tenant to oauth application
  app/controllers/spree/api/v2/tenant/base_controller.rb
  app/controllers/spree/api/v2/tenant/vendors_controller.rb
  app/models/spree_cm_commissioner/oauth_application_decorator.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/overrides/spree/admin/oauth_applications/_form/tenant_fields.html.erb.deface
  app/serializers/spree/v2/tenant/base_serializer.rb
  app/serializers/spree/v2/tenant/vendor_image_serializer.rb
  app/serializers/spree/v2/tenant/vendor_serializer.rb
  config/routes.rb
  db/migrate/20250123162946_add_tenant_id_to_spree_oauth_applications.rb
  lib/spree_cm_commissioner.rb
  lib/spree_cm_commissioner/test_helper/factories/tenant_factory.rb
  spec/serializers/spree/v2/tenant/vendor_serializer_spec.rb
Labels: S

#2255 Close #2247: stop retry fcm queue when missing notification record
  app/jobs/spree_cm_commissioner/application_job_decorator.rb
  lib/cm_app_logger.rb
  lib/spree_cm_commissioner.rb
  spec/jobs/spree_cm_commissioner/application_job_decorator_spec.rb
  spec/lib/cm_app_logger_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#2301 close #2300 s3 sign url api for organizer app
  app/controllers/spree/api/v2/organizer/s3_signed_urls_controller.rb
  app/serializers/spree/v2/organizer/s3_signed_url_serializer.rb
  config/routes.rb
Labels: api

#2302 close #2298 enchance tenant
  app/controllers/spree/admin/tenant_vendors_controller.rb
  app/controllers/spree/admin/tenants_controller.rb
  app/models/spree_cm_commissioner/tenant.rb
  app/models/spree_cm_commissioner/vendor_decorator.rb
  app/overrides/spree/admin/shared/sub_menu/_organizations/tenants_tab.html.erb.deface
  app/views/spree/admin/tenant_vendors/_assign_tenant_vendor.html.erb
  app/views/spree/admin/tenant_vendors/index.html.erb
  app/views/spree/admin/tenants/_form.html.erb
  app/views/spree/admin/tenants/_tabs.html.erb
  app/views/spree/admin/tenants/edit.html.erb
  app/views/spree/admin/tenants/index.html.erb
  app/views/spree/admin/tenants/new.html.erb
  config/routes.rb
  db/migrate/20250127081645_add_fields_to_cm_tenants.rb
Labels: M

#2292 close #2291 Remove homepage section when events are inactive
  app/models/spree_cm_commissioner/homepage_section.rb
  spec/models/spree_cm_commissioner/homepage_section_spec.rb
Labels: enhancement

#2250 Close #2249 Add section tab in taxon edit screen
  app/controllers/spree/admin/taxon_childrens_controller.rb
  app/overrides/spree/admin/taxons/edit/title.html.erb.deface
  app/views/spree/admin/classifications/index.html.erb
  app/views/spree/admin/guest_card_classes/index.html.erb
  app/views/spree/admin/shared/_taxon_tabs.html.erb
  app/views/spree/admin/taxon_childrens/index.html.erb
  app/views/spree/admin/taxon_vendors/index.html.erb
  app/views/spree/admin/user_events/_users.html.erb
  config/routes.rb
Labels: enhancement, feature

#2312 close #2311 fix homepage section scope
  app/models/spree_cm_commissioner/homepage_section.rb
Labels: bug, XS

#2310 close #2309 fetch tenant homepage api and UI Tab filter Enhancement
  app/controllers/spree/admin/homepage_section_controller.rb
  app/controllers/spree/api/v2/storefront/homepage_sections_controller.rb
  app/controllers/spree/api/v2/tenant/base_controller.rb
  app/controllers/spree/api/v2/tenant/homepage_sections_controller.rb
  app/controllers/spree/api/v2/tenant/vendors_controller.rb
  app/models/spree_cm_commissioner/homepage_section.rb
  app/serializers/spree/v2/tenant/homepage_section_relatable_serializer.rb
  app/serializers/spree/v2/tenant/homepage_section_serializer.rb
  app/serializers/spree/v2/tenant/taxon_serializer.rb
  app/views/spree/admin/homepage_section/_form.html.erb
  app/views/spree/admin/homepage_section/_tabs.html.erb
  app/views/spree/admin/homepage_section/index.html.erb
  config/routes.rb
  db/migrate/20250131024730_add_tenant_id_to_cm_homepage_section.rb
  spec/serializers/spree/v2/tenant/homepage_section_relatable_serializer_spec.rb
  spec/serializers/spree/v2/tenant/homepage_section_serializer_spec.rb
  spec/serializers/spree/v2/tenant/taxon_serializer_spec.rb
Labels: api, S
